### ISSUE TITLE
'preact/hooks' does not provide an export named 'default'

### ISSUE THREAD

**Issue by sibbng** [jspm/project#100]
Hi, I'm trying to convert my Skypack example to jspm version. 

[Skypack demo](https://jspm.org/sandbox#H4sIAAAAAAAAA41VwW7bMAy99ytYIyicLY3XnobW9rAVA7ZDT8V2GQbUkZhZiCwZtpQ2CPzvoyXLdZJt3ckRRT4+PlJMes41M7saoTSVzM/S8MGC52cAaYWmAFYWTYsmi6xZX76P3IURRmL+qVihhM/PRVVLTBNvHONUUWEWbQU+1boxETCtDCrCeRLclBnHrWB46Q4LEEoYUcjLlhUSsyvKkiaeRrrSfOdQW9aI2kBPOIsqza1ExwZAVH0K2AMhNag4NtDButEVRKUxdXuTJIyrZbvZ1QXbLCl1UjdYMBPdHsbbFh9MYfA/w5NS6017CEIavhJLHkd53QGA41oovNNkVaTUYjA3uA4/Gd1ZgzyctbrXVh0YvqlqanqtEFeH2Fp8UeTMZ1KtK0ZC1n+WK6F4XM4Pru93dy5XQz5H5OOBUJIADY+tYW0VJdKKWg3fLQ7Xcd3oup1Dlo8qBHA2QpMA3m+5LaTF+e2RJ9d2JZGTZ9Anjh3kAOHD4A1cn4QKxSjMe8eH7m8zuArlHmg9gqtWS1xK/SuOgg6D9tF8kmnSk3+FWjUNHqMbUq9RNJsDu0Uod+HIdyFPt3hRPGhdSKeIa0ivu29xkP6vkEftIMCdtsAK1b+PAQTc6EOJDR5T7YfmcTTSw+Vim0/Og2W2H9J38AzX1IXZfqDRpclpyMoaQ9Oj1Z0UbJPN9kS1y78qRnRa2j7+fhp0hPI4KuW+QeNxLj/WNXVnP760fjx+tKV+WvQT/EA/fhLJsCFi07hJHN/oH0o/5ezbP8DF5z36vJtynu17G3yA6IvgGMENRL1r1IVevYCfVDzEXlx4GulsP77PDtxME4Ordx0k+WM3RHmynS/Dr844RJMgHbn208FsRSO07FexG+w08cu4X9N+P6eJ//P4DZ9SmlpUBgAA)

[jspm demo](https://jspm.org/sandbox#H4sIAAAAAAAAA41Wa0/jOBT93l9xyaJRu7RJC7sSj7ZLVRADOx2xU8pqZrUSIXGJIbEzsdNSqvz3vX4k9MEwKwGJfe899/j42KS7E/JALlICkUzifq1bPogf9msA3YRIH4LIzwSRPSeX09ahowOSypj0J0w/w65nxlUJ8xPSc2aUzFOeSQcCziRhCDGnoYx6IZnRgLT0oAmUUUn9uCUCPya9DjboeoZB956HC42602rB+RhGPMxjAuOIJuIYLhOFDomfCkh5vJjSOIYpzyDRaQLuMz4XJBMwpzLiuQS6UiHyVA/qPlaR54CkEoZRxhMCh0d7DWi1dGcRZBQjvliwAEQW9JxIylQce96D7z6KNHEp91iaHBPRMn1bQtE7bbsd/PFCKqS3EXMTyrDW6Xc9A6862WXiA+BqfD2CC8JI5ktcj13oyE919DykEiZfPh1DRaVMrRj9Mtm/ffh6cRadHbazxfjlajzpRIvh41V4c/b36Gjw8nX8wMdPndEndj7//Hnw0rkZtb/k19+/7d2wb8/By8Nosli005uPf720H69vR0fDiz8Hl4OnuXi+GQyQx7o+ykU9x+iL8mqXLDVbOymcYzuBU+gzHP5ISYyeHrht9zcjHg6VWM2yOM2IH8h36k3CKcr/u9s5MCBmzjW78AacF3H+JP4/qE63/NTrW8i6gs5y4v2UcpWKtjnAhVtSeFBcykLyrHA1bGHQHRHwlGxouoW8EsaEU8XENqJy8Q6bjUy9GUfrZJobuAIvCRL+DNNkvYVn4Ypa+Vf9bh6PNa8ZwbXRoDzYS8D7JCMImkEBUzzMlV1O1vNyQcbSl2QjzdpgLRn9Z3OUbddxLO2QTCkjQ46zDO+5UpyMTMvXAGO5JGE55mzEc7Y2MWHJ6lRJbMtFikGtZkCZ0Pxi6KmHe4961qPGyWp4tBhq2AxzNnjWbW/PA7zg8xSmOcNenOGdDLc5seF6mvFUNKDXX7GTAQ8qaFyryXNnfpyTxslGZsjze/xXgZmlFPW6hrQQpgx+hf2tUoo3bw9Mdn09fa8HnXK5a7JW4ExwPJYxf6g7pQ5WZqex0mlF/vdKc7ZaXFVnqF7G0FaWXbNcblOTL8o+RfNV8VJrP9aK6A1RuptdLqX/IeTGdiDggucQ+ExZ24KAdjNEJCObVJVp7qpJPFshnfVXxnZmd2nbF/AM+7gLu0tLo+h62yX3uZToHs6GMQ2eertLpFr0L1mAdATpeia+WrSBclcppZ+lxpUvB2mKu7OsDpWyxz8i4vOmcvAYX/5FkuXhrstMO7E6jm8sfZuz2X4LV99R6I1ilfPuUs3BH+B8pCFxAC89leoU5V69gm+t2NZ++GBodHeX1fksQHsaGXTaBXj9u8JW3dlLsWYWoW63elmNghSYqtwR5AlayFXfTNrYr7cn0tAfUl3PfOD9By8aLWL4CQAA)

Skypack example works as expected but jspm example throws that error:
>Uncaught SyntaxError: The requested module 'preact/hooks' does not provide an export named 'default' sandbox:1:-33

`reactivue` package internally imports preact/hooks but jspm trying to import its default export which is not exist.

**Comment by guybedford** [comment]
Thanks for posting the issue. This was actually a bug in the generator - I've posted up a fix so if you refresh the generator it should be correctly generating the map now.

The corresponding sandbox demo is [here](https://jspm.org/sandbox#H4sIAAAAAAAAA41VbVPaQBD+7q/Ypl+0kgRqOyMYGBh1fKk4VEBHv53JQk6TXJo7hNDxv3dzFxhefOkMEO5297lnn9vdeF8C4as8RQhVHLV2vMUDWdDaAfBiVAz8kGUSVdOaqJF9aGmD4irC1jDRz8BzzXoZkrAYm9YLx2kqMmWBLxKFCUFMeaDCZoAv3EdbLyrAE644i2zpswibNTrAcw0D71EEuUb9Yttw2oeuCCYRQj/ksWzARVygQ8xSCamI8hGPIhiJDGLtJuExE1OJmYQpV6GYKOArEXKS6sUuoyic+ZgqOA4zESMc1vf3wLb1ydLPOFmYzBMfZOY3rVCpVDZcd8ycJ5nGDhduksYNlLY515YFvXbVqdHHDbhU7obNiXlCsVbLcw18cVKZJj0ALvu9LpxhghlTlE+ZaJel2noacAXDm6sGLKksXJeMvg6/347vz07Ck8Nqlvfnl/1hLcyPny6Dwcldt96Z3/fHov9c614lp9Pr6868NuhWbya9Pw/7g+Rh5s/H3WGeV9PB+e959al3260fn/3qXHSep3I26HSIx7o+RRU1LaMvyaur5K9mW25Kq1Fu0BbVGS3fU5Ks7QOn6vww4tGyEKuyCE4zZL76IN44tEn+n07twICYPcfcwhtwbijEs/x/UO1e8iv+voWsI/jLBN1PKS9dqWwOKPGSFE8CnDkotQAa9tWgW9IXKW5ouoW8YiaHdsGkPIir/AM2G576Muouda1jCK0kucCVNCQw+AzTeL2FV8K97ix+i+9me6zVmhFcFxosGvsb9Wkxy2BEfWzK7GjLbrQtXcqbec/rvLjbNdeyULYDllfYW8XfqoEjkwuA68JdxhXSNOJJObJoUAY0jDHDClDfEyoDiSmj3kag8YZ6ktGmRZPIAqZUxh8nZBMJqBAXKEYnRx9Do1cKKsxIjHdJj0qZWGU1wcom+b2jNfU91wxizzUviH/yoWJSOAYAAA==).

Unfortunately it's showing another error now - `process is not defined`.

This seems like a bug in reactivue to me, in that it is assuming the `process` global exists in an ES module, when it does not exist in the browser - see https://unpkg.com/reactivue@0.3.4/preact/index.esm.js. I'd suggest posting an issue to reactivue here as JSPM will not be supporting rewriting process in the name of ensuring we can move towards browser compat ESM - we shouldn't be shimming Node.js things.

The better pattern to use in ESM for production / development splits is the `"production"` and `"development"` exports conditions (https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_conditions_definitions).

If you're able to post an issue back to reactivue that would be great, let me know if I can help further too.

**Comment by sibbng** [comment]
Hi, thanks for quick fixing the issue. First of all I'm the maintainer of reactivue. But there is things you missing.

- Using wrong version
For some reason import map generator doesn't pick latest version. There is 0.4.1 available.
I added a `browser` field to export map in https://github.com/antfu/reactivue/pull/32 to bypass that issue.
Maybe I could misconfigred [our export map]. I would like to hear your comments about it. (https://github.com/antfu/reactivue/blob/master/packages/reactivue/package.json).

I manually edited import map to map `reactivue` to `index.module.js` and it works as expected now. 

[Working sandbox](https://jspm.org/sandbox#H4sIAAAAAAAAA41Wf0/jOBD9v59iNodW7dEmLbsn8SPpURXEwm1X3JZy2j2dREhcYkjsXOxQSpXvfhPbCWnLsicBie2ZN8/Pb0zcdyEP5DIlEMkkHrbc6kH8cNgCcBMifQgiPxNEelYu5719Sy1IKmMynDH1DF1Hj+sU5ifEsx4pWaQ8kxYEnEnCEGJBQxl5IXmkAempQRcoo5L6cU8Efky8ARZwHc3AveXhUqG+6/XgdAoTHuYxgWlEE3EI50mJDomfCkh5vJzTOIY5zyBRYQJuM74QJBOwoDLiuQTayBB5qgZtH7PIU0BSCeMo4wmB/YPdDvR6qrIIMoorvliyAEQWeFYkZSoOHefOt+9FmtiUOyxNDono6bo9UdI77tsD/HFCKqSzsWYnlGGuNXQdDV9WMtvEB8DF9HICZ4SRzJe4H7PRiZ+q1dOQSph9/XwINZUqtGb0y2zv+u7b2Ul0st/PltPni+lsEC3H9xfh1clfk4PR87fpHZ8+DCaf2eniy5fR8+Bq0v+aX/77ffeKfX8Knu8ms+Wyn159+vO5f395PTkYn/0xOh89LMTT1WiEPNb1KV3kWVpflFe5ZKXYmklhHZoJnEKf4fBHSuLq8Qe7b3/U4uGwFKtbJacZ8QP5Rr4OOEb5f7MHHzSInrP1KbwC50ScP4j/D6rCDb/y9TVklUEfc+L8lHIdirb5iK4xpCgLyVMDWiEXuoAlAp6SDVm3wBvLGHBckjG1qFy+QWgjUp3HgYONa2tOjX1WuALvCRL+DFNHvYZn4IpW9bf83eyQNbtpYZTXoOrtFeCVkhEEzaCAOfZz7Zij9bhckKn0JdkIM05YC0YLmpjSues4hnZI5pSRMcdZhlddJU5G5tVrgGu5JGE15mzCc7Y2MWNJc6oitmWkkkGrpUGZUPxi8MqHfYt6tqPOUXN5shwr2AxjNni2TW3HAbzj8xTmOcNanOG1DNc5McvtNOOp6IA3bNhJgwc1NO5Vx9mPfpyTztFGZMjzW/xvgZGVFO22gjQQOg1+hb2tVIqXrwc6ur0evuvBoNrumqw1OBMc2yfmd22r0sHIbHUalRryv5Was2ZynZ2hehlDWxl23Wq7XUW+qOoU3RfFK639WCmiDqTUXZ9yJf0PITeOAwGXPIfAZ6W1DQgoN0NEMrJJtTTNTT2JvRXSx2FjbGZ2VqZ8AU+wh6ewszI0CtfZTrnNpUT3cDaOafDg7ayQajE8ZwHSEcR19HozaQPlplZKPSuNa1+O0hRPZ1U3VWmPv0XEF93SwVN8+QdJVs3dlplyYt2Or2x9m7M+fgPXfleid4om551VOQe/g/WJhsQCvPTKUKuozuoFfGvHJvf9e03D3VnV/VmA8jQyGPQLcIY3hcm6MZdiS2+ivN3aVTYKUmBo6Y4gT9BCdvnZpIz9cnsiDfUt5Tr6G+8/8EnHQPsJAAA=)

**Comment by guybedford** [comment]
@sibbng you need to put the `"browser"` entry first, because the exports conditions match _in object order_.

The 0.4.1 is coming through now, there's just a slight delay for JSPM to process new versions that are released, usually around 20 minutes.

**Comment by sibbng** [comment]
> @sibbng you need to put the `"browser"` entry first, because the exports conditions match _in object order_.

Hi, I updated `reactivue` based on your comment. Now import map generator picks right export. Thanks for your help and quick fix 🤗
