### ISSUE TITLE
CDN is not available to all regions

### ISSUE THREAD

**Issue by psamim** [jspm/project#101]
Hi,

It seems that the CDN is not available in countries where Google Cloud is not available. Google Cloud sends 403 to the countries sanctioned by U.S. including Iran, Syria and some others, and even sometimes to suspicious VPN IPs. I know that this may be out of hands of JSPM project, but availability in all countries is also an important factor in CDNs. I am almost sure this is a side effect of using Google Cloud and actually serving content to these countries will not violate international laws.

Thanks

**Comment by guybedford** [comment]
@psamim thank you for posting this, I wasn't aware. Do you know if this is the same for other CDN providers like CloudFlare, Fastly etc?

**Comment by psamim** [comment]
@guybedford 

As far as I know Google is the only major cloud provider doing this, AWS, Azure and others do not block traffic at this level. 

I tested personally and jsdelivr.com and cdnjs.com are both available in all regions.

**Comment by psamim** [comment]
My tests on a VPS in Iran:

### JSPM:
```
$ wget https://ga.system.jspm.io/npm:@sentry/browser@6.3.1/dist/index.js
--2021-04-29 10:23:49--  https://ga.system.jspm.io/npm:@sentry/browser@6.3.1/dist/index.js
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving ga.system.jspm.io (ga.system.jspm.io)... 35.244.221.95
Connecting to ga.system.jspm.io (ga.system.jspm.io)|35.244.221.95|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-29 10:23:55 ERROR 403: Forbidden.
```

### JSDELIVR

```
$ wget https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
--2021-04-29 10:18:44--  https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 104.16.88.20, 104.16.86.20, 104.16.87.20, ...
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|104.16.88.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/javascript]
Saving to: ‘jquery.min.js.1’

jquery.min.js.1                                      [ <=>               ]  84.63K   555KB/s    in 0.2s

2021-04-29 10:18:50 (555 KB/s) - ‘jquery.min.js.1’ saved [86659]
```

### CDNJS

```
$ wget https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
--2021-04-29 10:51:26--  https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving cdnjs.cloudflare.com (cdnjs.cloudflare.com)... 104.16.19.94, 104.16.18.94, 2606:4700::6810:135e, ...
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.16.19.94|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/javascript]
Saving to: ‘jquery.min.js.2’

jquery.min.js.2                                         [    <=>         ]  87.40K  72.7KB/s    in 1.2s

2021-04-29 10:51:35 (72.7 KB/s) - ‘jquery.min.js.2’ saved [89501]

```

**Comment by guybedford** [comment]
I am planning an update in the next month or so to move to CloudFront for the main CDN. Thank you again for this information to help inform this decision. Will leave this open until that happens.

**Comment by guybedford** [comment]
The CDN has now been migrated over to CloudFront. This should have resolved this issue but please let me know if there are any other concerns here.

**Comment by psamim** [comment]
Thanks but I am still getting the same result. 

For example when the link https://ga.system.jspm.io/npm:@sentry/browser@6.3.1/dist/index.js is opened in Iran using a browser, I see 403 error with Google logo.
