### ISSUE TITLE
Undefined variable in served @wasmer/wasmfs

### ISSUE THREAD

**Issue by michaelfranzl** [jspm/project#102]
https://generator.jspm.io/#02JgYGBkDM0rySzJSU1hcChPLM5NLdIHUWnFDgZ6hkZ6BgBipuf3JAA

Gives `Uncaught ReferenceError: _process is not defined sandbox:1:55467`.

I don't see this issue when locally using jspm cli version 2.0.0-beta.7 .

**Comment by guybedford** [comment]
Thanks for posting the issue, if you clear your browser cache it should be working correctly now.

**Comment by michaelfranzl** [comment]
Confirming that it is working!

I'm interested though what the problem was.

Thanks!

**Comment by guybedford** [comment]
@michaelfranzl this was due to the handling of the `process.nextTick` replacement for browsers in the CommonJS conversion not working correctly.
