### ISSUE TITLE
fp-ts 2.10.5 missing from cdn

### ISSUE THREAD

**Issue by jollytoad** [jspm/project#104]
https://ga.jspm.io/npm:fp-ts@2.10.5/package.json appears to be not found!

exists on unpkg: https://unpkg.com/browse/fp-ts@2.10.5/package.json

**Comment by guybedford** [comment]
Thanks for posting - it should be there now. This was actually a build bug that was causing the issue. Usually we recover from build bugs and have the errors in the output but this one was an actual internal syntax error in the intermediate build which was why there wasn't any output.
