### ISSUE TITLE
Imports i've had to post-process

### ISSUE THREAD

**Issue by jollytoad** [jspm/project#106]
These are the rewrites i've had to do so far after the import-map generation:

**NOTE: Some of these are broken, i'm fixing them as I find them, not all are loaded at the start of the app, and i've not got the app fully starting yet**

module | generated url | rewritten url
-|-|-
@isomorphic-git/lightning-fs | https://ga.jspm.io/npm:@isomorphic-git/lightning-fs@4.3.0/src/index.js | https://cdn.skypack.dev/@isomorphic-git/lightning-fs@4.3.0/dist/lightning-fs.min.js
@monaco-editor/loader | https://ga.jspm.io/npm:@monaco-editor/loader@1.0.1/lib/cjs/index.js | https://cdn.skypack.dev/@monaco-editor/loader@1.0.1/lib/es/index.js
idb | https://ga.jspm.io/npm:idb@5.0.8/build/cjs/index.js | https://cdn.skypack.dev/idb@5.0.8/build/esm/index.js
isomorphic-git | https://ga.jspm.io/npm:isomorphic-git@1.8.2/index.cjs | https://cdn.skypack.dev/isomorphic-git@1.8.2/index.js
isomorphic-git/http/web | https://ga.jspm.io/npm:isomorphic-git@1.8.2/http/web/index.cjs | https://cdn.skypack.dev/isomorphic-git@1.8.2/http/web/index.js
launchdarkly-js-client-sdk | https://ga.jspm.io/npm:launchdarkly-js-client-sdk@2.19.1/dist/ldclient.cjs.js | https://cdn.skypack.dev/launchdarkly-js-client-sdk@2.19.1/dist/ldclient.es.js
react-draggable | https://ga.jspm.io/npm:react-draggable@4.4.3/build/cjs/cjs.js | https://cdn.skypack.dev/react-draggable@4.4.3/build/cjs/cjs.js
use-resize-observer | https://ga.jspm.io/npm:use-resize-observer@6.1.0/dist/bundle.cjs.js | https://cdn.skypack.dev/use-resize-observer@6.1.0/dist/bundle.esm.js
**scope: https://ga.jspm.io/**
@isomorphic-git/idb-keyval | https://ga.jspm.io/npm:@isomorphic-git/idb-keyval@3.3.2/dist/idb-keyval-cjs.js | https://cdn.skypack.dev/@isomorphic-git/idb-keyval@3.3.2/dist/idb-keyval.mjs
css-vendor | https://ga.jspm.io/npm:css-vendor@2.0.8/dist/css-vendor.cjs.js | https://cdn.skypack.dev/css-vendor@2.0.8/dist/css-vendor.js
dom-helpers/addClass | https://ga.jspm.io/npm:dom-helpers@5.2.0/cjs/addClass.js | https://cdn.skypack.dev/dom-helpers@5.2.0/esm/addClass.js
dom-helpers/removeClass | https://ga.jspm.io/npm:dom-helpers@5.2.0/cjs/removeClass.js | https://cdn.skypack.dev/dom-helpers@5.2.0/esm/removeClass.js
hoist-non-react-statics | https://ga.jspm.io/npm:hoist-non-react-statics@3.3.2/dist/hoist-non-react-statics.cjs.js | https://cdn.skypack.dev/hoist-non-react-statics@3.3.2/dist/hoist-non-react-statics.cjs.js
hyphenate-style-name | https://ga.jspm.io/npm:hyphenate-style-name@1.0.4/index.cjs.js | https://cdn.skypack.dev/hyphenate-style-name@1.0.4/index.js
jss | https://ga.jspm.io/npm:jss@10.6.0/dist/dev.jss.cjs.js | https://cdn.skypack.dev/jss@10.6.0/dist/jss.esm.js
jss-plugin-camel-case | https://ga.jspm.io/npm:jss-plugin-camel-case@10.6.0/dist/jss-plugin-camel-case.cjs.js | https://cdn.skypack.dev/jss-plugin-camel-case@10.6.0/dist/jss-plugin-camel-case.esm.js
jss-plugin-default-unit | https://ga.jspm.io/npm:jss-plugin-default-unit@10.6.0/dist/jss-plugin-default-unit.cjs.js | https://cdn.skypack.dev/jss-plugin-default-unit@10.6.0/dist/jss-plugin-default-unit.esm.js
jss-plugin-global | https://ga.jspm.io/npm:jss-plugin-global@10.6.0/dist/jss-plugin-global.cjs.js | https://cdn.skypack.dev/jss-plugin-global@10.6.0/dist/jss-plugin-global.esm.js
jss-plugin-nested | https://ga.jspm.io/npm:jss-plugin-nested@10.6.0/dist/dev.jss-plugin-nested.cjs.js | https://cdn.skypack.dev/jss-plugin-nested@10.6.0/dist/jss-plugin-nested.esm.js
jss-plugin-props-sort | https://ga.jspm.io/npm:jss-plugin-props-sort@10.6.0/dist/jss-plugin-props-sort.cjs.js | https://cdn.skypack.dev/jss-plugin-props-sort@10.6.0/dist/jss-plugin-props-sort.esm.js
jss-plugin-rule-value-function | https://ga.jspm.io/npm:jss-plugin-rule-value-function@10.6.0/dist/dev.jss-plugin-rule-value-function.cjs.js | https://cdn.skypack.dev/jss-plugin-rule-value-function@10.6.0/dist/jss-plugin-rule-value-function.esm.js
jss-plugin-vendor-prefixer | https://ga.jspm.io/npm:jss-plugin-vendor-prefixer@10.6.0/dist/jss-plugin-vendor-prefixer.cjs.js | https://cdn.skypack.dev/jss-plugin-vendor-prefixer@10.6.0/dist/jss-plugin-vendor-prefixer.esm.js
react | https://ga.jspm.io/npm:react@16.14.0/dev.index.js | null
react-dom | https://ga.jspm.io/npm:react-dom@16.14.0/dev.index.js | null
react-onclickoutside | https://ga.jspm.io/npm:react-onclickoutside@6.10.0/dist/react-onclickoutside.cjs.js | https://cdn.skypack.dev/react-onclickoutside@6.10.0/dist/react-onclickoutside.cjs.js
react-popper | https://ga.jspm.io/npm:react-popper@1.3.11/lib/cjs/dev.index.js | https://cdn.skypack.dev/react-popper@1.3.11/lib/esm/index.js
react-transition-group | https://ga.jspm.io/npm:react-transition-group@4.4.1/cjs/dev.index.js | https://ga.jspm.io/npm:react-transition-group@4.4.1/cjs/index.js
state-local | https://ga.jspm.io/npm:state-local@1.0.7/lib/cjs/state-local.js | https://cdn.skypack.dev/state-local@1.0.7/lib/es/state-local.js
tiny-warning | https://ga.jspm.io/npm:tiny-warning@1.0.3/dist/dev.tiny-warning.cjs.js | https://ga.jspm.io/npm:tiny-warning@1.0.3/dist/tiny-warning.cjs.js

i have a script to apply these to the import-map, so it's repeatable, ~~and some are just a wholesale cjs -> esm rename.~~

**Comment by jollytoad** [comment]
here are my rules...

```typescript
import { flow } from 'fp-ts/function'

const replace = (a: string, b: string) => (url: string) => url.replace(a, b)
const skypack = () => replace('https://ga.jspm.io/npm:', 'https://cdn.skypack.dev/')
const esm = () => replace('cjs', 'esm')
const es = () => replace('cjs', 'es')
const noDev = () => replace('dev.', '')
const noCjs = () => replace('.cjs.js', '.js')
const skypackEsm = () => flow(skypack(), esm(), noDev())
const react17only = () => (url: string) => !url.includes('17') ? null : url

const overrideImports: Record<string, string | ((url: string) => string | null)> = {
    "idb": skypackEsm(),
    "launchdarkly-js-client-sdk": flow(skypack(), es()),
    "react-popper": skypackEsm(),
    "jss": skypackEsm(),
    "jss-plugin-camel-case": skypackEsm(),
    "jss-plugin-default-unit": skypackEsm(),
    "jss-plugin-global": skypackEsm(),
    "jss-plugin-nested": skypackEsm(),
    "jss-plugin-props-sort": skypackEsm(),
    "jss-plugin-rule-value-function": skypackEsm(),
    "jss-plugin-vendor-prefixer": skypackEsm(),
    "react-draggable": skypack(),
    "react-onclickoutside": skypack(),
    "hoist-non-react-statics": skypack(),
    "dom-helpers/addClass": skypackEsm(),
    "dom-helpers/removeClass": skypackEsm(),
    "react-transition-group": noDev(),
    "react": react17only(),
    "react-dom": react17only(),
    // "tiny-warning": noDev(),
    // "hyphenate-style-name": flow(skypack(), noCjs()),
    "css-vendor": flow(skypack(), noCjs()),
    "use-resize-observer": flow(skypack(), noCjs())
}
```

and the fns that modify the import map:

```typescript
const fixImportMap = (importMap: ImportMap): void => {
    fixImports(importMap.imports)

    Object.values(importMap.scopes).forEach(imports => {
        fixImports(imports)
    })
}

const fixImports = (imports: Record<string, string | null> = {}): void => {
    Object.entries(imports).forEach(([moduleId, url]) => {
        if (url) {
            const altUrl = fixImport(moduleId, url)
            if (altUrl === null) {
                delete imports[moduleId]
            } else if (typeof altUrl === 'string') {
                imports[moduleId] = altUrl
            } else if (typeof altUrl === 'object') {
                delete imports[moduleId]
                Object.assign(imports, altUrl)
            }
        }
    })
}

const fixImport = (moduleId: string, url: string): string | undefined | null | Record<string, string> => {
    if (/^@babel\/runtime\/helpers(\/esm)?\/(.+)$/.test(moduleId)) {
        const moduleIdWithoutEsm = moduleId.replace('/esm/', '/')
        const moduleIdWithEsm = moduleIdWithoutEsm.replace('/helpers/', '/helpers/esm/')
        const urlWithEsm = url.replace('/esm/', '/').replace('/helpers/', '/helpers/esm/')
        return {
            [moduleIdWithEsm]: urlWithEsm,
            [moduleIdWithoutEsm]: urlWithEsm
        }
    }
    const override = overrideImports[moduleId]
    let overrideUrl = undefined
    if (override) {
        overrideUrl = typeof override === 'string' ? override : override(url)
    } else if (url.includes('cjs')) {
        overrideUrl = url.replace(/cjs/g, 'esm')
    }

    if (overrideUrl) {
        console.log(`${moduleId} | ${url} | ${overrideUrl}`)
    }

    return overrideUrl
}
```

**Comment by guybedford** [comment]
I've just tested out the non-scoped packages listed on the online generator and can see all of them importing via the sandbox here:

https://jspm.org/sandbox#H4sIAAAAAAAAA7VYbVPbOBD+3l+h5r7AXG3HIeXtAhNKKS/HWwiUtl9uZFlJRGTLWHJy4ab//VayHZLUaZTe3HQoeL37PLvSerXa1ttQEDVJKBqoiB++aZW/KA4P3yDUiqjCiAxwKqk6qGWq5+zWzAvFFKeHD7H5Hba8/HlqEuOIHtRGjI4TkaoaIiJWNAaIMQvV4CCkI0aoYx7eIRYzxTB3JMGcHvhA0PJyD1qBCCcG9a3joO5EKhpddPdRN0s0rkRc4JDFfRSJMONUooSmPZFGOFZ8ArgIc46CVIwlTSUKMBkiJdD5ie+jjZAmNDbGIkacBSlOJ0jmwJvIcQytJClLFJIpOagNlErkvuf1sSuNJ+6TTCKXCS9Oov1c9CTb2+6uu+WFTCpPuhGLQat22PJyJA1ahvMQExFFsCrTwNAHHFBwmHIxRhAHwjEE4RQBoJMuujJxIg/dw6Z1c+c8dNH9gmBJ0Vikwx7YuqX7muYXYnAC7Ue77m65fhHJ3Jv5kAqygg9+IXDo9gqd0pimWEEY55FeVHSFE/P2JGQKPdxd7qOpO6Xq1J3fAsIvP4rz8cnRx07jS4RPu/3++HN9NO6cbUcPx/woGd6cKr8ZPt6yeubv3HaOyVZ289y9vz7rXp8FV3sP9c5xGgTfrvfu+6dxch10Old+Lz0NPo++PI8Hv09ursnL3eTbnz16XP9KsovPktx/uo462beTj18/kAcRJM/kpTHe2X5+2sP07Krz6F8OItE8fr4ed7ve6csdfbxpjtTIu/rQvQ344+XREUQ4nzv68zqoTReQmbWIcGK+o3/MgtRyoaztFwItCgN4XLFhoNR+79bdXS/IGA898iQ9Fof0b71D76ZQUkQiTQaMOH2mLFDn9Ns+JHSjgCXLcT0N6o2pjdtVBKV5FRPHWUwGIU6HfOLAIhLO4LtxZDhcTbbctt1w/b0yw3mYv9DEc6uXUkyUE6a438cBp6sJFwzaTbcJBeF1g6oJJOWUWGzOrHYbvk+3nvs/K3eLivFDLJmkTkole6GOCEBhRNPVjBVGUOSmxEEWh5yWVIbpe05Yk0QkdC6rlzPNaIFe29QZL83ggIkonAYcKrvO7QFNmZKXQkiLnZhHae+4fhO8rgSbXSbNTyOhmIg9gsnAhmlOv+3X4aNs7OULZETLtmSOS6RrUYG6ZvLLFNYCKx4p16GRsohnp6CR0oZlgOVgDRqtDifObplW+tmGJoI/IDXXYCosgGzHbeZkhciGD15Dr7Ie49QGOH3Yru3iUC3FVrwDSi3Kw7w+8O2VMRqBFZOacLZOhuQGZvPeF1xGYkOWxbpxXCshSxOzgQVhKbOiVIyvxaf1850r+jojsaEaUzx01s/QWTMgbpRRzsp/Qo/lJCYOF8TidHzVhWO4AY3ED+0DAAZZr2dzUrT1Q16XGlAw6k4AdwF3x4tFSKHDll4OtIBOOJZSXxgsNuVVFxh0d1rlLuEUx7qzgGOrZ4M5o24c9z3wtho6Jc5WwwLT6JklrXvwsNVYAApZr7e1GseotXX11akHfy/AsH5sdWjketAr+ku2uDwMLaAKTbNSzekp+leZj/O4RbY6IrbwckYZXG2U59qMuCLbRfAELY8DeQFBruaYU4fezF+SRAkeitVoWgt2WReHahTWm1iggBa4Ul/mSiqIXYlc9f0VSD/iJ46+plhQvOq2/fdQfxuVHptm1LKXbfvbeV+2FMgJRWTddovIApDFSQY5kCkhrSpzlRUsMfwzleKoEJ1rhQVCiXvUsS2gM8rFB1AVg4R+Uo8BbABLVX1+7S3DG2CQQIOAff1mNajRh/ibOu1LswLv+/Sy8Qtt7PwlYL0s2tEt6mt8a7qz/JLzP/j0pvxf/1SNhj6JFCkqFYv7+/PjhENjmw+M3HxssGFmBZuuGtB4I0IHh3raJgXcybjob0Sbm39U2swPBf6b+evdf12cn9zs14VavKj/mn1xD1/XuOpmvQKjauMvBQ711A8nCSQM6jFO0RiOV0X1JBABHipGSbVi5onMvFMhkSkoPmhjxDC6E5xnyUUXecVEcXZeuFk1HFwYUuXQtXxmmPuyOPBreflstuXlM+N/AXIzBcpLFgAA

`@emotion/cache` working fine for me at https://jspm.org/sandbox#H4sIAAAAAAAAA51VXW/aMBR976+4zV5AIg6069SygKArq4qabm1A2h5NYojBX4pNEUz773OcgABRbd0DWL72vefcD5+E56lMzFoRyAxn3bNwuxCcds8AQk4MhiTDuSam4y3N1L/23IGhhpHuWLg1DYNyv3MRmJOO90rJSsnceJBIYYiwIVY0NVknJa80Ib7bNIAKaihmvk4wI52WBQiDkkE4kenaRT33fYjX2hA+jNsQL1URVwOTOKViBlymS0Y0KJJPZc6xMGxt4wJmDCa5XGmSa5jgZAFGwsOg1YJaShQRzlkKYHSS43wNugxcB993sDrJqTKg86TjZcYo3Q6CGUbaMUFzrTiiMhCKt0vTXPc+oWt0GaRUm0AjToW95XXDoIxUBN2mMxaJ5NxWZZcY3OIJsYQJkyuweQAWNgm/SgAGMUQuTwhgZJsWl+QCGMY/wJYUVjJfTK0v2tIvYP4jB39S8Og10SVqVZkcnBymVIFVeHYBS+h7BPdEkBwbm8YDL4oKEVbudJBSA+OXxzbs6Gyv7uh8iC6eZj/vbxd3UTNfx5thPG5lyWD+tImD4SYKRqPmVbRZZK3obvQc3fQ3evbc79Nv2ejLuG9RDvtXjHjH2yVBHR+OlZvlX46UVxq1164M1tQjXBoqRZDgJCP25C/1O7zfazVRE13clBV0JlS1EiVzXRTRAf1ulAR0IhU5wH8bbe/WPk+dEWLewdPdt32+QR+rPheGY5aNU0hmzah+D5RzsFjX6KrCcpZ/AVsRvPC53dHNe7qw72aBL7bA+/aTHbE9Odv+F79Tr/ernWtDtLEC0j6ctq7zLd80KqeqdjxKdWQyImocOt1CG7VkBDE5q/F6/fMbgI9W6gpBwEpZojClVgdWOTVWVwuls/GgmnCvkkNwUmhALo1aGqi9UgwvkrGlslITVGKzLyX1U7px9HbK0F4pJyWXYy0Ig1K2rYq7z8kf5sSl+mYGAAA= as well.

Perhaps you can share an exact replication / break further in these scenarios?

For your `"dev"` -> not dev renames, did you pass `env: ['browser', 'production']` to the generator API call? That should avoid the need for this.

Let me know how I can help further.

**Comment by jollytoad** [comment]
Yeah, but they load the cjs modules rather than esm.

**Comment by guybedford** [comment]
@jollytoad this gets back to the dual package hazard issues, where we want to ensure to avoid issues between versions. Is there a reason the CJS file doesn't work for you?

**Comment by guybedford** [comment]
Note also that upstreaming an "exports" override / "exports" PR is the ideal way to fix this stuff up as the "module" field is a legacy field that isn't guaranteed to provide correct semantics.

**Comment by guybedford** [comment]
I've gone ahead and added a treatment of the "module" field for the top packages here. So that when using the `"module"` exports condition, the ES module versions should resolve now.

I haven't cleared the cache for the scoped package variations yet though.

**Comment by jollytoad** [comment]
I've update my build, excluding some stuff that wasn't even meant to be built, (emotion packages were a red-herring, they aren't even used in our app). I've updated the rules to explicitly cover each individual case now, and removed the wholesale cjs -> esm replacement.

**Comment by guybedford** [comment]
I've refreshed module builds for all of the above now down to the react case.

As far as I can tell the react case is one of bad version deduping? Will the install list you provided replicate this?

**Comment by jollytoad** [comment]
Yes it should do.

**Comment by jollytoad** [comment]
So, most of these are working now, thanks @guybedford ... the override list is now down to...

```typescript
    '@isomorphic-git/lightning-fs': flow(skypack(), replace('src/index.js', 'dist/lightning-fs.min.js')),
    '@isomorphic-git/idb-keyval': flow(skypack(), replace('-cjs.js', '.mjs')),
    'react-popper': skypackEsm(),
    'react': react17only(),
    'react-dom': react17only(),
```

The isomorphic-git stuff will need fixes upstream (i'll get onto that at somepoint), react/react-dom could be dealt with by a resolutions style solution as we discussed. react-popper is an odd one, although the esm module is present in jspm now and resolves correctly, I get some runtime bugs ... i think it maybe a transient dep ... i'll have to investigate further on that one.

**Comment by jollytoad** [comment]
Just discovered another problematic package:

https://ga.jspm.io/npm:react-datepicker@3.8.0/package.json

maps by default to: `dist/react-datepicker.min.js`, but should be: `dist/es/index.js` (as set in it's `module` prop)

**Comment by jollytoad** [comment]
react-timeago also, `lib/index.js` -> `es6/index.js`

**Comment by guybedford** [comment]
With respect to the react deduping issue, https://unpkg.com/react-timeago@4.4.0/package.json in react-timeago clearly depends only on React 16. This is the reason for the version issue. I'm going to track this in a new issue at https://github.com/jspm/generator/issues/13 and not rush implementation to be sure this is implemented well. I believe that resolves all the questions posted here but please reopen / post a new issue if I've missed anything. Thanks again for the very useful reports.
