### ISSUE TITLE
JSPM Package Guidelines & Patterns

### ISSUE THREAD

**Issue by guybedford** [jspm/project#110]
Tracking issue for either a package author guidelines page on the website, or more general information information / blog post about universal package patterns including:

* `import.meta.url` patterns
* Conditional importing patterns (TLA / exports / imports)
* What not to do (importing packages that aren't available on all platforms / process / Buffer access etc?)

Contextualisation and full list of workflows / patterns / dos / donts to be fleshed out further.

**Comment by JayaKrishnaNamburu** [comment]
- Exposing style sheets and json modules from a package
- Missing `dependencies` / `peerDependencies`. (Confusion between defining a dependent module in `dev` / `peer` Eg (https://unpkg.com/browse/rc-util@5.4.0/package.json).
- `module` field under `exports` in package.json
- Transpile / Bundle for authors. (Like, package clients installs dependencies defined inside `package.json`. So, for authors just transpiling should be good enough).
- `type` vs `module` field under `pacakge.json`. Not to get confused with `module` under `exports` map.

**Comment by guybedford** [comment]
This turned into a todo that never went anywhere, closing.
