### ISSUE TITLE
aurelia@2.0.0-alpha.10 fails in generator 

### ISSUE THREAD

**Issue by timfish** [jspm/project#112]
![image](https://user-images.githubusercontent.com/1150298/124582110-9e9cff00-de49-11eb-924e-377f77808117.png)

When I mouse over "Add package export" I get the busy cursor. 

Aurelia is built with native modules output:
https://unpkg.com/aurelia@2.0.0-alpha.10/dist/native-modules/index.js

I can see some 404 errors in the console about `package.json` but it's not immediately clear what sort of PR I could do to fix things at the source.

**Comment by timfish** [comment]
This dev version works but I can't see what is different and would cause this:
https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hSCwtSs3JTHQw0jPUM9BNSS3TMzIwMjQwNzA2MDA1AQCDr047LQA

**Comment by guybedford** [comment]
@timfish there is a slight delay for new packages on the CDN due to the npm publish stream having a delay, this is usually a few hours. Support for triggers will be added in future, but for now I've triggered a manual build - it should be working now.

**Comment by timfish** [comment]
Thanks @guybedford!

**Comment by timfish** [comment]
Are comments kept simply to preserve any licence text?
eg. https://ga.jspm.io/npm:@aurelia/kernel@2.0.0-alpha.10/dist/esm/index.js

I suppose the next step would be to ship Aurelia with `exports` in `package.json` with `development` and `production` to get the minified output really small.

**Comment by guybedford** [comment]
Those comments are kept because of the JSDoc typings specifically. We retain JSdoc and license comments.

Yes development / production branches are recommended. You can use nested exports conditions to achieve this for ESM + CJS variants.
