### ISSUE TITLE
Can't import react-admin

### ISSUE THREAD

**Issue by NewName** [jspm/project#113]
Importing the `react-admin` package, 

`import reactAdmin from 'https://jspm.dev/react-admin';`,

gives a number of errors due to the `@material-ui/icons@4` package, as `react-admin` seems to directly import various files in this package, eg one is resolved to `https://jspm.dev/npm:@material-ui/icons@4/RemoveRedEye!cjs`.

The main error is that  these files seem to be served with the `application/octet-stream` encoding, but reading the encoding shows that it's actually a 404. 

These files do seem to be accessible, but can only be found by changing the package version either to the full version number, eg `https://jspm.dev/npm:@material-ui/icons@4.11.2/RemoveRedEye!cjs`, or removing it altogether, eg `https://jspm.dev/npm:@material-ui/icons/RemoveRedEye!cjs`.

Example below:
https://jspm.org/sandbox#H4sIAAAAAAAAAz2QS04EIRBA93OKks1sbIk7o9CJCy/gDRBq0mUoIFDzu/00EF0RUsV7L5inkL3cC8ImHNeD+TvQhfUAYBjFgd9cbShWneW0vKkxEJKI6zc6L/AZmBJ83RyXiEbP0f/r5BituhBeS66iwOckmHbalYJsNuCFPC7j8gyUSMjFpXkX0b7uLqNnjPnJ4d6pHdx8pSLQy63iHM4RRxYAcbdA7WGz61Qzw3ETKe1d699W+GV36rGxuL5y/OhMPaHdOFW7efzGA9QBbuolAQAA

In addition, the `react-admin` package seems to fail in the generator:
https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hKEpNTC7RTUzJzcxzMNYzNNczAAC3zRQFIQA

**Comment by guybedford** [comment]
Thanks for posting. This is a bug in the serving process, I'm looking into it.

**Comment by guybedford** [comment]
To update I'm still looking into this - the package is just so big it literally takes 10 minutes to process so debugging is slow.

**Comment by guybedford** [comment]
The generator fix has been merged at https://github.com/jspm/overrides/pull/7, this should get the import map version working once the build completes shortly.

The jspm.dev issue is a file limit issue because there are 22000 files. I'm looking into the exact bottleneck.

**Comment by guybedford** [comment]
`import('https://jspm.dev/react-admin').then(x => console.log(x))` is now working.

The version in JSPM generator is still pending some override fixes which I'm still looking into.

**Comment by guybedford** [comment]
The generator version is now working as well. Thanks again for posting.
