### ISSUE TITLE
How to bundle an importmap?

### ISSUE THREAD

**Issue by mustafa0x** [jspm/project#114]
I want to use `rasterizehtml` in an application bundled by rollup, but it has node dependencies. JSPM's importmap provides the deps, but I don't know how to feed that importmap to rollup so that I get everything contained in one bundle.

Thank you; exceedingly helpful tool!

**Comment by guybedford** [comment]
The goal is to have a RollupJS plugin for JSPM to support this. There is an older version of this plugin but it needs updating. Are you interested in contributing? It's on my list!

**Comment by mustafa0x** [comment]
Thanks for the reply! I'll take a look but I'm not too familiar with the internals of rollup. :)

**Comment by guybedford** [comment]
The plugin at https://github.com/jspm/rollup-plugin-jspm now handles this use case! It is yet to be released properly, but works when cloned. Will close this issue as resolved, pending that release.

**Comment by mustafa0x** [comment]
Woah, impressive, thanks!
