### ISSUE TITLE
Get TypeScript working (finally)

### ISSUE THREAD

**Issue by guybedford** [jspm/project#119]
The time has come to finally sort this one out...

**Comment by jaydenseric** [comment]
Related earlier issue, specifically about TypeScript support for Deno: https://github.com/jspm/project/issues/55 .

**Comment by fusionstrings** [comment]
I wish to like this 10000+ times ❤️

**Comment by guybedford** [comment]
This finally happened in https://github.com/jspm/project/issues/249. Code example there. Issues welcome!
