### ISSUE TITLE
JSPM Core Discussion: 12 August 2021

### ISSUE THREAD

**Issue by guybedford** [jspm/project#120]
### Proposed Agenda

- Development update
- JSPM Foundation First Members Meeting

### Meeting Details

Time: 8am PST Thursday 12 August 2021 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20210812T1500)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by jollytoad** [comment]
Hi Guy, i'm free again to attend this week. I'd like to have a quick chat about how to proceed with getting MUI 5 (and other projects in general) up to spec (exports-wise) if we have time during the meeting.

**Comment by guybedford** [comment]
@jollytoad as discussed in the meeting, would you like to post an issue to track the MUI 5 work specifics further here?
