### ISSUE TITLE
semantic-ui-react TypeError: a is not a function

### ISSUE THREAD

**Issue by Jarreddebeer** [jspm/project#125]
(generator command at the bottom)

When I import from 'semantic-ui-react' from a bare-bones app it throws:

```
Uncaught (in promise) TypeError: a is not a function
    at _interopRequireWildcard (interopRequireWildcard.js? [sm]:22)```

It appears to be from `@babel/runtime@7.15.3/helpers/interopRequireWildcard.js` line 22, which is:

```js
if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") {
```
Vaguely to me `_typeof`, `_typeof2` and `_typeof3` appear to be undefined, specifically:

```js
import * as _typeof3 from "@babel/runtime/helpers/typeof";

var _typeof2 = "default" in _typeof3 ? _typeof3.default : _typeof3;

var exports = {};
var _typeof = _typeof2["default"];
```

Where `@babel/runtime/helpers/typeof` is from: https://ga.system.jspm.io/npm:@babel/runtime@7.15.3/helpers/esm/typeof.js

I don't have the intuition to debug further. The import-map was created using the generator, and i'm able to get a fairly sized react based app running, just, if I import from semantic-ui-react this error is thrown.

I'd used the [web based generator](https://generator.jspm.io/#M2VgYGBkDM0rySzJSU1hKE7NTQSyk3VLM3WLUhOTSxyM9Az0jAGlQ9k6JgA) and had the same experience with the cli generator (I don't have exact generator file on me at present) but only `generator.install('semantic-ui-react')` was necessary.

**Comment by guybedford** [comment]
This seems to be working via:

https://jspm.org/sandbox#H4sIAAAAAAAAA62a31fbNhTH3/tXqNkD7YZtAmO0NOEEaNYDBdqRUranHcW+iQW2ZCQ5JPTwv+/6R0ISIoHoHsDYut+Prq51JVmi9ToSoZ5kQGKdJnuvWtML0GjvFSGtFDQlYUylAt1u5HrgvWuUBZrpBPYueHmNWkF1P5NwmkK7MWJwmwmpGyQUXANHxC2LdNyOYMRC8MqbdcI404wmngppAu0mVtAKKg9afRFNSuprz8MLIce9r6fkE3CQVAtJjtKCT05pVpZ2I6bJxfnJLrZHZ2o3CIZTU/9KZanPRPDLxeZZ/M+ng+uPpxty0rs77l0048/dnbNvf/Um11vfT063Lk8u4i/feuPJ6fv9u+bV/uF4dPA3PR7uYyWeV/qjQskyvZdJEYJSpE1+EOCjXbysnX352P23e/Z9bZesYXmUh5oJvkbuyX0rqHUPCFKEv91gZUNSmpXh/VG2pn6oGrv1A3ykIKUY9NDLmSeBhhoLG7PG0lkreZbuPrLtbPpNfzOImNIBqIDxCMaoaJTw+/WqUhWKDBbqXIGfK0aDTp/2IQlkjrWlgO8uyUAqrCINqFIg9beYqaPqLbM7iCw+L6I6O35zx3//NLFoxfqzHAoxEhoOE8T8lBtznOdXDmPMgujnKq4Zz6+U8Rgk0+pECAU/VfUC6fkOiP4VhPqS6Vjk+qvE7iU1g//BHxv4ee4xHJZQdw43OZNwyZIopPLl/XM1btmVQZLjWJizoExKLxSY5hyfeDAqfieYnsWoZfPimYjOhr/d9HeqjEejVPCrubx/llMSBi/yBHUL1YOh4kxkGDt0KxTS2h0WDIuhrOlvBwnrr8Y+GvyCKjRK0/DaVo1V2NkqR1BTrWGixhZ2UdxpIqFZvxG899MlBoxxIrFAynKkbKIfq3y4hklfYK/z8A8LZt6s9GkjUDIMpo8/w2SJm4iIqtjD1xgmNM0s6Jll5/ciPTablcLMwz5jn8lWECuNkRlBP5e2FHqMrCRmIhsMQAIPbZ10BXUmM5OLIYMNY7cIzFRGLnbe2AlZCMw0XJ5lcA7D7tjt5c8LzfQRSFt3XYEtFEbegCXaOoQ+BlYSC5HbJoZVPL489C/SjorsdUYercj5ea5Ubv2oVJh5QnZdu1GtMTKH4OYh2htZMbWtph6z0N7IYvyc8qFbetcaCzNM8gjcnJyKLFTsqQrKDwtH8oPQQsfUcntFlcRGFNeugS0kZqLal5K6jRi1xsI8ECIB6hjSqcrC7SaQ4hrCkVurbNw0064xKDU25k1OE1dmobEw/8z5C/rqTGYhnzFXX1Fh4+Vp33HemIos1C/lh4ojtRJZqF8TyviL0HNKC7+nJeNDR3QlslAvcP7Cecy6C7AKPNMZ2bh2PXDLhlJh47mN24XASCv2dlxgaG9jfaf44eXm3kxl5kIq2J3bQF1rzEzmlvZob2RxIdyCWAiMtIzKYv/Ifek9LzTTmfU7cwUVBVaaY+euJEaidF7rSOtKR0KUO34bVRIzUeSOS+5SYeQpx3Wnsqw7lWuaKFuOKJE60lBgoUnt2FcqiZmosccfUut23QroVGXnqmIDzx1cyszkPHVD5sv7MA8sTR3XroXATGOp47hdKsw8TEuFn1xu7Z2pLFzmimRmWs5dl3+lwsa7ccXdGGkj98l0ZJ9Jb6tNaSdkrVliVpvcHlWKDW0RXLArmH5z5f5gJkXmFYdOtvY+GHWa2/47A+qpA6jq0Akbt2HYq6z2jCNh62gzm6dBA6qqHWhq3Ul+bNzZ8jf9DQuZ2YI1Nek0//CbW7ZYedUe9pOsyqyziV5VW9zV6ctjqgpjnEMTK3Jm08HomQKoYpok4hae+PibN6t3jVfRbqnk9k+H2gL76Ya/FdR3/vQskpD7V9Pfxc/8uWl9Gky6PXIqinaRXsxStTs9C8ZVriKZSCYDliQEhziSlmaK9KW4VSAVqRONsDmFyrPy5g02kMA4hEyTw1jiPEvevf/t7eK5L6FqwkOiZNg2btMrr6rXU4V7GKzt6bb/UlHRahJKoXASZkPG2w3KBZ+kIleNveWWLxwaV5TyxJhMG/Mr+kamZxgX7LzoT2SA7Vh1dvyhohISBORSMg0YC8brgJFQREBikLBOMIqIpQjGdKFoh8GFMo74sIFxaBCqcQLo51gmONExTCmVx35ZTSi4Egn4iRi+WfLx7YeF99wKqqP/VlD9S8J/3JhaVaogAAA=

Let me know if this is still an issue and needs to be reopened.
