### ISSUE TITLE
preact@10.5.15 results in `TypeError: Failed to fetch`

### ISSUE THREAD

**Issue by jaydenseric** [jspm/project#135]
Attempting to add `preact@10.5.15` into https://generator.jspm.io results in the error `TypeError: Failed to fetch`.

`preact@10.5.14` works ok though. This works:

https://ga.jspm.io/npm:preact@10.5.14/dist/preact.mjs

But this doesn't:

https://ga.jspm.io/npm:preact@10.5.15/dist/preact.mjs

The file definitely exists, so I don't think the `preact@10.5.15` release is broken in any way:

https://unpkg.com/browse/preact@10.5.15/dist/preact.mjs

Something seems wrong with the JSPM CDN?

**Comment by JayaKrishnaNamburu** [comment]
@jaydenseric looks like `preact@15` is published yesterday. And it takes a little to have the same in JSPM. Usually it takes just a couple of hours. And `npm` was kind of down in the last 1-2days mainly regarding publish.
I triggered the build manually using https://api.jspm.io/build/preact@10.5.15

But looks like, there is a build issue
```
{"error":"JSPM encountered a build error processing preact@10.5.15. Please post an issue at jspm/project on GitHub, or by following the link below:\nhttps://github.com/jspm/project/issues/new?title=CDN%20build%20error%20for%20preact%4010.5.15&body=_Reporting%20CDN%20Build%20Error._%0A%0A%3C!--%20%20No%20further%20description%20necessary,%20just%20click%20%22Submit%20new%20issue%22%20--%3E"}
```
