### ISSUE TITLE
`history` package broken due to process.env.NODE_ENV checks

### ISSUE THREAD

**Issue by lewisl9029** [jspm/project#138]
When I try to import https://ga.jspm.io/npm:history@5.0.1/index.js, I get the following exception:

```
Uncaught ReferenceError: process is not defined
```

This is due to the fact that checks for process.env.NODE_ENV.

Interestingly enough, in the skypack version of the same package, the NODE_ENV references are nowhere to be found: https://cdn.skypack.dev/-/history@v5.0.1-ug7XhJQK9EKMfLWXS31e/dist=es2020,mode=imports/optimized/history.js

Looking at the github repo, I only see process.env.NODE_ENV checks in the node entry point, and nowhere else: https://github.com/remix-run/history/blob/bb756f4ba2da9a6a9edbd6d716b1c2b5575621f8/packages/history/node-main.js

I think what could be happening here is skypack is using the [`module` entry point](https://github.com/remix-run/history/blob/main/packages/history/package.json#L9) specified in its package.json, while jspm is using the `main` entry point meant for node?

Luckily I've been able to work around this fairly easily by just injecting `process.env.NODE_ENV = 'production'` before importing, but would be ideal if the package just worked.

**Comment by lewisl9029** [comment]
@JayaKrishnaNamburu sorry for revisiting this so late. 

I've been working around this on my side by adding a `window.process.env.NODE_ENV = 'production'` global, but I still think it would be ideal for the cdn to automatically replace references to `process.env.NODE_ENV` with the string `'production'` and then running a minification pass to remove dead code for non-production builds, with something like https://www.npmjs.com/package/@rollup/plugin-replace.

This is a pervasive pattern in the ecosystem, and not doing this results in many super-popular modules (react-router-dom, framer-motion, are the ones I've encountered so far) failing to load, and results in a large amount of dead code being delivered to prod environments.

**Comment by guybedford** [comment]
JSPM will continue to not inline `process` based on the principle that we believe module standards should work without complex tooling, and are willing to take a hit in usability to help guide that future.
