### ISSUE TITLE
`react-marked` is failing to resolve `unist-util-stringify-position@3.0.0` 

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [jspm/project#141]
The package `unist-util-stringify-position` is available both in `dev` and `ga` 

https://jspm.dev/unist-util-stringify-position@3.0.0
https://ga.jspm.io/npm:unist-util-stringify-position

But when used using `jspm.dev/react-marked` it fails in resolution

https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hKEpNTC7RzU0syk7JL89zMNcz1DMAAO2RZlEjAA

**Comment by guybedford** [comment]
I've fixed that version lookup issue, let me know if you're still seeing problems here.

**Comment by JayaKrishnaNamburu** [comment]
All good now, closing this. Thank you 😄
