### ISSUE TITLE
Debugging @mui

### ISSUE THREAD

**Issue by guybedford** [jspm/project#142]
When running https://generator.jspm.io/#U2VhYGBmD80rySzJSU1hcMgtzdTPTSxJLcpMzHEw1TPQM9EPSa0occtMzUlhKEpNTC7RTcnPdTA0B0oZQQSgHAA82EitSgA in the sandbox via https://jspm.org/sandbox#H4sIAAAAAAAAA81YW3fUNhB+51cI9wXa2F4npAlhN2cDpFzK9gR2U077psiTtYJtGUlOsuHw3zuWL9jLWmtK29MH2Nj65pubPDPS+H4omF5lQCKdxMf3xvUP0PD4HiHjBDQlLKJSgZ44ub50Dx2zoLmO4fg8Nb/h2C+fG5GUJjBxrjncZEJqhzCRakiR4oaHOpqEcM0ZuOZhh/CUa05jVzEawyRABWO/tGB8IcKVYb3vuvhDyOv52Yy8gBQk1UKSV0nBT2Y0M6unIdfk/N2bI/RHZ+rI95c11LtSWeJx4f9wvvt79MeLp8nzw5Fcze9ez8+DiM2W+i5cnC3mt6/fsGx29/L0JlicvZ09Pj2b05FgTM/uzuPo19Pst8Wzg3cLlp6Fi5PR05H48+3b+fLlycnh7inX8+UJGuK6xmbFJM/0cSYFA6XIhHwikF4fkU+fyeexX61+AZIiEROHG5cSmplAfzJ+VS+Vc1S9wFfTJOd+QjVIjJ2/gFv9C4c4RIjTOE8br9MsOepITPe9kffoi5yPOfF4GsItyjg7tRYJlGkLp1mfBgdItmujcEORbKMpMBupDNPnktBRTGTQicQGztZyEaoLegGxL3Pcrgng3oozkMoHlfhUKZB6EXH1qtyF/A6sMexQTQ+84GdvtJ2xHRC7QZgPSEP1XSZUHMOV8jTCTaHVGyEUfJfqDtNwA8TFFTD9nutI5PpMYoal5vAP2GMjHmjef50QjqUSDX0HH3Mu4Tlc0jy2fYJDkrKBcZgx/4vEQCI0F6nPKIusWjvAaRB4WOT8kCvtVyuuWfEupLjBr9RDQ/p0RVRFQ1QVuOnIO6wVFc8NP7v6Kue1HFcuNobMvcYCYS04GwWmgResu9YBDDEhwT+wOA1RXkHR0QNvv6u2WhqicFsz6QI35s+sDMmfMl1uoHsNGONquk+hsmhBtdoGMMRNFQEMctMAjcq9rpdmYZCXehXb+1UXWcR0bz2m5dIQdXlajHnKWgzXse09U78bEsVc83iYogJoorjml1kYouoG6Af3G76GNh7d263da7+3hbOYw5iQVl01xsxpI5fGWUS9/WDzjNUm9Z9S9iHEQnCebt8dfVrWOXy7ypkIafw9+joE/coyya9xfnV1BAlPl9s0rcGN0i0RLC1wIV3ydGt+OmDD3jMDN+wrpcE2B7dQ1YBe9u8evq3fSAOqfO9jY7G6tfAUy6blBOVGL5699W2N07tbd3gahs9iai0ULTgat4sfr5meK0ELt8QP7Br+Hn1Ldk1DJNAxN61bDBZFqjmzaeiRmO5hha1aSA9kQy0qxyEX7eLL1KK0g5s+MinZlFAzCRQHSpsHX0DTYB+rdP/uLc3nNrIaMsVRL9izfGclUEuaKm7q9FKKPNvKvC6Azj9Ci/t2tBHyr9StWw2h33KIbYmt0SocH8M8BmmhazBFb7DVhAboo3PMXtA2klZi67RYlqypKgEYQCwJI797zG4O2psP1n33CN0D9zdtl74D/1BL2vXt3zHjXv1/8a99c1PdTJHTOcEOhtkh84gn6qi+l0popkgm4tUlj2NyKSRJDEyRajpQ5KY8ARHeklB5Zh4eUJSCWwaZJs8iKRIgh49/eti9XyJUrVJGlGSTPidBuaVeHCzRPNxBwa53WA1L3TUPG2XhOmFSKCUkx9Y2cSiWsFUicuUcr7vfubsqmczFFak9+hENJLNqtzTXTeQS3em/xHryFYNJVCVVniN6MM8R0YKZi6cnpbGE+D55L7kGjDNPq2QQJkIgEUjYIZgh5KFEQUYlmkUwcWByhC8djLFDqNaSX+S4JlKCk0XNUgbCM2qYSJWIwYvF8sFXru+Udu405j580tlWY7+89Rz75W3sX3PlQiulFQAA

The first issue is that `process` is not defined. This is because `process` is not defined in ES module contexts and can be resolved with:

```html
<script>process = { env: {} }</script>
```

The next issue is an obscure `b is not defined`. Debugging with source maps gives:

![image](https://user-images.githubusercontent.com/598730/140461392-8a512a9c-8516-438f-9aeb-4293a281ca1e.png)

where the issue is that the `composeShouldForwardProps` function is returning undefined.

I was unable to trace through the logic in the above what the expected exit path should be, as it seems this is a straightforward "not all exit paths return a value" bug, but obviously the root cause would be something that the JSPM CDN can likely look into fixing further.

**Comment by x-yuri** [comment]
If I understood you correctly, here's the [`webpack` output][a].

Also, how do you debug with source maps in this case? I mean the `mui` assets don't contain links to source maps, which kind of suggests that they're not available. Or location is unknown. And why does it even needs source maps in the first place? Isn't it a `development` build?

[a]: https://gist.github.com/x-yuri/e28a6396425450f61f49b03330d888a6

**Comment by guybedford** [comment]
@x-yuri thanks for sharing - we just need the actual webpack build file though that runs either unminified or with source maps to debug the actual execution paths. Specifically the execution of that function I screenshotted and the variable comparison of it.

**Comment by x-yuri** [comment]
@guybedford  The "import path" is:

```
./index.js
./node_modules/@mui/material/TextField/TextField.js
./node_modules/@mui/material/styles/styled.js
./node_modules/@mui/system/esm/createStyled.js
./node_modules/@mui/styled-engine/index.js
./node_modules/@emotion/styled/dist/emotion-styled.browser.esm.js
```

Not sure what you meant by variable comparison, there are a lot of [tags][a], and [for each][b] of them it [calls][c] this [function][d].

The build: [dist.zip](https://github.com/jspm/project/files/7505286/dist.zip)

[a]: https://github.com/emotion-js/emotion/blob/%40emotion/styled%4011.3.0/packages/styled/src/tags.js
[b]: https://github.com/emotion-js/emotion/blob/%40emotion/styled%4011.3.0/packages/styled/src/index.js#L8-L11
[c]: https://github.com/emotion-js/emotion/blob/%40emotion/styled%4011.3.0/packages/styled/src/base.js#L40
[d]: https://github.com/emotion-js/emotion/blob/%40emotion/styled%4011.3.0/packages/styled/src/utils.js#L49-L70

**Comment by guybedford** [comment]
@x-yuri I was finally able to trace this down to a bug with the interaction of "module" and "browser" where it is using the `.cjs.js` version instead of the `.esm.js` version. Working on the fix.

**Comment by guybedford** [comment]
Mui is now working correctly, let me know if you still have issues here at all.

**Comment by x-yuri** [comment]
Indeed, that's a step forward, it imports, but still doesn't work :(

Let's take the [generator link][a] from the original post, copy the result, apply the `process` trick, and use the following code:

```js
import TextField from "@mui/material/TextField";
import { createElement as e } from "react";
import ReactDOM from "react-dom";

const div = document.createElement('div');
document.body.appendChild(div);
ReactDOM.render(e(TextField), div);
```

And what I get is:

![][b]

Let's add the peer dependencies (I realized it doesn't work w/o them with `webpack`). The [generator link][c], the code:

```js
import * as React from "@emotion/react";
import * as Styled from "@emotion/styled";

import TextField from "@mui/material/TextField";
import { createElement as e } from "react";
import ReactDOM from "react-dom";

const div = document.createElement('div');
document.body.appendChild(div);
ReactDOM.render(e(TextField), div);
```

The result is supposedly identical:

![][d]

[a]: https://generator.jspm.io/#U2VhYGBmD80rySzJSU1hcMgtzdTPTSxJLcpMzHEw1TPQM9EPSa0occtMzUlhKEpNTC7RTcnPdTA0B0oZQQSgHAA82EitSgA
[b]: https://i.imgur.com/zemUItc.png
[c]: https://generator.jspm.io/#U2VhYGCVD80rySzJSU1hcEjNzS/JzM/TL0pNTC5xMDTUM9MzQIgWl1QCVcGFc0sz9XMTS1KLMhNzHEz1DPRM9ENSK0rcMlNzUhjAJuim5Oc6GJoDpYwYoEaCOQD6g5f1dwA
[d]: https://i.imgur.com/hy3oH1l.png
