### ISSUE TITLE
Several babel packages broken due to 404 on @babel/helper-environment-visitor

### ISSUE THREAD

**Issue by lewisl9029** [jspm/project#151]
It looks like babel released a new update at v7.16.5 that introduced a new [`@babel/helper-environment-visitor`](https://www.npmjs.com/package/@babel/helper-environment-visitor) dependency to several plugins (including `@babel/plugin-transform-typescript` as a transitive dependency) earlier today (8 hours ago at time of writing). 

As of time of writing, https://ga.jspm.io/npm:@babel/helper-environment-visitor@7.16.5/lib/index.js is still 404'ing, so the latest versions of these plugins have been failing to resolve.

How long should we expect new packages to propagate from NPM to the CDN? 8 hours seems longer than I would have expected, maybe there's been an issue with the build?

**Comment by guybedford** [comment]
@lewisl9029 I'm not actually seeing a 404 for https://ga.jspm.io/npm:@babel/helper-environment-visitor@7.16.5/lib/index.js, do you have an exact replication of the issue?

**Comment by jaydenseric** [comment]
I just queued it to be processed by JSPM for you by visiting this URL:

https://api.jspm.io/build/@babel/helper-environment-visitor@7.16.5

It will take several minutes, usually less than an hour. You can tell it's done by visiting the URL and seeing a different message in the response body.

**Comment by guybedford** [comment]
Ah it seems @jaydenseric bumped the build queue for it, yes that's the way to prioritise newly published packages in the build queue.

**Comment by lewisl9029** [comment]
Ah excellent, it's working for me now. That's great to know. Thanks for the ridiculously quick response, both of you. 😄
