### ISSUE TITLE
JSPM Core Meeting 30 December 2021

### ISSUE THREAD

**Issue by guybedford** [jspm/project#154]
### Proposed Agenda

- Package landing packages
- Chomp
- CDN & dev update
- _Add your agenda item here_

### Meeting Details

Time: 8am PST Thursday 30 December 2021 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20211230T1500)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by guybedford** [comment]
If members aren't able to join for this meeting due to the holidays we could offset by one week to 6 Jan, unless that conflicts for anyone?

**Comment by jaydenseric** [comment]
I'm keen to listen in if you're happy for a non-member to lurk (if I'm still awake tonight at 2am my time 😅). Could I please have an invite? Perhaps via Twitter DM; [`@jaydenseric`](https://twitter.com/jaydenseric).

**Comment by JayaKrishnaNamburu** [comment]
Hi @jaydenseric yes you can. Are you in the discord group of jspm ?

**Comment by guybedford** [comment]
@jaydenseric you are welcome to join as an observer in meetings. They are held every two weeks. DM me for an invite.
