### ISSUE TITLE
CDN build error for @polkadot/util-crypto@8.0.3

### ISSUE THREAD

**Issue by danforbes** [jspm/project#155]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
Should be working now, I see `@polkadot/apps-config` and `@polkadot/api-derive` were flagged as slow builds so may also not be working, just post another issue if you need something that depends on these as well.

**Comment by guybedford** [comment]
I've verified that the full generation for @polkadot/util-crypto@8.0.3 is working now.
