### ISSUE TITLE
Package Issue - aurelia-framework@1.3.1.

### ISSUE THREAD

**Issue by jpietarinen** [jspm/project#159]
Generator´s HTML boilerplate code https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hSCwtSs3JTNRNK0rMTS3PL8p2MNQz1jMEAERlFhwmAA throws an exception ”Uncaught SyntaxError: The requested module 'aurelia-path' does not provide an export named 'default'”.

**Comment by guybedford** [comment]
Thanks for posting. If you clear your browser cache it should be working now. Just let me know if you hit further issues.
