### ISSUE TITLE
@sentry/core publishing issue

### ISSUE THREAD

**Issue by jmadkins** [jspm/project#163]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
Thanks I've triggered the rebuild on this. It seems this is a recurring issue with new publishes - I expect it might be something to do with the multi-package publishing workflow perhaps they are publishing the dependencies after the main repo or something like that. I will keep this issue open to investigate further, but 6.17.2 should be working correctly for now.

**Comment by guybedford** [comment]
The latest versions of Sentry seem to be working correctly, closing for now.
