### ISSUE TITLE
CDN rebuild API

### ISSUE THREAD

**Issue by guybedford** [jspm/project#164]
It would be beneficial to update the build queue request API (https://jspm.org/docs/api) with the ability to trigger rebuilds as well for packages that have build issues that need updating.

The main API integration work here is just linking into the AWS invalidation API (https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateInvalidation.html) once the rebuild is complete, but this should be straightforward.

**Comment by huntercaron** [comment]
Hey @guybedford our users still run into this decently often, is there any sort of quick solution possible here?

**Comment by guybedford** [comment]
@huntercaron sure, I will prioritise this this week.

**Comment by guybedford** [comment]
Also, if there are specific packages you need done now, please just let me know here or on chat.

**Comment by huntercaron** [comment]
A couple from this week are `react-timer-hook` and `shadertoy-react`

**Comment by guybedford** [comment]
@huntercaron sure I've just cleared both of those at the latest versions, and the cache should have invalidated by now. If either is still not working just let me know and if there's a replication I can look at.

**Comment by guybedford** [comment]
Did these work for you?

**Comment by guybedford** [comment]
Got completely swamped this last week, I'll pick it up again next if there's still interest.

**Comment by guybedford** [comment]
(and I'm always available on DM for issues)

**Comment by guybedford** [comment]
This feature has now been implemented using a privileged version of the build API that will support rebuilds with cache invalidation of the CDN. @huntercaron I will forward you the details. If anyone else has a strong reason to need access to this API, please DM me and I can provide a unique token for you.
