### ISSUE TITLE
CDN build error for @chakra-ui/modal@1.10.5

### ISSUE THREAD

**Issue by GuilhermeAmado** [jspm/project#167]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
Seems to be working correctly at https://jspm.org/sandbox#H4sIAAAAAAAAA9Va23LbNhB9z1cg6os9DUhRju3UlT1yGvfiids0iqfpI0RCEmySYAHQipzJv3cBXsSbZNBOZtoH25L2cnaxi4OFzPHzgPtqnVC0VFF49mxc/KEkOHuG0DiiiiB/SYSk6nSQqjl+NTACxVRIz65j8zcYu9n70iQmET0d3DG6SrhQA+TzWNEYXKxYoJanAb1jPsXmzQvEYqYYCbH0SUhPPQAYu1kE4xkP1sbrc4zhD0KX03dX6BcaU0EUF+i3SPtHVyQx0ouAKXT9/u0J5KMSeeK6i0LVuZFJ5DDufnc1+n359y+vb99cDcV6en85vfaW/sXNH9OrVTpVf6r74MO7++sfLu9/vVh5oDR8c/Xz+dvgj4/fn0fn54CDMUQmfcESdbZiccBXTiK4T6VEp+gzovHdCfr8BX0Zu7mSTiB7ifRinw7kWioa3UjMTPwRScyqfjZJDLIP5eAk/wA+mkANbgXBKXMjHpAQZIMyReJk/soU4yQ6aVpMPMcbOoduwKRySxk2ModKbTwwaF9eZFFInye0FsR2wIqWDnZGZjR0RQrdEVEoZZhQId2AzllM3wlwK9TaIoOam8mx4x05x1u86ehfPBgBpOnST9CIgXwqfMWVJfZXwu2DyeIlFUzJt5xL+lTkmjNbfEWhQO/pPykT9A2dkzRUT4+jw+lj4vmLhYFPRPB1Ayq82kXEZzfUV38xteSpypuZ0Sd3yRa3djHJELg5+MDPhSBP3qY1Z3b4iv/EY5lGZBbSrxJDy6FlHEDVfP5kcOOlibghZz+E7YRnqVI87sXqVUMg95Fz0OT2qkZB8VuC4CEX+iywYYkuMwjgpeO1Aijlu+Hn3E8lDrl/2wt+Y2byHzXhN/Ld8EvOb222XMMCQF85wyaoEe3GY37PUmuDycgZtldYS3aD6VGi57yQmUB6B+2eymS7IQUlvsIwBvVCLa30pNIuZim2wU4VC/tVtGJnmqm10hWF3RFItYaJGGdwvWKoWepVOG63V03ngUAeEUEJ3dFrNphKkFjCNN+zwTdmhkhaXbeR74bvX/ei4pBwa623FptGXMfi+sRf2jBmTX/iec5xsbq5BBuJMxN8JanYBbkkctkDUatPhhue0u9tYJjEcKVJ8B0Jmc2A1GlnNnIj0ZqCTSQRvGD3fVY5t4C0j4v7ToGei2xwzX7vgWr0O2trJDaQIIZrcL9kSxtY7GHBmgVyKbRCX1LaJ2Gjb0o8bKBqgRWi4bI+kMZAL/JRC9SIbFDTWH9VIW1oomlSbaniMytIS1qq6ZuCNrLMGMkCcUXJLe6/dapmkOyoSLb6+Q54Au2GlywIqAX9V5RNF+WkT+Uh3KgC+qnh2+fJGisOQy1LZtzq2tYymcBAA7uz072UeMY/mWHVYlqqqdcGhqrA8W+ad66AKriZ4RjE2OaeV9fPt5teo6IKdfd9JunK+Dx0fii5Q46GXncJNgYw+cdSkVhZZLATpvTThBIkovrqYDdK1NQnhxV6kHkmUYd/uY59S99aFfwetPzW3S6oLlXsW+y5UtXsc2938y/pGoegYLOvNrrG86vMc6dXDhIdRD7cQiUU8y1KusXQbK+8vltUOnZEyAM9lED9FnTFlMV007SYvISCjzpTzL4IwURKtrBYu5o6uPW2sEXCE9vWLFX1sTXcsFx3X5rZSH9lYFGFje7EOzQjXleolnNMPr4cmyFiqx9NpRR2K9NsNJ9Ta89tQ0Oah27IZjvgAm5xfylVHw5/TqApfR4lRFhs0bYNdPho1zrjPvzbtIAb/mF5773pJpjMhll0R6E58Y4cb9uplykJONjvKJa+4KHF2ddhBKG/3HDY1gOkwxLPiHgUpDYE2NGGkXth9jnBLNG3nWUFAcKAiiWLFyG1+qqv0wwwvYcOCwlXySANqcW6lqp62Nu2dbIQ4MKWUltqapnA2Tl86EzWRjadnekBO8OxedAZsWLxGrP4To+YsQVF1fUNM+Wx1iUdI6/ii4UuEA2B06wOhKaFOaWPuvOQQI8WHrUadIbe5eY1xHnUcJVKin0ShjPi30IrW3yt3bTICXtn62kbzfG+zaauKJs1OOzmj9z7lwLmURdyq39Qfpt/DT42/vpl9/+TQNcsXo/+UcP3UXVKrhBIz+ha49h/J7Tt52o9xl6sAKfFyyYt9IyrvU+/UTzPit/6p/rwRP4ACJoar5fTEzRNE/OMBAo5CeBwRHDfhnNMImjgORcRkHW4RixGQGAovypLpKkMKY5+u/A8tBfQBFpcG/MYQTiCiDWSmeN985DH5rENKfzTh46l/JkOaAevnPOlE7FY53jWlc91DHNlBHNxmRl6rTcmgh++QpAIIjFkgfMM0MUUXZlEkYs+wLk6zaJz0eX0IwroHVpxcTsHW6eIX8M8IglsCAKmgoOis+uSeko5WIH3M8StqISzc3FSX8czU+IsWSd7zGWv/WzLvqOWNN6L0OmZfnBI8pA6IV/sRfv7P27pjLfQBnqtSJJAaGjOYIlWgikgMd0F4A/lD90M8lZBpk0U4qlKUoX27hhB72HLpQlUwc3rUF3l/a4lbTzOk7keZCudxdJcprGbPdM0drNnrf4FpDvM1oMlAAA=

Let me know if you have any further issues here.
