### ISSUE TITLE
Will jspm drive support package.toml?

### ISSUE THREAD

**Issue by LongTengDao** [jspm/project#174]
This would make great help to both toml spread and package config (json config ubiquitous and day after day cost really too much).

**Comment by guybedford** [comment]
`package.toml` is a really nice idea, although JSPM wouldn't really be in a position to drive anything like that unfortunately. I think as a replacement for the `.rc` or `.config.json` files TOML is a great fit though, and have another project I'm working on which uses this approach to configuration.

**Comment by LongTengDao** [comment]
nice! wait in hope
