### ISSUE TITLE
mobx fails because process is undefined

### ISSUE THREAD

**Issue by YousefED** [jspm/project#176]
sample urls:

https://jspm.dev/npm:mobx@6.3.13
https://ga.jspm.io/npm:mobx@6.3.13/dist/mobx.esm.js
https://jspm.org/sandbox#H4sIAAAAAAAAA3VTUW/aMBB+51dcvZd2bRJopYrRBJV1FSpaJDqEqj2a5CDeYjuzndIw7b/v4gBakfZgWXfnu/u+787xWa4z11QIhZPluBcfLuT5uAcQS3QcsoIbiy5htVsHQ+YDTrgSx0vl7zyOOvuYorjEhL0K3FbaOAaZVg4VldiK3BVJjq8iw8AbVyCUcIKXgc14icmAGsRRhyBe6bzxVc+CgC6A2WKewhQVGu60gSfZ1oeUVz76mAsHy29fR8THVXYURZvD0/CHrWQodPRheT0rvk8///yS9k2z2M0Wy0HRpIP5LzXZ9nfzl3T3PJ08XD4PbjWfTKhuEHgINjOictDKlTDhG0teeTl+++57p2WjvYNcUq/eyGZHPPwIRFVy1Ibvb8ObcHAT5cK6qHWEaCW9Yr7Gn1534qjr37bbCwKPC0h1XpcIi0JIOzrIQbAsVLps1qIsYU06Sf/MwsrorUVjYStcoWsH4p8MW1feOOeUhW8ZEtuHwmiJMPx0eXGiA7eNysCaLPkfObRB1zewLbz7fji4Docdz5NYKIVqKUNmtLXaiI1QCeNKq0bq2rLxKf13w+gq+UnAgdFHAgitmrAmBvtB3HXZAFEEL0Y4JOJC7dWhJc3pI6DBKyDJKJ2DxYrT+iCQkuhFIycj0gy4c0asaoppBa7AQ5UOWejb0NpbXWJY6s15C+Di7t0k46jbb1p3/+/+AqGiQ+OPAwAA

I expected process would be polyfilled?

**Comment by guybedford** [comment]
@YousefED this is a common issue, and JSPM could very easily solve it. But it is a principled position of the project that `process` is not a browser global, therefore we should not be relying on patterns where a global that has no meaning in the browser is assumed to exist and be processed by a build tool. In these workflows I often just define the process global:

```html
<script>globalThis.process = { env: {  NODE_ENV: 'production' } }</script>
```

Whenever you come across this I would recommend posting an issue to the original library to instead use browser-compatible modules by doing a process check first (feel free to reference eg https://twitter.com/guybedford/status/1474434054590107649?s=20&t=pFnUKHTBrlxAg8Xj2UP7Ug). You are welcome to cc me as well.
