### ISSUE TITLE
CDN build error for werift@0.14.5

### ISSUE THREAD

**Issue by p-fruck** [jspm/project#180]
The import fails with the following error:
```log
error: Import 'https://dev.jspm.io/npm:werift@0.14.5/lib/rtp/src/rtcp/rtpfb/twcc.dew.js' failed: 500 Internal Server Error
    at https://dev.jspm.io/npm:werift@0.14.5/lib/rtp/src/index.dew.js:22:36
```

Response payload:
```
Unable to create dew wrapper for this file.
```

**Comment by guybedford** [comment]
@p-fruck `https://dev.jspm.io` is the old JSPM CDN and is no longer supported. It was actually going to be removed last year but it's still up to support legacy applications.

Instead use `https://jspm.dev/werift@0.14.5` or alternatively the import maps CDN.

I did notice another weird issue in this package dependency - https://unpkg.com/binary-data@0.6.0/src/index.js.

It's doing things like `require('lib/...')` which isn't a valid pathing scheme so it seems like the package does not support standard modules semantics.
