### ISSUE TITLE
React 18 exports changed between RC0 and RC1

### ISSUE THREAD

**Issue by lewisl9029** [jspm/project#181]
Hi there!

I was using https://ga.jspm.io/npm:react@18.0.0-rc.0/index.js for my project for a while, and just recently attempted an upgrade to https://ga.jspm.io/npm:react@18.0.0-rc.2/index.js, and noticed that the exports have changed.

In RC0 there was a default export in addition to named exports, but in RC2 there seems to be only a default export. Looks like this change happened back in https://ga.jspm.io/npm:react@18.0.0-rc.1/index.js.

I couldn't find anything material that has changed in the original packages, so I'm assuming there was some change in the build script?

I'd like to see the named exports re-introduced to packages like this, since devs are used to be able to use named imports regardless of underlying package type (cjs/esm) from other build tools for local workflows. 

FWIW most other esm CDNs I've looked at do manage to preserve named exports for react (and presumably other similar cjs packages). Some examples:

https://cdn.jsdelivr.net/npm/react@18.0.0-rc.2/+esm
https://cdn.esm.sh/v69/react@18.0.0-rc.2/es2021/react.js

Thoughts?

**Comment by lewisl9029** [comment]
Actually this is a bigger issue than I originally thought since other packages also assume react to have named exports, and break as a result. For instance: https://ga.jspm.io/npm:framer-motion@6.2.8/dist/es/index.mjs

**Comment by lewisl9029** [comment]
Wanted to do a quick bump on this since React 18 is now released and considered stable, so this will start affecting more and more users: https://ga.jspm.io/npm:react@18.0.0/index.js

cc @guybedford

**Comment by guybedford** [comment]
Thanks @lewisl9029 for the bump on this - it should be working now.

**Comment by lewisl9029** [comment]
@guybedford just gave this a shot, and react seems to be working now, but looks like we also need to update react-dom, which had the same problem: https://ga.jspm.io/npm:react-dom@18.0.0/index.js

**Comment by lewisl9029** [comment]
Here's another one affected: https://ga.jspm.io/npm:use-sync-external-store@1.0.0/shim/index.js

I was able to work around the react-dom issue since only my code calls to it, so I could just use the default export. But this one is used by third party packages like https://ga.jspm.io/npm:react-query@4.0.0-beta.2/es/index.js.

**Comment by guybedford** [comment]
@lewisl9029 should be working now. Since you're an expert now, if you want access to the rebuild API DM me and I will share a token you can use to achieve these.

**Comment by lewisl9029** [comment]
@guybedford I just found that `react-is` has the same issue, but for some reason rebuilding using the token doesn't seem to have changed anything. I sent the rebuild request last night, and checked again this morning.

Here's the current version where only the default export exists: https://ga.jspm.io/npm:react-is@18.0.0/index.js
Here's a previous rc where named exports exist: https://ga.jspm.io/npm:react-is@18.0.0-rc.0/index.js

This is breaking styled-components, a very popular package: https://ga.jspm.io/npm:styled-components@5.3.5/dist/styled-components.esm.js

After figuring out what's causing this to not rebuild properly, it could be a good idea to just do a bulk rebuild of every package in the react repo: https://github.com/facebook/react/tree/main/packages. That seems to be the common factor among all the ones I found so far.

**Comment by guybedford** [comment]
@lewisl9029 the invalidation API runs faster on the weekends, so I'd suggest trying again on Sunday. But if you want me to do it, what would help is a comma-separated list of package names and versions of the form - `pkg1@1.2.3,pkg2@2.3.4`, then I can just post that invalidation this side anytime easily. It's just hard to trawl through the versions otherwise.

**Comment by guybedford** [comment]
I finally went through the full list and ran all the rebuilds and invalidations here.
