### ISSUE TITLE
JSPM Core Meeting 24 March 2022

### ISSUE THREAD

**Issue by guybedford** [jspm/project#183]
### Proposed Agenda

- Tooling update
- CDN update
- Package packages
- _Add your agenda item here_

### Meeting Details

Time: 8am PST Thursday 24 March 2022 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20220324T1500)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by guybedford** [comment]
@Aslemammad you are welcome to join and listen in, I will DM you the link.

**Comment by fusionstrings** [comment]
I am unable to join this one but https://jspm-packages.deno.dev/ have some updates on package detail pages

**Comment by guybedford** [comment]
@fusionstrings the difficult thing about changing the time is the only option is to make it later really. Would that work for you?

**Comment by fusionstrings** [comment]
Yes, I guess I later would work for me. Thanks :)

**Comment by fusionstrings** [comment]
Thanks for the new timings 🙏🏽 😊
