### ISSUE TITLE
JSPM Core Meeting Time

### ISSUE THREAD

**Issue by guybedford** [jspm/project#184]
We're looking at possibly moving the meeting time a little later.

@vovacodes @Jarreddebeer @JayaKrishnaNamburu could you each indiciate if you could make slots for 1, 2 or 3 hours later than the current time?

**Comment by JayaKrishnaNamburu** [comment]
1-hour later from the current time works for me. Anything more would be very late in the night 😅

**Comment by guybedford** [comment]
Okay thanks, I will wait for confirmation further from @vovacodes and @Jarreddebeer before updating the meeting time to one hour later.

**Comment by vovacodes** [comment]
It works for me too

**Comment by yavko** [comment]
10 pm is fine for me too I guess (I'm pst)

**Comment by guybedford** [comment]
Ok, we'll go with one hour later, I've updated the meeting calendar and created the next meeting to the new time - https://github.com/jspm/project/issues/186.
