### ISSUE TITLE
Some issues importing from JSPM

### ISSUE THREAD

**Issue by lucacasonato** [jspm/project#197]
I am occasionally getting 500 errors when importing packages from https://dev.jspm.io.

Example: https://github.com/lucacasonato/fresh/runs/7020847576?check_suite_focus=true

**Comment by JayaKrishnaNamburu** [comment]
Please change to use `https://jspm.dev`

https://github.com/jspm/project/issues/196#issuecomment-1161937319

**Comment by guybedford** [comment]
Yes `dev.jspm.io` was deprecated a while back, eventually it will redirect over to `jspm.dev`. If there are any issues upgrading to `jspm.dev` please let us know.
