### ISSUE TITLE
CDN build error for @firebase/component@0.5.16

### ISSUE THREAD

**Issue by jwfwessels** [jspm/project#198]
## reproduction:
@firebase/database on @firebase/component@0.5.16 (which is the current @latest tag)

link to repro:
https://generator.jspm.io/#a2NgYGBkDEpNTC5RCC5JLCpJLWJwSMssSk1KLE7VT0ksSQQxHAz0DI31jACAmMorLQA

_Reporting CDN Build Error._

**Comment by guybedford** [comment]
This should be working now.
