### ISSUE TITLE
JSPM Foundation Annual General Meeting - 14 July 2022

### ISSUE THREAD

**Issue by guybedford** [jspm/project#200]
### Proposed Agenda

- Directors update
- Membership amendments
- Bylaws amendments
- Financial update
- 2023 Forecast
- _Add your agenda item here_

Since this is a legal requirement of the foundation and quorum will be required for this meeting, it would be appreciated if all voting members of the organization could attend. /cc @Jarreddebeer @jollytoad @vovacodes @JayaKrishnaNamburu @fusionstrings.

During the meeting we will be updating the membership per the bylaws to remove the membership of those who have not attended for the entire last quarter, which includes currently only @jollytoad, unless attending the annual meeting to request retaining membership.

### Meeting Details

Time: 9am PST Thursday 14 July 2022 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20220714T1600)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by jollytoad** [comment]
Hi @guybedford, sorry I haven't been round for a while, I've moved onto other projects now, and whilst not using JSPM directly anymore, I'm keeping a keen eye on the project. Please feel free to remove my membership. Thanks - Mark.

**Comment by guybedford** [comment]
@jollytoad if you would like to remain a voting member we could always make an exception if you're able to at least participate in governance meetings as they come up from time to time. Your contributions were much appreciated either way, and thanks for the update!
