### ISSUE TITLE
JSPM Core Meeting 11 August 2022

### ISSUE THREAD

**Issue by guybedford** [jspm/project#203]
### Proposed Agenda

- Development update
- Package packages
- Discussing vite-plugin-jspm

### Meeting Details

Time: 9am PST Thursday 11 August 2022 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20220811T1600)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by Aslemammad** [comment]
> Discussing vite-plugin-jspm

I'd like to hear the team members' comments and opinions on the plugin and see what the next steps for this plugin are!
