### ISSUE TITLE
Some valid Node ESM packages can't be imported from jspm.dev

### ISSUE THREAD

**Issue by trusktr** [jspm/project#207]
I'm able to import them in Node, and with Webpack which also follows Node ESM spec.

F.e.

```js
import html from 'https://jspm.dev/solid-js@1.4.8/html';
```

fails with

```
Uncaught Error: Unable to resolve "solid-js/web" from npm:solid-js@1.4.8/html/dist/html.js
```

Related issue with examples of two packages and three CDNs: https://github.com/solidjs/solid/issues/1159

**Comment by guybedford** [comment]
Note that we recommend `ga.jspm.io` instead of `jspm.dev` for most production use cases. See eg https://generator.jspm.io/#W8XDwMDE7JSYlJqj4JxflKrgl5+SqpdVrOBakZhbkJPKUJyfk5mim1XsYKhnqmegm5RakqhnjF1Uvzw1CQAAdsxQUAA.

That it doesn't work on `https://jspm.dev` is a bug in jspm.dev in supporting package own-name resolution. I plan to update jspm.dev soon to provide better support for features like this.

**Comment by guybedford** [comment]
And here's a sandbox link:

https://jspm.org/sandbox#H4sIAAAAAAAAA5VUUVObQBB+91es9MXWAKatViNkqpmMY1ocFVP18YCNnD04vLsESaf/vcuROJoZH/rA3LC79+33fcsSbGcyNU2FkJtCDLeC9YEsG24BBAUaBmnOlEYTOnMzcw8dmzDcCByesgQFjKRCuJAZeo8axs+sqAQGflfxAlKyAkNnwbGupDIOpLI0WBJozTOThxkueIqufekBL7nhTLg6ZQLDPrUM/I5TkMissajbrksHwCS+jOAMS1TMSAXnRYsPEatsdpxxA9PrnwNSaCo98P2HdSmxrQqPS//D3u4kvz875dnvKop1/zqNvi5icVc3e0eTfqqffpUjE0e1acZC/Ii+XTbT5fUyrj5HF1fL/s3l1c1Umji7Wj7zg6e7/QN2ejI6v5H8fnpyQiRc1/LVqeKVgdbt0OGWZcEq6+YfS3UV1M5gFaCQloJn7mMbc14EsBfmZVUM1iXf+96+t+cmZLb3xc+4Nr5GtcBWp9PbBPRrTP4blO5sAlvcv1vdE/idyFbTakQwjiGS2VwgxDkv9GA9INKuoZKimXEhYEaTK2yZhkTJmhpoqLnJ5dwAf3VDzyv7ssPoFj6nSJaOciULhMOj3Y8bZjPdlClolYbvCUXtdn1d3dKzevudyI1UqxZSJbWWij/wMnRYKcumkHPtDDeVvxl2h2InDWsxn4gbWJcnGmbE/9Wsj98rvMVko9aO8bhrCuD7cKu4QbKKlys/adEyWm9U2AMymcAYaKwYrQACeY/WZgo6ZJMDzBjFkznlZAkmxzVKJ8izbWh1qT96Qj7srJj1XlH8ePzmUwj8bmVpg+3P5R+qGTgHdAQAAA==

**Comment by guybedford** [comment]
This was actually a very specific resolution bug it turns out, fixed and working now - try `import('https://jspm.dev/solid-js/html').then(x => console.log(x))`.

**Comment by trusktr** [comment]
Thanks for such a quick turnaround! I am just now circling back and testing things out.
