### ISSUE TITLE
Lit 2.4.0 referencing incorrect lit-html dependency 

### ISSUE THREAD

**Issue by heyMP** [jspm/project#214]
Lit 2.4.0 is attempting to reference lit-html 2.3.1 which is causing an import error.

https://generator.jspm.io/#k2RjYGBkDM0rySzJSU1hyMkscTDSM9EzAAD/u4ltGAA
![Screen Shot 2022-10-07 at 2 30 12 PM](https://user-images.githubusercontent.com/3428964/194627498-71f8c904-c473-41a9-bec0-b8379b44822f.png)

The correct version is lit-html 2.4.0 [package.json](https://github.com/lit/lit/blob/main/packages/lit/package.json#L332)

Is it possible this is a caching issue?

## Quick fix

Pin lit-html to 2.4.0 https://generator.jspm.io/#k2RjYGBiDs0rySzJSU1hyMks0c0oyc1xMNIz0TMAcSEsACzePSQnAA

**Comment by guybedford** [comment]
This was due to a combination of a minor backlog on the build server, due to reprocessing some old builds, combined with a shutdown operation interrupting the lit-html 2.4.0 process task. Should be working now!
