### ISSUE TITLE
Importing uniforms-mui@3.10.1 I get a 404 @mui/base@5.0.0-alpha.105 

### ISSUE THREAD

**Issue by jacopomoretto** [jspm/project#218]
Hi all, as in the title I get following error importing uniforms-mui@3.10.1

`Error: Timed out waiting for the build of @mui/base@5.0.0-alpha.105 to be ready on the JSPM CDN. Try again later, or post a JSPM project issue if the issue persists.`

It seems that exists a  @mui/base@5.0.0-alpha.10**4** version.

Is it possible to solve it?

Thank you

**Comment by guybedford** [comment]
I just tried this and it is working now. Sorry for the delayed response!
