### ISSUE TITLE
React-dom/client could not be resolved

### ISSUE THREAD

**Issue by Aslemammad** [jspm/project#220]
I've been working on a demo lately, and relized that for react 18, the client entry does not work.

[Repro](https://jspm.org/sandbox#H4sIAAAAAAAAA31TW2/aMBR+hl9xmpeEDSfjraMJmtohrQ9VpfYXGPtAPPkS2SdQ/v0cJ7RsUichYfuc73IuqW+kE3TuEFoyejOvL3/I5WYOUBskDqLlPiA1WU97dpulACnSuLnnO9SwfeOm01hX4+M7znKDTXZUeOqcpwyEs4Q28pyUpLaReFQCWbosQVlFimsWBNfYrKJKXY026p2T5818Vkt1BCWbzDtH2aau4j2J3TAG21d4crLXCK+tMmENj2YQBcO7AJ3T573SGvbOg0lpAXbenQL6ACdFresJ1BUi9F26FDyi8E1gR/DQemcQbr9/XQBjSTkIr2KEh7MVELxospaoC+uqOvDyd+hMqVxlO7PGwEZdFgZ7P76Vq/iLFQSq/omVRtmIHQoc6a+Vhlk12ZieBgEX24LbIw8Pzu6RSME+eoX84iZZif2uxiwmprT87priSywEXpAL+gzuh+BnoJ/PT//FMelMJbSKKxAp5vPZ7Mg9DMOE5p2hFDGX8CW+FnE3exOzywPSVuNwvD8/yiIfMPlicTdR4Bi7sEwUE6KIZmezvF3ly3SyvdbjKf+FWrslnJzXMo9ciXDgLj1aib6YiNN7qjn2LTiNpXaH4u+GT6IfnoelXSwhVb4YOvYxzroaNzouePrc/gCfMEBQhgMAAA==)

**Comment by guybedford** [comment]
I ran a rebuild and was able to fix this. I'm a little bit concerned I wasn't able to work out the root cause though, let's keep an eye on this issue when the version after 18.2.0 is posted.

**Comment by Aslemammad** [comment]
Thanks, it's resolved now.
