### ISSUE TITLE
CDN does not download an existing file

### ISSUE THREAD

**Issue by damodharanj** [jspm/project#224]
https://ga.system.jspm.io/npm:@jspm/core@2.0.0-beta.27/nodelibs/browser/crypto.js

This URL does not download the file but it exists in the repo / npm

https://github.com/jspm/jspm-core/blob/main/nodelibs/browser/crypto.js

**Comment by guybedford** [comment]
Thanks, this appears to be a SystemJS specific CDN configuration issue, due to a low timeout as it is a very large file. We're looking into updating the CDN configuration to support bigger files.

**Comment by guybedford** [comment]
This has been resolved, thank you for reporting the issue!
