### ISSUE TITLE
JSPM is down

### ISSUE THREAD

**Issue by Aslemammad** [jspm/project#225]
I think JSPM is down.

**Comment by guybedford** [comment]
All ok according to https://status.jspm.io/. Perhaps this is Iran specific?

**Comment by Aslemammad** [comment]
I do not know actually, here's what I see.

![image](https://user-images.githubusercontent.com/37929992/205969049-02d4d315-f9ff-45cf-ba47-955d48f7af64.png)

**Comment by guybedford** [comment]
This is a SystemJS specific issue for large files only, as tracked here https://github.com/jspm/project/issues/224. It does not affect the CDN as a whole.
