### ISSUE TITLE
Build error: @sentry/browser 7.28.1

### ISSUE THREAD

**Issue by xdmx** [jspm/project#233]
It seems it stopped working few versions ago (7.29.0 has also been recently released)

**Comment by guybedford** [comment]
When I try to run it on the generator I get this error:

```
Error: Invalid status code 401 loading https://ga.jspm.io/npm:@sentry/replay@7.28.1/esm/node_modules/rrweb/es/rrweb/packages/rrweb/src/entries/all.js. undefined
```

Is this the issue you mean?

**Comment by xdmx** [comment]
Yes, and also from Rails importmap I get
```
./bin/importmap pin @sentry/browser
Couldn't find any packages in ["@sentry/browser"] on jspm
```

**Comment by guybedford** [comment]
My sincere apologies for the long delay, I've finally traced the issue to https://github.com/jspm/project/issues/240 and have flushed these builds. The newer versions should be working now. Thanks for reporting, and please do report any updates as necessary further.

**Comment by xdmx** [comment]
Hey @guybedford, unfortunately it seems that it's still returning that error (from the generator, as well as not being able to pin that from rails' importmap):
```
Error: Invalid status code 401 loading https://ga.jspm.io/npm:@sentry/replay@7.30.0/esm/node_modules/rrweb/es/rrweb/packages/rrweb/src/entries/all.js. undefined
```

**Comment by guybedford** [comment]
@xdmx sorry for the long delay here, I just checked the latest build and it seems to be working now. Improving unstable builds like this is a priority for this year!
