### ISSUE TITLE
CDN build error for https://ga.jspm.io/npm:@aws-sdk/middleware-endpoint@3.226.0/

### ISSUE THREAD

**Issue by wbugenis** [jspm/project#236]
_Reporting CDN Build Error._

This was a result of trying to generate the importmap for amazon-chime-sdk-js, I believe there are other failing dependencies aside from the specific one here. Building any of the versions from the current (3.10.0) down to 3.7.0 gave similar build errors for different @aws-sdk packages, but 3.6.0, 3.5.0 (and presumably lower versions) work.

**Comment by guybedford** [comment]
Thanks for reporting, and for being patient as well. I finally got the import map to build on this - https://jspm.org/sandbox#H4sIAAAAAAAAA61aXXPaOBR9769Q2Zd2N7KBfGyaQoZst9Ntt7SdzWQ6fdoRtoyV2JYryRC60/++VzIEMI6RHB4SsH3POVfX0tWV0OB5yAO1yCmKVZpcPhusPigJL58hNEipIiiIiZBUDTuFivB5xzxQTCX0smBYxjRJBn55/QDJSEqHnRmj85wL1UEBzxTNgGLOQhUPQzpjAcXm4gixjClGEiwDktBhDwQGfunBYMLDhWF9jjF8IPTh+ssYvaMZFURxgd6nmh+NSW6evg2ZQjf/fLyA9qhcXvj+dGXq3co89Rj3f7npf4q/vfvj7uP4+OZjcPr+R5DE1+P7T2IsvnS7x58X8L133fu8CCef/s6+zXu34273z/HV1V9f51/e3uRXV6CFsXFLBoLlCukQDjvMOJOS3IToP+PR8qbsXCxvwC2Skh88w0HMUopleIdv9ePOg8vkwdcsTy9qrEfHXq/rdf1JwZLQZ1lI7wHSMfw/j0pdGfCcbsnW8G88BoMRmUsciEWuuC9j0j89a/as1n7U97pev+raUb1KoVhiKaBN7bghRn6QMOhuG0FLqZRkyrLpPrlmNES+f3IKoQ+ZVJhKKy+k5A6qYN1WBXMWBm5SBtJOT+3tG9vWjio8i9gUCyp5MqPCSmobovWOT6z1BA3BUZ2HcsFnLKQC02xmpVsP1fr9s6foszS0i/Ej2AN4kLHWDmTM8Y3XkGQ8pG0d0NinewBfAhj9bZ1Ywp/+JmyTSD306XGY0wlm5q5atHVkk8MtIjGRsXVneDB202ASEyHIAk+KKLLLOBWI1uv2bPVSFoYJnRNB8bI8wgnNpiq2UX4U7NbmDRqahTlnmXJUX8Fa68Yc7HW5ZxfyemRr9YRPp87CJai1pqBBISSDoi6kigYKvjk6UMPwBG+UsBrRVYyZX61zygZaV1SW1cMuqnU7JRV26aOKaa/IppllxbmLaq+qSHDnqqkxrRULCBMmsNJyzR1roJu2zu14We2tJhcb6TpcC2Utg2OSQTPsZTdBbprgaU6FWjg1dQfkrKl4wBPjtqXeGuCm9b2gYiGVgE6PzdLOroU1sPa6ud7hcJYtUW6qADB7H1QILnCQEClZxAJiOws04Y0nr6w9iWEMhrpOxxFL9KxmOwfXIx3jAGmOqAKywOzESnPD3lEpZSpe4HIhaiW1CXBbRSp+R7OHMWc1xVUgbpW63niyU9GGbnErROIwLtbWjiqKJXhCJD2z6gYb5qbaPnfT4eFiWSdbryZqgW20zRIBR4Kn9rJrTAvFFjNkHa6FckgjUiRK4lRPfU6R3oW6jUBDslqUWA2NbYTb+DPYmN4DPuChZbG3A3JbNxr4uoqyVlxDWoxQ61XC2tptNjK4QjAwDEhu36o1pEUU1wWoWyet4FrEs1DROZ4IPrdNr1WQ/g3g3G1UGrhbO1cIuxxgikDIWbfSJxIuUiYbtersRz2v5/X38u+fMXaMLZnpDF4rhRJANb+ZRyBGpbtXJYKaqbEYqdoCb9fCe5Z9L1hzUti1tvQ557zx15qKqSWr7mOWrNq0gXX/vp2+8AMOLda/JHXxhCri9X83K7SETaCnlIPLL6kq/EEMq4x/LTaErWW2GKtq5nevw8gYqgp/uXNkkYO2DUen3jHE/5EUEBFID/epReFYsRzBBO/1er4UgR/d51Xaw4Q7qsZ43+rWmlkT1HD3D0ber2E/TFAMQYWdH4aaV3lzctfUo/Vj4HxsfOekeW/c2i9NVOU+4KhecukCOizM5uyu2CqlpbCITklTWl0bj85ghHjHK0yFVCpBSePSwroBJdUuf1Y08ZcGZp469cuLCoWSINPAYJ7rBH/i9Xxz4VF5ViEpyDJlNB9O2DRbzp06tzzcrrKKxqnNOnTAU2Xec8bBnhqIqtwFC5tiAI9H55Cv+6Zug6SdrtJ45dQIQj+frf7rv4FfnmzRB1mWx2/Q22s0hg6dUHQds1RerA7fpCSXKOfJImJJgiIuUGrMJFpqSTRnKuaFQmwDIYvcXLwggKL3Ac0VehNDEUjR+avfXlZO2BC5yAIEb3D4WGOpWTKCLpbaPXjnp9CLlu3eeqRbjQLBpeSCTVk27JCMZ4uUF7JzWW351gmfksUc70GrxvwKvqHykM4bfWDkOrz7IJFestef9HldEiPk++irYIpCOFi2jBmCBSFFMRX0CEEgNTOSFHosATu912ZCCTc7EIoOIkoJNingGc+QiumKpXTaMzKwmpc8oV7Cpy+qbr58vfWuB3553mrgl+fA/gcJ7B6pHyYAAA==

Whether it works is another question too!

Let me know how it goes further.

**Comment by wbugenis** [comment]
Thanks so much for the quick reply and resolution! I was able to pin the package (using importmap-rails) so that's already a good sign, will report back if I run into any issues actually using it in the coming days.
