### ISSUE TITLE
CDN build error for https://ga.jspm.io/npm:typescript@4.9.5/

### ISSUE THREAD

**Issue by shyrz** [jspm/project#249]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
It turns out TypeScript goes over the 10MB build limit on the CDN, I've increased this to 15MB now and the build server is chugging away. It should finish optimizing the TypeScript package sometime later today. We'll see if it works then...

**Comment by guybedford** [comment]
Wow, so for the first time ever in the history of JSPM TypeScript _seems_ to be working....

https://jspm.org/sandbox#H4sIAAAAAAAAA6WVUW/aMBDH3/sprtlLu5EYUDtRGhBdV3Vri1YNsWlPk3EujdckjmynNJv23XdJCNBorabxAFHO55//d+D/+fuBErbIECKbxOM9v3kgD8Z7AH6CloOIuDZoR05uQ3fgVAtW2hjH87R6Bj6r39dbUp7gyHmQuMyUtg4IlVpMCbGUgY1GAT5IgW710gGZSit57BrBYxz16ACf1Qr8hQqKirrvuvQAuJrdTuESU9TcKg0fk5IPU55VqxeBtDD/fDOkemxmhozdNaneD5MlnlTs1bz/Jfp2+e7+/bSri9nPq9m8F11f35vZee/TjVHm+sPFsru4nU+X8zNbDI5ENDgjuutWQozQMrNQNm3kyOr4hGdVU35VGlZB4wxXAQqV2fVGijprbXwtKs2S4SZpcuSdeMcslgu2CVKuU/F+d+pzjFC0tn3MX8Bby5SwyMMQ9QsaJuULE0rjpO91vR5LVYCkw7CFVkuDmtWIUkynzXVDrZIX4FtZk57X8/pMpgE+tlhCF5lVO2msES1uaHZihqbFk6nJUNA/67+wE0wyW7SQajeJqi0x4zbaiVgC2kzU4fdIqfvdtG4wbb5WAs2O8JrRIhuVazKd8rY+D98kTbreW4JvAs/iXJNnlc39C7ZJJvyx19/mNyvri05Xfa/5Lj8+q52g9JqVJ8LFDKYqyGOEWSQTM2wckXgGMhUXoYxjCMkqkyrNwKpJBpbSRiq3ILd2rCTAAadd+CiQrO48oguLMDh5c9gyQW6KVIDRYvRc3Wjc+lzXlPLo2h9TTwNpLGstlVWD0MoYpeWdTEcOT1VaJCo3zrhd+RMTrimVA0NTzGvSBhvvhNJzntjwaU0CYAy+ammR6pfpqkk0rgIaiaixA9Q5QnEwmHEaJAjUUKx6R0GHaneAW6vlIqc1lYKNsKGsfLs6hgagUTF6sbo72Mg4PH3ys/qsnnc0/qo5/AdhwfdxnwcAAA==

Let me know how it goes!
