### ISSUE TITLE
how to handle packages that have multiple files in a subdirectory

### ISSUE THREAD

**Issue by Aaike** [jspm/project#25]
I'm trying to require the jquery-ui source files.  
These files are located in a **ui** subdirectory.

I installed jquery-ui from github:components/jqueryui
That will registry a mapping like this :

    "jqueryui": "github:components/jqueryui@1.11.2"

so i can do this :

    require("jqueryui/ui/position");

now i actually want to be doing the following without specifying the **ui** subdirectory :

    require("jqueryui/position");

for that i have to manually change the mapping to 

    "jqueryui": "github:components/jqueryui@1.11.2/ui"

is there anyway to have jspm install the mapping like that automatically ?
what property override do i have to use for that, or what would be the right approach for a situation like this ?

I used jquery-ui as the example package but i also want to do this for a library that i have.
the files are located in a subdirectory but i want to require them without having to specify the subpath to the files.
i guess ace is another example of such a library.

**Comment by Aaike** [comment]
i think i know what the problem is.
as i understand you should specify the **directories.lib** property in the package.json , then only those files will get copied into the jspm folder instead of the entire repository.

but i was trying to do this with a locally linked package, like :

    jspm install --link github:aaike/mypackage@0.0.1

it seems when i do that it doesn't take the **directories.lib** property into account.

**Comment by Aaike** [comment]
anyway i guess the question still stands : is there anyway to have jspm install a mapping to a package directory with a subdirectory included ? or does the mapping always have to point to the package directory itself

**Comment by guybedford** [comment]
Yes this is what `directories.lib` is for.

`directories.lib` is supported with jspm link, but there was a bug in that that was only fixed in jspm@0.10 I think. Ensure you're running the latest version. Also `directories.lib` is not supported for packages that are set to `registry: 'npm'` simply because npm itself doesn't support this and we need to maintain parity with what is required on npm.

**Comment by guybedford** [comment]
Yes, you can set up internal package maps through the package.json:

```javascript
{
  "map": {
    "./custom-name": "./internal/mapping/target",
  }
}
```

**Comment by Aaike** [comment]
thanks a lot :)
