### ISSUE TITLE
generator.jspm.io produces outdated es-module-shims import (1.5.1)

### ISSUE THREAD

**Issue by zachsa** [jspm/project#259]
https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hqEosKnIw0DPTMwQArVL7dRkA

**Comment by Bubblyworld** [comment]
Seems to be hardcoded into the app: https://github.com/jspm/generator.jspm.io/blob/main/src/api.js#L32
Probably the page should be using the `generator.injectHtml` API which automatically does latest lookup for the shim.

**Comment by JayaKrishnaNamburu** [comment]
Did some hacky way in the recent `vite-plugin-jspm` to solve this thing
https://github.com/jspm/vite-plugin-jspm/blob/main/plugin/src/index.ts#L16

**Comment by guybedford** [comment]
There is in fact a PR to update the generator site to use the new CLI in https://github.com/jspm/generator.jspm.io/pull/6. I'm not sure if that PR handles ensuring es-module-shims is always updated.

**Comment by guybedford** [comment]
But a generator bump should be done certainly there!

**Comment by guybedford** [comment]
This should be resolved now with the auto update system in place.
