### ISSUE TITLE
CDN build error for https://ga.jspm.io/npm:@sentry/replay@7.42.0/

### ISSUE THREAD

**Issue by agirling** [jspm/project#260]
_Reporting CDN Build Error._

In troubleshooting I stepped back to @sentry/browser@7.40.0 and @sentry/replay@7.40.0 and was able to import successfully.

**Comment by agirling** [comment]
In troubleshooting stepped back to `@sentry/browser@7.40.0` and `@sentry/replay@7.40.0` and was able to import successfully.

**Comment by guybedford** [comment]
Thanks, this should be working now.
