### ISSUE TITLE
JSPM Core Meeting - 4 May 2023

### ISSUE THREAD

**Issue by guybedford** [jspm/project#271]
### Proposed Agenda

- CLI Update
- Docs Update

### Meeting Details

Time: 9am PST Thursday 4 May 2023 (https://www.timeanddate.com/worldclock/fixedtime.html?msg=JSPM+Core+Discussion&iso=20230504T1700)
Location: Google Meet (ask for an invite if you do not have a link)

**Comment by yowainwright** [comment]
May I have an invite?

**Comment by guybedford** [comment]
@yowainwright you're more than welcome to join, I'll DM you an invite.

**Comment by guybedford** [comment]
@yowainwright you should have got an invite now to your email, just let me know if you didn't get the notification.
