### ISSUE TITLE
CDN build error for https://ga.jspm.io/npm:@loaders.gl/worker-utils@3.4.4/

### ISSUE THREAD

**Issue by kirillrdy** [jspm/project#278]
_Reporting CDN Build Error._

**Comment by kirillrdy** [comment]
maybe duplicate of https://github.com/jspm/project/issues/160 ?

**Comment by guybedford** [comment]
@kirillrdy thanks for posting, was able to fix another issue here - this should be working now.

**Comment by kirillrdy** [comment]
@guybedford  thank you ! I can confirm that issue has been resolved
