### ISSUE TITLE
question(npm.jspm.io): package.json access

### ISSUE THREAD

**Issue by douglasduteil** [jspm/project#28]
Hi @guybedford 

Today the `files` key, in the `package.json` of modules, has the power to exclude the `package.json` itself from the files installed by jspm. 

Example:

- The package `true` with this `.jspm.json` description https://npm.jspm.io/true@0.0.4/.jspm.json as an installed `package.json` https://npm.jspm.io/true@0.0.4/package.json
- The package `source-map` with this `.jspm.json` description https://npm.jspm.io/source-map@0.4.4/.jspm.json doesn't https://npm.jspm.io/source-map@0.4.4/package.json

What do you think about making the `package.json` file always accessible (like it's the standard of  npm module manifests) ?

**Comment by guybedford** [comment]
Thanks @douglasduteil. This support was actually just recently added for npm repos handled in jspm via https://github.com/jspm/npm/commit/4f06729b9e9cdfc9febec71322b68838af573af5.

This change be pushed out to the CDN with the 0.16 release.
