### ISSUE TITLE
Missing https://ga.jspm.io/npm:chart.js@4.3.1/dist/chart.js

### ISSUE THREAD

**Issue by morgoth** [jspm/project#284]
Hi.

The chart.js new version was released recently https://github.com/chartjs/Chart.js/releases/tag/v4.3.1
but it's missing on the jspm.

BTW
Is there somewhere described the process of releasing new version of packages to jspm and why they are not available immediately after release?

**Comment by guybedford** [comment]
Did you try the build request API for this package - https://jspm.org/cdn/api#build-queue-request.

It usually takes a few hours for packages to update on JSPM. Sometimes there are dependency build order issues so things take a bit longer to trigger. I've just triggered the build queue bump on this one, it should be working now. Improving the build queue time is the top active development item right now.

**Comment by morgoth** [comment]
I didn't request the build as I didn't know about such workflow.
Thanks, now it works. I guess some guidance about it on the main page would be helpful.

**Comment by morgoth** [comment]
@guybedford Looks like the same issue again with version 4.3.3.
This time I tried to rebuild it but with no success

**Comment by guybedford** [comment]
@morgoth thanks, should be working now.
