### ISSUE TITLE
undefined is not a function, when using JSPM CDN

### ISSUE THREAD

**Issue by trusktr** [jspm/project#294]
This has an error:

[playground link](https://jspm.org/sandbox#H4sIAAAAAAAAA51W247bNhB991dMVRSbpNbF671knbWxAdo+JUWB9qUo+kBJsxazlKiSlGUn2H/vkJK8si3b2z74wuGZMxeeEXWvE8VLA2ZT4tzjeSmVyVnpLUYA3+gD0Bq1N2sNZBJVjrT2MmNKPQvDJQu+6DIPuAyLMp/Z7YcomAaRz0SZsWByF6Zcm5AXKa4J6jmi53ETQCeyxB3+Ad7eNgEebIiQVUYKtpGVCVGHH2n1ya1shOPZ7ftSpu+Dq0OG8X64pNJG5j4zRvG4MuSwW9S5kAf+FHkS3O6xHIRFgTkW5ix9iyPSm+D6laQNLDO5eE0BAxE618MAK0I+VuI8aQsk1svzeT/xmp+ltCDX28ieql0NcplMIfqlkl8wMZj6OTOoOBNNDr919s+t+TUdOkbZL26Q+CC5FaOtWJwas10ghbgNpuf616Eb3P8i75O2ivBjzNiKS3WqQwfYh6k7oqMZf2E5aj+WRXqC9QVEOV4Hk+N0QtaJYPpUih3k4TqITlEpXOJanSBqAA8TGpRokEFLwVP/pKI6CLFcBe+bZFJcHSFyk/jacd6jPnQdCkAPL3VKjnukDn426xrj11MS+BihG7wTTG7fPhOmd8FlGFdcpM2wBrlMK4FDdKfGY5fPaz2fxydusKNTtXu1/ReZXgV3wc3Q1UqpjLrv59F92Nzyi9Hovn/fN6UvHLK55eFbio+8wJ+bWdXP8KhkDhc27QuH291/83aH/Dvfhz8yrluUBpMhaKOqxFQKQT4Cg+lPoBMsEGpuMtAyRxB8mRleLMfAitRBRkkVI/DCEeQ8TYXztqsVx3oGvr8Y3dus/JYM46VoKmnMLI+5fdo4bmIyWGhuNnOPnhLe4j48BPW9S8m3vokUUs29OuMGPWBkLJp9xwWWD0pJ5FwWZIIIplHkgeZfsVnSImHa+DpjqaznHvWDiHZSurn22vDhfnzq60tesVwDT+ce/XYRJlEE7Wc4uybDXFbEOLCz6GISJ/U0fGlqd6K/ypr6C0u+QncC7mwYxEzzBJQ0zFYOTFGE1AH+BLbmuj2kY4KjcMHWeQ5v1mPYjOHrW5gv4C+7gB9hQoa/DxT2Cy+YEAQmlbFKGFLYRpB8wEgXPpVJZdXZJUC725jpphlR+6DrTV34bvsX3sFn9tRUqqQ00N5bJGZrpjcVQdJNTRZm6PTR6rKmCZR1AL9bRcdK1hqV7rOmsrgw9E1ompB406U/piEAgeZCAwnCzonJGEnW2KbjuhQ84UZs2pnqM3Iz6y3D7X+X3swq4ocPW2OTbWc9UvlHQbkozCUdddfdkqWp7a6dzZypJS8CGnLUJISMFUuacqcMem0G1udKJMlbk8iNrYLedLBISDeJklpvGzQGmqskI/Ug/FNx9bQJBktqk5hB9FJRk4wz9cqBT66VGo07lpglT8tGmm6Qt8eFMQ2QQai0K476syZEirN+2BfvGXx/cxnf3d1+aB+spEonrH8BoZCE3kINAAA=)

```
Uncaught TypeError: r.escape is not a function
```

Here's the same example but using the local node_modules from docs.lume.io (it currently has the same 0.3.0-alpha.19 version of lume installed, see the version logged to console):

[playground link](https://jspm.org/sandbox#H4sIAAAAAAAAA4VW36/aNhR+vvwVZ5mm23aE0FXrVAZok7Y9rXtZX6Zpmpz4QHyvE2e2Q6BV//ce2yEEMAzdC7bPd35/x8kyZwah1LhZJaW1jVlkGVeFmcm2wplQWQLZejJZmkKLxoI9NLhKRNUobSvWJOvJw6fJw0N/YpIFuO1D4rRpk8yyWnH8t1K8lWgyd5xxYWwmao772ZNJpgM+u6XQY37yG5RYYW0j2DP5lRe4MhHzdwEYO94xLVguY2mdA6IJXkD+38h50jsKZ9PK2xH3gDu+n0Unbuo7YUY793upaIkdmDZaPWFhkacVs0hByttJ3NYY22WtVZIdVHunE2NMzxTVFZIZEyNLL4oW4YlVaNJc1TyieRJGdTVuca8jekGQGV1cqvQUSnMs2U4oHYv3CnOne0VrrKpSZq0WeWtJ+2bNItBgySgpePoUC+UoChH43WhsBuk9zQsnWYf5PTiJgzNanJIdxKWtYmw/kwd9t4oYoBro2KyeA/p83fJkw9M3ourPfbM/uNWFQqw4vYBAnyf0t8zCNXp5oQb4egL0CTcpfOK4ETX+GihiPsNGqwoeXYMfPe5c/uLlmfGv0hQ+lML0KAO2RDBWt4VtNYLaAIM3v4ApsEbohC3BqApBim1pRb2dAqu5h0yKNkcQtTdQCc6l13a7ncBuAWm6nixdVGlvDPOtDJmEY1blwpHc2yZLFmsj7GGVzGffJ+tldg0aazdKDLqFkkqvkq4UFhNgdFgHubcFzh40iowLVdMRzOHNfJ6AER8xbGlTMGNTUzKuulVC9SBDZyG9pZiC++zSP9X1FFeu9iD4KqHfo4fX8zn0//HoQoSVasliRLI++iSbVNPsVNRjR/9QHdUXtmKHvgO+NwzoCS4K0MoylzkwTR64B/wFbC9M36RbhCN3s0F5BS/2UzhM4eNLWK3hb7eBb+E1HfxzxbDfRM2kJDCxjLXSEsMOkugDVnn39B7ROnYeAyDp4JMfpn7lppfeGaD/ZK+GJbyC9+w5ZKqVstBfl0Rmd0wPO0nU5bbMSvT86HnZ0f2puhn86Rida9UZ1GZslav60dI3oWlC8sMx/CkNAUi0jwaIEG5ObMmIstYVHfeNFIWw8tDP1NiisIvRNhvWPryFY8Q3Pw6HIdrj6Y3Mf5YUi8ZKUauP1W0Y5666bjYrpreintGQI72+FSWrtzTlnhn0sAQ2tlUoorchkluXBT2IsS6IN4VWxgwFmgLNVVESexD+a4V+PsyiKfVBLGB+yigE449G6cDvvpQGrW9LzornbaCmH+ShXZjTAFmE1vjkqD57QnBcjN2etBfw9dvv8nfvfgj+/aXqifUFRAsM5MoKAAA=)

Just to double check, JSPM's importmap is getting 1.6.0:

https://ga.jspm.io/npm:regexr@1.6.0/index.js

And the one from docs.lume.io is currently the same version:

https://docs.lume.io/node_modules/regexr/package.json

```js
{
    "name": "regexr",
    "version": "1.6.0",
```

Search for `r.escape` in this file:

https://docs.lume.io/node_modules/regexr/src/index.js

**Comment by trusktr** [comment]
Ah, looks like JSPM picks `regex@1.6.0/index.js` (the non-ESM file, which has the CommonJS `default` export discrepancy), while my importmap is mapping to `regexr@1.6.0/src/index.js` (the actual ESM file).

Looks like this could be solved with an override, but regexr 2.0 is already out, published as ESM and `type:module`, so a better fix is to get the depedency updated in Lume.

**Comment by trusktr** [comment]
I thought a workaround would be to manually change the generated importmap to point to the `src/index.js` ESM file, but apparently JSPM does not expose that file. This link is 404:

https://ga.jspm.io/npm:regexr@1.6.0/src/index.js

[playground link](https://jspm.org/sandbox#H4sIAAAAAAAAA51XS3PbNhC+61ds2ek4SUVSsvyIFEvjzKQ9ZOJOZtxLp9MDSKxF2CDBAqAeyfi/ZwGSsmQ924MeWCy+/XaxCyxuTKpFaScdgDiGe6s0gs0QlBZTUTAJqSqMkgjMAIOpVAnJZkwLlpAwwQe34PP91zvIvEaasSIlCAVqhloLjiAsqALmouBqHkFmbWlGcTwVNquSKFV5/GjKPC61esTUxsKYCk18PjwnSs64XVEYtyCNoHMTt+w7N/U/sMsSx4HIS6VtzsrAOfadPgCN0ASjRkAiWeVI42BFikWOTCRUXJT5yE3f9qJB1AuZLDMW9YcxF4ZIFhwXpBp4oOdubcCkqsQN/B24a9OkcOtMxKyySrKlqmxMrn+k0Rc/chb2s3u9lpi+jy62EbqvzaWVsSoPmbVaJJWlBZtOHTO5tZ4s96PrVyhbZlFijoU9Ct/oEehVdHkiaK2W2Vye4sAOC+3SbQMz0nyo5HHQRpFQz4/zfhJzcRTSKfnY9tyuutFOLJtpxLApIORhzixSgcqaw9dWfteIT4nQPsh153YCb5Frz4qjJltFMnEdDY7Fr9Wu9f4X+DpokxFhghmbCaUPRWhL93bgt2gv40eWowkTVfADqC9KxPEy6u+Hk2qeSmYOUWxVbi+j3iEojVNc6ANAtcJtnwqlFxud7kShs1jw8GBWtSqEdBG9rwlxnO0B8tV4akm/gt5eusuAcRfd6aBe/SjrOSanQ5LyPkBffAeQ/Lw7FwbD6DxOKiF5XbBRrnglcRfcoRLZxAualc/dA7fY3sravN7+S6peRMPoatf1SlQ67ffz3ju/dn3iNeubHr5zfBAF/lbXq3mGB61yOHO0z7ze5vybtxvgP4Uh/JkJ02gZ3xYZq6vUVtTzqAfqdgafwKRYIDUmNgOjcgQpppkVxbQLrOBepZNWCXVBhQfIBefSr3ajmcD5CMJw0rlxrMIGDJOprD2pxSxPhDtxPDYhWSyMsMtxQCdFMLmJt5XWV5dKrNamSio9DuaZsBgAI2FRz3sscHhQKgIXqiAR9GDQ6wVgxDeshzRImbGhyRh1YuOA4kFAG5SuLoPGfPzaPsX1hVeiFiD4OKDf1kK/14Pms5tdzTBXFSHumJm0NgmTYhq/BLXd0T/UnOILUzGr+1y/NwwSZkQKWlnmPAemyQL3Cn8BWwjTbNK+hCNz0WrxGN4surDswre3MJ7A324Av0KfBP9sZdjvrsmWpExZxippKcOWktLHddDOPFdp5bKzJUCzK5t8WZeoO+jWqi5+t/oL7+COPdWeaqUsNHcXJbMTU7ciKXW5zeIMfX40edk26/cuoxOt5ga1WUflqjiz9E3aVCHJsqXfpSIAifbMACVE5R8TzLonAAUdF6UUqbBy2dTUOqKwo7VhvPrv6Y1cRvzyYSWs2bbSPZ5/lMRFY04PkVV0S8a5i66rzZxpeuJEVORo0D9cplTlPjOodQa2juVeHHQyUeicF9TtoHvlsFQrY1YB6gLVVZpR9iD8Wwn9tIx2utSQGEHvxaOajBetuQNffCgNWr8tCUufpnVq+kJebRcmVEAWoTLeOYrPgjQ4jtbNvqwewc9X58lweP2hOVgpK31i/QD0+KzKDg4AAA==)

Here's what we see on unpkg:

https://unpkg.com/regexr@1.6.0/src/index.js

This makes it a bit difficult to perform an immediate workaround.

-----------------

Should JSPM CDN allow fetching different files, like unpkg does, to make workarounds for these sort of situations easy?

Regexr 1.6 doesn't have `type:module` or an `exports` field, so the file not being exposed seems like an arbitrary limitation.

**Comment by guybedford** [comment]
JSPM does not expose all files in a package, only those that are reachable. It is not a direct npm mirror but instead a modular build of npm packages.

Because the package.json `"exports"` field is encapsulating, other files are now non-reachable via `import` in Node.js and other environments.

This same property of non-reachability is also what enables the JSPM package optimizations to apply.

**Comment by trusktr** [comment]
`regexr` 1.6 does not have an `exports` field though:

https://unpkg.com/browse/regexr@1.6.0/package.json

The expecation of publishing a package \*without\* an `exports` field (f.e. to NPM) is that we can simply import any file from that package.

**Comment by guybedford** [comment]
This should be working now if you clear your browser cache.
