### ISSUE TITLE
Include traceur in depcache?

### ISSUE THREAD

**Issue by neothemachine** [jspm/project#30]
I added a depcache config which I use together with the JSPM CDN at http://reading-escience-centre.github.io/leaflet-coverage/ (ignore any errors, just look at the network tab). It works quite well, however I see that traceur kind of blocks before the bulk gets loaded. Is it possible to somehow load traceur in parallel as well?

![timing](https://cloud.githubusercontent.com/assets/530988/10528305/5c5be8ea-738d-11e5-9e56-f0c44daed7a3.PNG)

**Comment by guybedford** [comment]
You shouldn't be loading Traceur itself in production as that would mean production transpilation. Let me know if you have any questions about converting ES6 when not bundling.

**Comment by neothemachine** [comment]
Just found this post from you which explains this nicely: https://github.com/jspm/jspm-cli/issues/872#issuecomment-114946729 I'll close this since optimizing for that case (transpilation in production) would be a waste of time I think.
