### ISSUE TITLE
Importmap Generator: `Failed to load resource: the server responded with a status of 404 ()  ga.jspm.io/npm:james-bond@0.7:1`

### ISSUE THREAD

**Issue by trusktr** [jspm/project#302]
I'm unable to generate an importmap for `lume@0.3.0-alpha.28`, failing with several errors:

https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hyCnNTXUw0DPWM9BNzCnISNQzsgAAoYq6VyIA

```
ga.jspm.io/npm:james-bond@0.7:1
Failed to load resource: the server responded with a status of 404 ()

/#U2VhYGBkDM0rySzJSU1hyCnNTXUw0DPWM9BNzCnISNQzsgAAoYq6VyIA:1
Failed to find a valid digest in the 'integrity' attribute for resource 'https://ga.jspm.io/npm:debug@4.3.4/src/browser.js' with computed SHA-384 integrity 'hPwnb+BEr93FDeQGA/+LX5arBHpwK0TGJV/Bd8+dbE3zSR4XY+SlHu7NQskc47Xe'. The resource has been blocked.

mapapp.js:1
TypeError: e.match is not a function
    at new Semver (sver.js:1:390)
    at Installer.tryUpgradeAllTo (17f28187.js:35:2693)
    at Installer.installTarget (17f28187.js:25:1151)
    at async TraceMap.resolve (17f28187.js:46:2499)
    at async TraceMap.visit (17f28187.js:43:373)
    at async 17f28187.js:43:1203
    at async Promise.all (/index 6)
    at async TraceMap.visit (17f28187.js:43:1148)
    at async Generator._install (17f28187.js:156:1662)
    at async getMap (api.js?1:88:41)
renderMap @ mapapp.js?1:257
```

That last error is odd. There's no `mapapp` in lume on npm, but there is in fact mapapp in lume in the git repo in this folder:

https://github.com/lume/lume/tree/develop/apps

but maybe that's just a coincidence. EDIT: Hah, yeah, just coincidence.

**Comment by trusktr** [comment]
After trying again a few times (after opening devtools, which has network cache disabled, if that has anything to do with it), it worked.

**Comment by guybedford** [comment]
Glad to hear it is working.

If you ever find a CDN reliability bug for `jspm.io`, do report it immediately and I can run some debugging steps with you to provide to our CDN sponsor.
