### ISSUE TITLE
ga.jspm.io: new URLs are 404

### ISSUE THREAD

**Issue by trusktr** [jspm/project#312]
I'm getting 404s for these:

```js
import('https://ga.jspm.io/npm:three@0.155.0/').then(console.log) // 404
import('https://ga.jspm.io/npm:lume@0.3.0-alpha.30/').then(console.log) // 404
import('https://ga.jspm.io/npm:lume@0.3.0-alpha.30/dist/index.js').then(console.log) // 404
```

This is not 404:

```js
import('https://ga.jspm.io/npm:lume@0.3.0-alpha.28/dist/index.js').then(console.log) // ok
```

If you take this [working playground example](https://jspm.org/sandbox#H4sIAAAAAAAAA+VWUW/bNhB+rn/FVcWAZLUs2V4y17aCpE1QtGiSrm7QDUMfaIm22FCiQNJxlKL/fUdScmKnVjKsDxsWRJZ4PH733fHIu/FT34fXJ2cnH44+nn+AV+fHJxD80z/w/YPW+GkiYl0WFFKdcRzXL0qSgxbAOKOaQJwSqaiOvIWe+QPPTmimOT24yO07GQduvFqSk4xG3hWjy0JI7UEsck1zhFiyRKdRQq9YTH07aAPLmWaE+yomnEZdNDAOHIPxVCSlRcUQ4Avg7eT9KbymOZVECwlvMoMPp6SwsycJ03Dx4d0Q/dGFGgbBvFbtfFFF1mEieHbRO0v/eP3y8vg0lOXk5u3kopuWr/Kzj79fLMPj959OX7w8u3mVv5mc/Xaj5kdHz/uXg3P25ggtmJihmbGKJSs0mMhFHrMcMlLYyHy1RCqh8oaVAEV8kVEceytqZMUpL7KhmT4MO/1O6BNepKTTGwQJUzpgeUKvUdWzQN/azoCKRUHX8L+De2caFQ6NiYAstOCkFAvdQGZTFYl18d8ROkLxOys2rNqbBuKF0iLzidaSTReaqg03HrJ6bz0a79W2Vyj3zFJOM0yxB+ErvTWPGlCvUHe24A/DVopuCx+CvWRL9iCkUUK4X2qWZvxdNJ1KSv1Cii801jTxM6KpxBPllr2v5aeV+DGbsA3SutdtAL5H7org1JQ3pf664oM7U+2gP6UpuWJCNnlzT/dwr9MI/gVvLuVPRZ40oN4qIdlfm7abi2XMiWqiWKsc7iOzBihJ5/RaNgA5hcMewvS2wyjBWeI3pkCtctjF5KtuISvbAhWYsvF4PKPtQM3XNky8BGRT0myAWvWKqvncBruk08eDorKDxI8NQHtAGpDsvEnlPZMf0wXjiTtUnUwkC77Jz04Fj8bzqpXfWvWvecaBK0wHrapkwskETq05mKQsU8O6YGK1UlAIXs4Y5zDDSip4QiVMpVgqKhUsmU7xggd2R18tCjvYoXOYkBkeV+jud/q7VVmsqyJRZR6DknG09VAq3wXBV4YVBntQJ/7GlIkSxFIoJSSbszzySC7yMhML5R2su7tWkx2GLchQ+/AzMgNz08BMiqyqx6OWVcF+6JNkmqKjLAe3GpuWBBsjKmkbMEC4mICiBcF2AiEYKpggodBDXz1Y1SsQOeiU1iiOV8eawTYIM4x2uJjvGPO7o7VdGweu3xkHrg9r2T08Oj4+Of6hXZ/SpWvWjJk2GKNVn5ARiVEeQjiyw5SyeaqH0A3Dn0atJ0+mJL6cS7HIkyE8G/T7AxqPbO6hDw6zNTZ+YSuHfRfgqZlzKNJSMWzteOnHQkqsGD43sJiAmGkFjtkVbtkgDD3MxLnZfxxyllMinSQWXMjIqyw6mZmNvP160cyMXuDIZqLlEOMlLYmPeQMEDeZ+IZhpQcPOHuDjrfpOk3gkjysOmFYby11+WaGFcPRxOba0iuky8ro9w+P7VgqBOkxg6vbDEHzz0zfatVOzWRju16laRa8wWQeK3SCnntElSuOBIIlYRt6McEU9wEBSDNymeAMWUqIib0pwB1Y1fOWis2MjFmy696Ocrh22nt/S65PB/mz2w72uYP89Xv+fnF7lt/8fS/CpuAaWIIq4/ltUrOn6eru1DnhDztOcKmXCNNgWOCxiyGVd6mbquIRQPSuvlykWqbsxDwHDvXfn2kIfTAG5vYXNnbytNqJyRwpNDBZEsHPdhnIXogP48/o5MsGReX0eVaq12Vq1DTeVth1g99rDKruDjMzEc7j5PDKVlVNZtFZV7i/XAUXLzhAAAA==) and update it [to this](https://jspm.org/sandbox#H4sIAAAAAAAAA+VWUW/bNhB+rn/FVcWAZLUs2V4y17aCpE1QtGiSrm7QDUMfaIm22FCiQNJxlKL/fUdScmKnVjKsDxsWRJZ4PH733fHIu/FT34fXJ2cnH44+nn+AV+fHJxD80z/w/YPW+GkiYl0WFFKdcRzXL0qSgxbAOKOaQJwSqaiOvIWe+QPPTmimOT24yO07GQduvFqSk4xG3hWjy0JI7UEsck1zhFiyRKdRQq9YTH07aAPLmWaE+yomnEZdNDAOHIPxVCSlRcUQ4Avg7eT9KbymOZVECwlvMoMPp6SwsycJ03Dx4d0Q/dGFGgbBvFbtfFFF1mEieHbRO0v/eP3y8vg0lOXk5u3kopuWr/Kzj79fLMPj959OX7w8u3mVv5mc/Xaj5kdHz/uXg3P25ggtmJihmbGKJSs0mMhFHrMcMlLYyHy1RCqh8oaVAEV8kVEceytqZMUpL7KhmT4MO/1O6BNepKTTD4OEKR2wPKHXqOpZoG9tZ0DFoqBr+N/BvTONCofGREAWWnBSioVuILOpisS6+O8IHaH4nRUbVu1NA/FCaZH5RGvJpgtN1YYbD1m9tx6N92rbK5R7ZimnGabYg/CV3ppHDahXqDtb8IdhK0W3hQ/BXrIlexDSKCHcLzVLM/4umk4lpX4hxRcaa5r4GdFU4olyy97X8tNK/JhN2AZp3es2AN8jd0VwasqbUn9d8cGdqXbQn9KUXDEhm7y5p3u412kE/4I3l/KnIk8aUG+VkOyvTdvNxTLmRDVRrFUO95FZA5Skc3otG4CcwmEPYXrbYZTgLPEbU6BWOexi8g0clJVtgQpM2Xg8ntF2oOZrGyZeArIpaTZArXpF1Xxug13S6eNBUdlB4scGoD0gDUh23qTynsmP6YLxxB2qTiaSBd/kZ6eCR+N51cpvrfrXPOPAFaaDVlUy4WQCp9YcTFKWqWFdMLFaKSgEL2eMc5hhJRU8oRKmUiwVlQqWTKd4wQO7o68WhR3s0DlMyAyPK3T3O/3dqizWVZGoMo9ByTjaeiiV74LgK8MKgz2oE39jykQJYimUEpLNWR55JBd5mYmF8g7W3V2ryQ7DFmSoffgZmYG5aWAmRVbV41HLqmA/9EkyTdFRloNbjU1Lgo0RlbQNGCBcTEDRgmA7gRAMFUyQUOihrx6s6hWIHHRKaxTHq2PNYBuEGUY7XMx3jPnd0dqujQPX74wD14e17B4eHR+fHP/Qrk/p0jVrxkwbjNGqT8iIxCgPIRzZYUrZPNVD6IbhT6PWkydTEl/OpVjkyRCeDfr9AY1HNvfQB4fZGhu/sJXDvgvw1Mw5FGmpGLZ2vPRjISVWDJ8bWExAzLQCx+wKt2wQhh5m4tzsPw45yymRThILLmTkVRadzMxG3n69aGZGL3BkM9FyiPGSlsTHvAGCBnO/EMy0oGFnD/DxVn2nSTySxxUHTKuN5S6/rNBCOPq4HFtaxXQZed2e4fF9K4VAHSYwdfthCL756Rvt2qnZLAz361StoleYrAPFbpBTz+gSpfFAkEQsI29GuKIeYCApBm5TvAELKVGRNyW4A6savnLR2bERCzbd+1FO1w5bz2/p9clgfzb74V5XsP8er/9PTq/y2/+PJfhUXANLEEVc/y0q1nR9vd1aB7wh52lOlTJhGmwLHBYx5LIudTN1XEKonpXXyxSL1N2Yh4Dh3rtzbaEPpoDc3sLmTt5WG1G5I4UmBgsi2LluQ7kL0QH8ef0cmeDIvD6PKtXabK3ahptK2w6we+1hld1BRmbiOdx8HpnKyqksWqsq9xeu0Ry7zhAAAA==), it breaks because of the 404s.

**Comment by trusktr** [comment]
The generator is also unable to generate import maps for new versions of packages:

https://generator.jspm.io/#U2NgYGBkDM0rySzJSU1hyCnNTXUw0DPWM9BNzCnISNQzNgAARIM29iIA

failing with something like "unable to load configuration".

**Comment by trusktr** [comment]
After a few minutes, it started working for https://ga.jspm.io/npm:lume@0.3.0-alpha.30/dist/index.js

I just tried https://ga.jspm.io/npm:lume@0.3.0-alpha.29/dist/index.js and it is 404.

Looks like something in the CDN is flaky right now.

**Comment by guybedford** [comment]
New package publishes can sometimes take a while to appear on JSPM. This is the area of the most development on the CDN at the moment, and we are introducing updates all the time. You can initiate a build queue request from the API and that should usually update the builds fairly quickly. This problem of new packages taking a while will get resolved eventually with the next architecture under development.

**Comment by trusktr** [comment]
Ah ok. I figured that the CDN would keep the request alive while building the package on first access. It seems that this is what other CDNs do, and so the first request to a package takes longer than subsequent requests, but at least doesn't fail. Is that being looked into? I Imagine it very useful because then we can push updates to users without having to wait for packages to exist; just push and refresh user's apps (one unlucky user might get a slow reload, or we can also ensure our CI is the first user to hit new URLs).

**Comment by guybedford** [comment]
To give a brief architecture summary - yes this is exactly how the project was first implemented as an on-demand build application. But then it was built for scale using a build queue system. The build queue has also undergone a bunch of rearchitecting internally. Reintegrating on-demand loads with the build queue is in theory a simple thing to do, and is very much a goal. Development time is going primarily into optimization and cost reduction right now though as the major goal to ensure sustainability of the project. But on-demand loads will happen eventually.
