### ISSUE TITLE
[Generator] Error: Unable to load package configuration for package@version

### ISSUE THREAD

**Issue by trusktr** [jspm/project#316]
Re-opening of https://github.com/jspm/project/issues/216.

It takes a long time for a new packages to be usable, and it makes the Generator seems to not be working correctly. I wonder how many people tried it but then left because because it seemed to not be working.

For me, this is the number one pain point with the generator at the moment.

**Comment by guybedford** [comment]
There is a lot of infrastructure work going on at the moment to improve the build queue times and build architecture and move towards fully on-demand builds. This work is happening already, but thanks for reiterating its importance.

**Comment by trusktr** [comment]
No prob, thanks for the work. Really looking forward to that.

 It's been over 3 hours with this one: https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcMgpzU3VT81JzU3NK3Ew0DM01DMAAFjZa1gjAA

**Comment by guybedford** [comment]
@trusktr I've bumped your build, it should be workign now.

**Comment by trusktr** [comment]
Thanks! It keeps happening with new packages (I'm a publishin'!). So I have to wait each time.

But now that the latest thing I published is available, but it has an error:

https://github.com/jspm/project/issues/320

**Comment by guybedford** [comment]
After a bunch of work, the build queue is now running much more smoothly. Please post if you have any new issues.
