### ISSUE TITLE
bundle.js contains references to files as absolute paths

### ISSUE THREAD

**Issue by egaga** [jspm/project#32]
> node_modules/jspm/jspm.js bundle-sfx app/main.ts bundle.js  --skip-source-maps

outputs the following bundle.js (content of the angular directive omitted).
    
    (function(__moduleName) {
      $__System.register("8", [], function(exports_1) {
        var template;
        return {
          setters: [],
          execute: function() {
            angular.module('Foobar').directive('myDirective', function() {
              // etc
            });
          }
        };
      });
    })("file:///Users/LoginNameInOSX/path/to/my/app/directives/foobar.ts");

Surely it's not intentional to expose local file system to bundle.js.

I'm running jspm 0.16.14 on OSX 10.11.1

Here's the interesting part of config.js:

    System.config({
      baseURL: "",
      defaultJSExtensions: true,
      transpiler: "typescript",
      babelOptions: {
        "optional": [
          "runtime",
          "optimisation.modules.system"
        ]
      },
      typescriptOptions: {
        "noImplicitAny": false,
        "typeCheck": true,
        "tsconfig": false,
        "files": [
          "./app/typedefinitions/heimo.d.ts"
        ]
      },
      paths: {
        "npm:*": "jspm_packages/npm/*",
        "github:*": "jspm_packages/github/*"
      },

      packages: {
        "app": {
          "defaultExtension": "ts",
          "modules": {
            "*.ts": {
              "loader": "ts"
            },
            "*.js": {
              "loader": "ts"
            }
          }
        }
      },

**Comment by guybedford** [comment]
Certainly this shouldn't be the case. I'd suggest not using the `typescript` internal transpiler here and trying https://github.com/frankwallis/plugin-typescript instead which is the recommended workflow. If you still get this then please post back.

**Comment by egaga** [comment]
Hi, I changed to the plugin-typescript, and I still have the same problem.
What I did was:

   * jspm uninstall typescript
   * jspm install ts

Updated config.js to have transpiler: "false"

   * jspm update
   * bundle-sfx --minify --skip-source-maps app/main.ts my-bundle.js

Arguments "minify" and "skip-source-maps" can be left out and the my-bundle.js still contains file:// references.

Here's the full config:

     System.config({
            baseURL: "",
            defaultJSExtensions: true,
            transpiler: "false",
            typescriptOptions: {
                "module": "system",
                "noImplicitAny": false,
                "typeCheck": true,
                "tsconfig": false,
                "files": [
                    "./app/typedefinitions/heimo.d.ts"
                ]
            },
            paths: {
                "npm:*": "jspm_packages/npm/*",
                "github:*": "jspm_packages/github/*"
            },
            registry: "jspm",
    
            packages: {
                "app": {
                    "defaultExtension": "ts",
                    "modules": {
                        "*.ts": {
                            "loader": "ts"
                        },
                        "*.js": {
                            "loader": "ts"
                        }
                    }
                }
            },
    
            map: {
                "angular": "npm:angular@1.4.7",
                "angular-animate": "npm:angular-animate@1.4.8",
                "angular-elastic": "npm:angular-elastic@2.5.0",
                "angular-growl-v2": "npm:angular-growl-v2@0.7.5",
                "angular-route": "npm:angular-route@1.4.8",
                "angular-sanitize": "npm:angular-sanitize@1.4.8",
                "babel": "npm:babel-core@5.8.34",
                "babel-runtime": "npm:babel-runtime@5.8.34",
                "bootstrap-sass": "npm:bootstrap-sass@3.3.6",
                "clean-css": "npm:clean-css@3.4.8",
                "core-js": "npm:core-js@1.2.6",
                "css": "github:systemjs/plugin-css@0.1.19",
                "false": "npm:babel-core@5.8.34",
                "false-runtime": "npm:babel-runtime@5.8.34",
                "jquery": "github:components/jquery@2.1.4",
                "lodash": "npm:lodash@3.10.1",
                "moment": "npm:moment@2.10.6",
                "ngstorage": "npm:ngstorage@0.3.10",
                "scss": "github:mobilexag/plugin-sass@0.0.10",
                "ts": "github:frankwallis/plugin-typescript@2.2.2",
                "ts-runtime": "npm:babel-runtime@5.8.34",
                "twbs/bootstrap": "github:twbs/bootstrap@3.3.6",
                "github:frankwallis/plugin-typescript@2.2.2": {
                    "typescript": "npm:typescript@1.6.2"
                },
                "github:jspm/nodelibs-assert@0.1.0": {
                    "assert": "npm:assert@1.3.0"
                },
                "github:jspm/nodelibs-buffer@0.1.0": {
                    "buffer": "npm:buffer@3.5.2"
                },
                "github:jspm/nodelibs-constants@0.1.0": {
                    "constants-browserify": "npm:constants-browserify@0.0.1"
                },
                "github:jspm/nodelibs-crypto@0.1.0": {
                    "crypto-browserify": "npm:crypto-browserify@3.11.0"
                },
                "github:jspm/nodelibs-events@0.1.1": {
                    "events": "npm:events@1.0.2"
                },
                "github:jspm/nodelibs-http@1.7.1": {
                    "Base64": "npm:Base64@0.2.1",
                    "events": "github:jspm/nodelibs-events@0.1.1",
                    "inherits": "npm:inherits@2.0.1",
                    "stream": "github:jspm/nodelibs-stream@0.1.0",
                    "url": "github:jspm/nodelibs-url@0.1.0",
                    "util": "github:jspm/nodelibs-util@0.1.0"
                },
                "github:jspm/nodelibs-https@0.1.0": {
                    "https-browserify": "npm:https-browserify@0.0.0"
                },
                "github:jspm/nodelibs-os@0.1.0": {
                    "os-browserify": "npm:os-browserify@0.1.2"
                },
                "github:jspm/nodelibs-path@0.1.0": {
                    "path-browserify": "npm:path-browserify@0.0.0"
                },
                "github:jspm/nodelibs-process@0.1.2": {
                    "process": "npm:process@0.11.2"
                },
                "github:jspm/nodelibs-querystring@0.1.0": {
                    "querystring": "npm:querystring@0.2.0"
                },
                "github:jspm/nodelibs-stream@0.1.0": {
                    "stream-browserify": "npm:stream-browserify@1.0.0"
                },
                "github:jspm/nodelibs-string_decoder@0.1.0": {
                    "string_decoder": "npm:string_decoder@0.10.31"
                },
                "github:jspm/nodelibs-url@0.1.0": {
                    "url": "npm:url@0.10.3"
                },
                "github:jspm/nodelibs-util@0.1.0": {
                    "util": "npm:util@0.10.3"
                },
                "github:jspm/nodelibs-vm@0.1.0": {
                    "vm-browserify": "npm:vm-browserify@0.0.4"
                },
                "github:mobilexag/plugin-sass@0.0.10": {
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "querystring": "github:jspm/nodelibs-querystring@0.1.0",
                    "reqwest": "github:ded/reqwest@2.0.5",
                    "sass.js": "npm:sass.js@0.9.4",
                    "url": "github:jspm/nodelibs-url@0.1.0"
                },
                "github:twbs/bootstrap@3.3.6": {
                    "jquery": "github:components/jquery@2.1.4"
                },
                "npm:amdefine@1.0.0": {
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "module": "github:jspm/nodelibs-module@0.1.0",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:angular-animate@1.4.8": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:angular-elastic@2.5.0": {
                    "angular": "npm:angular@1.4.7"
                },
                "npm:angular@1.4.7": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:asn1.js@4.1.0": {
                    "assert": "github:jspm/nodelibs-assert@0.1.0",
                    "bn.js": "npm:bn.js@4.3.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "inherits": "npm:inherits@2.0.1",
                    "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
                    "vm": "github:jspm/nodelibs-vm@0.1.0"
                },
                "npm:assert@1.3.0": {
                    "util": "npm:util@0.10.3"
                },
                "npm:babel-runtime@5.8.34": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:browserify-aes@1.0.5": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "buffer-xor": "npm:buffer-xor@1.0.3",
                    "cipher-base": "npm:cipher-base@1.0.2",
                    "create-hash": "npm:create-hash@1.1.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "inherits": "npm:inherits@2.0.1",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:browserify-cipher@1.0.0": {
                    "browserify-aes": "npm:browserify-aes@1.0.5",
                    "browserify-des": "npm:browserify-des@1.0.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
                },
                "npm:browserify-des@1.0.0": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "cipher-base": "npm:cipher-base@1.0.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "des.js": "npm:des.js@1.0.0",
                    "inherits": "npm:inherits@2.0.1"
                },
                "npm:browserify-rsa@4.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "constants": "github:jspm/nodelibs-constants@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "randombytes": "npm:randombytes@2.0.1"
                },
                "npm:browserify-sign@4.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "browserify-rsa": "npm:browserify-rsa@4.0.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "create-hmac": "npm:create-hmac@1.1.4",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "elliptic": "npm:elliptic@6.0.2",
                    "inherits": "npm:inherits@2.0.1",
                    "parse-asn1": "npm:parse-asn1@5.0.0",
                    "stream": "github:jspm/nodelibs-stream@0.1.0"
                },
                "npm:buffer-xor@1.0.3": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:buffer@3.5.2": {
                    "base64-js": "npm:base64-js@0.0.8",
                    "ieee754": "npm:ieee754@1.1.6",
                    "is-array": "npm:is-array@1.0.1"
                },
                "npm:cipher-base@1.0.2": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "inherits": "npm:inherits@2.0.1",
                    "stream": "github:jspm/nodelibs-stream@0.1.0",
                    "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
                },
                "npm:clean-css@3.4.8": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "commander": "npm:commander@2.8.1",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "http": "github:jspm/nodelibs-http@1.7.1",
                    "https": "github:jspm/nodelibs-https@0.1.0",
                    "os": "github:jspm/nodelibs-os@0.1.0",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2",
                    "source-map": "npm:source-map@0.4.4",
                    "url": "github:jspm/nodelibs-url@0.1.0",
                    "util": "github:jspm/nodelibs-util@0.1.0"
                },
                "npm:commander@2.8.1": {
                    "child_process": "github:jspm/nodelibs-child_process@0.1.0",
                    "events": "github:jspm/nodelibs-events@0.1.1",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "graceful-readlink": "npm:graceful-readlink@1.0.1",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:constants-browserify@0.0.1": {
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:core-js@1.2.6": {
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:core-util-is@1.0.2": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0"
                },
                "npm:create-ecdh@4.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "elliptic": "npm:elliptic@6.0.2"
                },
                "npm:create-hash@1.1.2": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "cipher-base": "npm:cipher-base@1.0.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "inherits": "npm:inherits@2.0.1",
                    "ripemd160": "npm:ripemd160@1.0.1",
                    "sha.js": "npm:sha.js@2.4.4"
                },
                "npm:create-hmac@1.1.4": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "inherits": "npm:inherits@2.0.1",
                    "stream": "github:jspm/nodelibs-stream@0.1.0"
                },
                "npm:crypto-browserify@3.11.0": {
                    "browserify-cipher": "npm:browserify-cipher@1.0.0",
                    "browserify-sign": "npm:browserify-sign@4.0.0",
                    "create-ecdh": "npm:create-ecdh@4.0.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "create-hmac": "npm:create-hmac@1.1.4",
                    "diffie-hellman": "npm:diffie-hellman@5.0.0",
                    "inherits": "npm:inherits@2.0.1",
                    "pbkdf2": "npm:pbkdf2@3.0.4",
                    "public-encrypt": "npm:public-encrypt@4.0.0",
                    "randombytes": "npm:randombytes@2.0.1"
                },
                "npm:des.js@1.0.0": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "inherits": "npm:inherits@2.0.1",
                    "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
                },
                "npm:diffie-hellman@5.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "miller-rabin": "npm:miller-rabin@4.0.0",
                    "randombytes": "npm:randombytes@2.0.1",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:elliptic@6.0.2": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "brorand": "npm:brorand@1.0.5",
                    "hash.js": "npm:hash.js@1.0.3",
                    "inherits": "npm:inherits@2.0.1",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:evp_bytestokey@1.0.0": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0"
                },
                "npm:graceful-readlink@1.0.1": {
                    "fs": "github:jspm/nodelibs-fs@0.1.2"
                },
                "npm:hash.js@1.0.3": {
                    "inherits": "npm:inherits@2.0.1"
                },
                "npm:https-browserify@0.0.0": {
                    "http": "github:jspm/nodelibs-http@1.7.1"
                },
                "npm:inherits@2.0.1": {
                    "util": "github:jspm/nodelibs-util@0.1.0"
                },
                "npm:lodash@3.10.1": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:miller-rabin@4.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "brorand": "npm:brorand@1.0.5"
                },
                "npm:moment@2.10.6": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:os-browserify@0.1.2": {
                    "os": "github:jspm/nodelibs-os@0.1.0"
                },
                "npm:parse-asn1@5.0.0": {
                    "asn1.js": "npm:asn1.js@4.1.0",
                    "browserify-aes": "npm:browserify-aes@1.0.5",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
                    "pbkdf2": "npm:pbkdf2@3.0.4",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:path-browserify@0.0.0": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:pbkdf2@3.0.4": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "child_process": "github:jspm/nodelibs-child_process@0.1.0",
                    "create-hmac": "npm:create-hmac@1.1.4",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2",
                    "systemjs-json": "github:systemjs/plugin-json@0.1.0"
                },
                "npm:process@0.11.2": {
                    "assert": "github:jspm/nodelibs-assert@0.1.0"
                },
                "npm:public-encrypt@4.0.0": {
                    "bn.js": "npm:bn.js@4.3.0",
                    "browserify-rsa": "npm:browserify-rsa@4.0.0",
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "create-hash": "npm:create-hash@1.1.2",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "parse-asn1": "npm:parse-asn1@5.0.0",
                    "randombytes": "npm:randombytes@2.0.1"
                },
                "npm:punycode@1.3.2": {
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:randombytes@2.0.1": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:readable-stream@1.1.13": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "core-util-is": "npm:core-util-is@1.0.2",
                    "events": "github:jspm/nodelibs-events@0.1.1",
                    "inherits": "npm:inherits@2.0.1",
                    "isarray": "npm:isarray@0.0.1",
                    "process": "github:jspm/nodelibs-process@0.1.2",
                    "stream-browserify": "npm:stream-browserify@1.0.0",
                    "string_decoder": "npm:string_decoder@0.10.31"
                },
                "npm:ripemd160@1.0.1": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:sass.js@0.9.4": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "path": "github:jspm/nodelibs-path@0.1.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:sha.js@2.4.4": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0",
                    "fs": "github:jspm/nodelibs-fs@0.1.2",
                    "inherits": "npm:inherits@2.0.1",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:source-map@0.4.4": {
                    "amdefine": "npm:amdefine@1.0.0",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:stream-browserify@1.0.0": {
                    "events": "github:jspm/nodelibs-events@0.1.1",
                    "inherits": "npm:inherits@2.0.1",
                    "readable-stream": "npm:readable-stream@1.1.13"
                },
                "npm:string_decoder@0.10.31": {
                    "buffer": "github:jspm/nodelibs-buffer@0.1.0"
                },
                "npm:url@0.10.3": {
                    "assert": "github:jspm/nodelibs-assert@0.1.0",
                    "punycode": "npm:punycode@1.3.2",
                    "querystring": "npm:querystring@0.2.0",
                    "util": "github:jspm/nodelibs-util@0.1.0"
                },
                "npm:util@0.10.3": {
                    "inherits": "npm:inherits@2.0.1",
                    "process": "github:jspm/nodelibs-process@0.1.2"
                },
                "npm:vm-browserify@0.0.4": {
                    "indexof": "npm:indexof@0.0.1"
                }
            }
        });

**Comment by guybedford** [comment]
Thanks, I've posted https://github.com/frankwallis/plugin-typescript/issues/65 and https://github.com/systemjs/builder/issues/416.

**Comment by frankwallis** [comment]
As of plugin-typescript@2.3.2, __moduleName is not output in build mode.

**Comment by egaga** [comment]
@frankwallis @guybedford Confirmed to work. Thank you!
