### ISSUE TITLE
Supporting JS builds larger than 25MB

### ISSUE THREAD

**Issue by robinboening** [jspm/project#327]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
This is a bit of a tricky one actually, because it's trying to host a 27MB file and the analysis code on the CDN is unable to handle code of that size.

I'd like to solve this properly, but it won't be a simple fix unfortunately.

**Comment by guybedford** [comment]
I finally got this to build using a build deoptimization technique where the large file is left unmodified by the build process. This should be working now.
