### ISSUE TITLE
__dirname in bundled files

### ISSUE THREAD

**Issue by u9520107** [jspm/project#33]
When a module is not bundled, __dirname would have the form "/build/component" for the module "/build/component/test.js".

After bundling however, __dirname would become "http://{hostname}:{port}/build/component".

This creates a bit of a problem for me when I use path.resolve on them. Resolving "http://xxx.com" would end up with something like "/http:/xxx.com/" and end up in a invalid path. 

If I want to resolve to an unbundled module or json, I could just work away with regex.
But if I want to resolve to another bundled module, I have to resolve to the right url including the domain name and port right? It's hard to determine whether or not the module is bundled during the resolution, so I am not sure how to approach this issue.

**Comment by guybedford** [comment]
Thanks, this is actually a bug. I've posted https://github.com/systemjs/builder/issues/419.
