### ISSUE TITLE
CDN build error for @zoom/videosdk v1.10.7

### ISSUE THREAD

**Issue by wbugenis** [jspm/project#330]
When trying to generate an importmap on https://generator.jspm.io/ for @zoom/videosdk v1.10.7, I get the following response - 
`Error: Unable to request the JSPM API for a build of @zoom/videosdk@1.10.7, with error: Unexpected response from the npm registry, it may be having issues!.`

Version 1.10.5 works fine, however. Thanks for your help!

**Comment by guybedford** [comment]
Thanks for sharing, there was an issue with the build API requests. Both the build and the API should be working now.
