### ISSUE TITLE
Build Timeout for a few packages (Milkdown/Remark-parse/Etc)

### ISSUE THREAD

**Issue by joshuaballoch** [jspm/project#332]
Hello! I'm unsure of whether to file a new bug for some timeouts I'm seeing trying to install a couple packages using jspm (via importmaps on a rails app), or under an existing issue. I reviewed the open issues and think this _might_ be related to #240, so please let me know if you'd like to me refile this as a comment on that issue.

# Build Timeout Installing Packages

The main package I was trying to install is [Milkdown Core](https://www.npmjs.com/package/@milkdown/core?activeTab=readme).

I tried installing its dependencies individually, thinking that this might help figure out if this package is building very slowly, or if it's related to a dependency. In turn, I found that the packages [remark-parse](https://www.npmjs.com/package/remark-parse) and [remark-stringify](https://www.npmjs.com/package/remark-stringify) time out.

I've run into this in three ways now:

1. Running `bin/importmap pin remark-parse` in the command line, which hangs and ends with a Timeout error.
2. Opening links for these two packages in browser, on the jspm API. For example, loading remark-parse by the link https://api.jspm.io/generate?install=remark-parse&flattenScope=true and remark-stringify by the link https://api.jspm.io/generate?install=remark-stringify&flattenScope=true.  These requests take a long time and end in a Service Unavailable notice.
3. Trying to install these two packages on the JSPM in-browser generator:

<img width="1278" alt="image" src="https://github.com/jspm/project/assets/538482/d5a083c3-7c16-4e9d-bb3a-a8cd01c60e07">

That last one finally showed an error building micromark-util-decode-numberic-character-reference@2.0.1 (see screenshot above).

Please let me know if I should add more info or refile somewhere. Thanks for the help!

**Comment by guybedford** [comment]
Thanks for posting, the `micromark-util-decode-numeric-character-reference` package was flagged as a spam package as npm has a lot of spam packages with names looking like that. Rebuilding that dependency, these now seem to be working.

Having a better workflow to detect and flag spam-markeed packages would help here in future.
