### ISSUE TITLE
Package Issue - @rhds/elements@1.4.2

### ISSUE THREAD

**Issue by bennypowers** [jspm/project#336]
> Package @rhds/elements@1.4.2 has already been built by JSPM.

> Error: Module not found: https://ga.jspm.io/npm:@rhds/elements@1.4.2/rhds.min.js imported from https://generator.jspm.io/

meanwhile https://unpkg.com/browse/@rhds/elements@1.4.2/

**Comment by bennypowers** [comment]
issue persists after releasing 1.4.3

https://generator.jspm.io/#U2VhYGBiDs0rySzJSU1hcCjKSCnWT81JzU3NKyl2MNQz0TPGKgjn6hdl6CYmJ+cXpWTm56FwdDNSE1NSi/SyigGyGF8oZQA

**Comment by guybedford** [comment]
Syntax errors building files like https://unpkg.com/@rhds/elements@1.4.3/react/elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.js causes the build to not complete properly. We should make sure this works though on the JSPM CDN builder too.

**Comment by bennypowers** [comment]
Nice catch! thank you very much for looking into this. Is there a way for users to query for build errors like this? perhaps an api call that can return any surfaced errors post-build?

**Comment by guybedford** [comment]
Yeah having warnings for build errors could be useful, although it would need to be carefully designed. Perhaps that's more of a separate npm linter kind of tool.

For JSPM itself, we always try to be resilient with errors, so this is still a bug that we should fix.

**Comment by bennypowers** [comment]
the proximal cause was fixed in https://github.com/RedHat-UX/red-hat-design-system/releases/tag/v1.4.5 so i'll close this for now
