### ISSUE TITLE
Importing @web3auth/modal error: 'loglevel' does not provide an export named 'levels'

### ISSUE THREAD

**Issue by sgraphics** [jspm/project#339]
Seems to be coming from a dependent `toruslabs` library line:
```
import n, {levels as o} from "loglevel";
```

**Comment by sgraphics** [comment]
While this error about loglevel seems to be fixed now, the dependency "@web3auth/modal" still fails to resolve. 

Next issue:
`SyntaxError: The requested module '#build/esm/encodePacket.js' does not provide an export named 'encodePacket' (at index.js:1:8)`

**Comment by sgraphics** [comment]
Seems that encodePacket and decodePacket are set to resolve to **empty.js** by the mapping. Why is that?

```
        "#build/esm/decodePacket.js": "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/@empty.js",
        "#build/esm/encodePacket.js": "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/@empty.js",
        "#build/esm/globalThis.js": "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/@empty.js",
        "#build/esm/transports/websocket-constructor.js": "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/@empty.js",
        "#build/esm/transports/xmlhttprequest.js": "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/@empty.js",
```

**Comment by guybedford** [comment]
I was able to go through the remaining cases - this should be working now short of support for unimported `Buffer` call which could be fixed by setting it as a global before the import.

**Comment by sgraphics** [comment]
This is amazing support, thank you!

**Comment by sgraphics** [comment]
This is amazing support, thank you! Issue resolved.
