### ISSUE TITLE
@walletconnect: The requested module 'pino' does not provide an export named 'levels'

### ISSUE THREAD

**Issue by sgraphics** [jspm/project#344]
Was adding **`@web3auth/wallet-connect-v2-adapter`** but got `"The requested module 'pino' does not provide an export named 'levels'"`

The error seems to be originating from @walletconnect package logger@2.1.2 dependency.

Is there something I can do to fix it myself?

**Comment by sgraphics** [comment]
After I tried to ignore this error I get some other error. What might be the cause? Would appreciate any help! Cc. @guybedford 

```Uncaught TypeError: Failed to resolve module specifier "quick-format-unescaped". Relative references must start with either "/", "./", or "../".```

**Comment by guybedford** [comment]
I managed to make some progress on this in

https://jspm.org/sandbox#H4sIAAAAAAAAA+1dWZPbNhJ+969QJg/J1oaijjm9My7ZzsTH2okTezbHyxREQhJmeJkgpZG38t+3AZAUCYFNUpp4XFup2qxH5NdfN65GowGS51+5oZOsI9pbJL735NF5/g8l7pNHvd65TxPScxYk5jS5OEiTmXV6IG8kLPHok6tA/uue2+p3IRIQn14cLBldRWGcHPScMEhoABQr5iaLC5cumUMt+eO7HgtYwohncYd49GIICs5tZcH5NHTXkvUry4J/er3X79+97b2gAY1JEsa9V77g770lkbx76bKkd/XLm8dQniTij217nkP7Nzzy+yy0v37m/DC9DJ/+/MPTZz9fjUbeh8EvZ2cvbj+8cb6/8W8+PHde/HYSTN+mi8tPn7wPz+bPLmdXg9P4zZQcz1//mP5++Pz2hL29HEzjeHz16pb8/nLqntI/vr9bLV5Nrw5fv/nx9burdDj4mdx8/OPy3+vDFXXW/wxvf50/BSMtS5Snd86dmEVJT1T+xQGTxfBJJCv3v7Is2UV+8Di7AJcmohC2E8bUDkKXemzK7Wk6m9EYUAdFmUlR2CDyH2+EJqP+oD8sicbhitM4owChg+8KTSs6HZM0Wdgr4nk0saAFA+ok1nJkEZdECa6yWXpy2h+O+oe2y3iSoZ4r0H9GTxWkT7kvjJI2/alMO+BOGNFKpRhsKN0GwNfTlHmuDWy2Sx0o/Dvi3NJEUNcXgQZzFlD4ZUWi98eTo/6oP7ZrqLKaLFdhVTEN7k1xhapR8dwLp8T7sGC8rVrHYzBUJ8f9I2geI1Gj0iQmAZe914aewENhqugDPIlTRw3GfUxppO9i4J3vCTti+jGlvHXbNFum8daYJIR47NgLwheU23xBRrgJ9aN5Qv0oWesKeBoJe2zGnxWjvJ49TZg3GYiReWTrks+MJZhMyZR6dpzCVOBT8NteRGMOo2MGNfUuhsEaJ2usPBX5yUl/JGo0p1EDrUzVTn04vQFP8h5qn7ijvbRXmHTlNFnQmKb+DYcW8f0wwFRtgSeH/cP+QHlAoYoFLr1DVMRe1JIfkOA2Bv1Re/LkriV3cgfUnewWnaoluex/Z/1hI72IMnzCb20yZZaQQsfMNloOnmz2aalAgZVT3kNbRtBN654lVEy4RmgFi7O51dRaRgEYOUVvw9WAV4HSS0fdSksJPxlvOoZS4tRpaV9fqq5OwY+jzEE49ajtpPFSeGnqRKOj49shpqEsMRnCiBnJ3lzI6jWk8Nk8cE04dBK0hsp4yT+Q/Jkkyu7E6ygJdyBXgij3wifODsxCDOUVM+PR8Q7MSrCJe7wb8xjlbeyFNcRSTmfm0JWoPSWcYowbFPAN+yc2hAbmEanCJiEIs1EUBhDOWNRnSUNkj4jJ8TmSGmv9Nk8IFFlApiwgMRoZ6FgokQh4NhfqyWHJCv9rR66wJXJ1oYl8NIhCbz0cD466qNlIbSnc3EJUiyCXQJWLcKWl3rJIWWn5er1G6o6OjoZn7XRlYKllbJeu1POLzt+OXCBL9oufCO2tO2tJC8gyLfxEaBu8WxVZpjX4tw2YBairrwBLpPCrnrNb7zT0yubeCIsdN/TbKVBYSa9chLpQT97s8HVsyXaz068IHA3RhYGOrZLDhXryFYtajk2BLBGLn/W0dx0G4p0+Du+MwxDWyin3iEgFwYwhltBJHHpeQ3xbLwUrg2ERoombzzf38mxOjf44JK5DOKzjFyQIKBqCImKT4WATiRZ3n6ubuAm5Q2xZ9gI+GY4366HiKq6LOs0x2DYaFoyDYmWUXcP1CG4rW86201WWmBzDhD5U+sT1l+oyrlJE1i5JSDe1upToSXlR83ut1IcRDbxwzgLrJo5QX10nA4uBca66uPMabrRV3Bj21QqB6lFe4cWtKxkNGnSrrGmWWpUpITQlu4WGFeLwKFenojW6FXZWxWiwZHEY+BSfsGqFMmenhspNzZJUk17ShjFpwpcV1QajVcEFJXEypaRDyQoRUDeqrn+bavKGhwH0KSuKwyVzG7LpqKQq6uEuysXuQ4eqrYhJtTtpbRwfiJjUetqpXXP5Fc+3IRieqGshvkOd39L1kngiFxzGZN5hqGqCcl3XadCCF5l36WAKL7xDty4dU4+sLRKx9qoKEVWhnYqVyaYJun6okyl335YdiZMZtUR3aK+vEMkC307q2DzI9hk6KNwI7eDem1aV2+hyuVo69I5ORzmb7mXp6GXynGlXNSuAhStrTkUGpIO+qtwO82JGkAdHnTXngu1U5/u5TfmnCrCyxysuGKOYsoRFl36n/WVdaEvl5dLXtpPrlbeai40SW2rfZTdQpfnGRzfFW1IV5fldxAAyDeOktGxDtOrQyViuQMybmY05awWQE8sg2zQ1ZqvJkjBPLGVlpOFaJI7JGhtbZgHZs0+MHVo00fGhhe6FFhjgEU6hnieNseVqgZGVV8MDbjv1p03bs2WY3CYb2ZtLvkYZNHCJ+/JwQZZSDXSbZBtjDBIgmnMoE9d6pgh6iUjyYAwKIUOagblimk63KACsVEWmw8TggPOzpgy1o8AgXabA2OKvZ2HaibGQ0VlDL8SKJ+/Dun9UVzpxXwzQJT70Krjs5EA9nzi+1UgmQLLlDhEmnsQsmDdyKRiwndXZ1ZguaTzlZNy8cuk0xcyT96H+x/1jeU7D7PnUWSArjZlV7IqgpNvwyUCuIE1lVwcgLJkeiZpPVJjgSDtl8AzJ0NBsCyvXveYWc2HBgvVseV+21bgcb/k6SyLOjWXVjtKVgeDXxtInGU2jnseihGHZoRwiT/ioXTSXLvv5ZZ0wcK1wJnoxJVg+vIKTG37mNtHPGe1zJAnnV6cR9jmOZuTnVrWrYP11Gyx9pnk+ADCNYdZAT2nlGOAZN/HYFBbXHcgEvJYLJjN0Za+TSXw9G8W2sLa4qL5vtWHi6yAh2AEfnUwJ1PKJKKsDm4DXcoEX7EAFaJ0pD4eVf5/HJFqs7VvqOOQWIzaJgTsS7kwJt9KzowYxcJrJ25wzwbTUnTUxa2taMDeVx3RqoTF5m2Vrx9nYEj80ipnY3ZF5FBUksBnmTAxoud4wz1Ez5sHC0AqnNxhlAULi1BkEMZQ4WCoqh8BMP66J5ma7nfzMI5zZVt2lgUxXNsW/FZwspTkSmdPEYoGoWI7OnhWcjBHM89w8jDCzxO0sPWGSXhBeTBkwhagT9fjUUCeSpbEQLWjwWWCyHdc6Hr72pyE6yEqodlxiN9rvxiglDIxJqMZMQuatWEv4rP5qmBf4SjRDlA4sGc52wKVwhWVeFUAOjZqG9IljufEUC/cLjHZ0Q17T+YBir+EqBA2c+/kAKaixMndqqV0EhHoDghByVE2CanSU0pOjQ4xLIZDVAQtgMmHo1JBDsoOs+c9r8xKMcYvE89RvmG/KsGwnxWgeVzkkhh5OKqGkUzf3O0CJ1b9IT+FcOUpWmzkJAajiiSYr99o46zZe9W3zPAYCAWlgBICMxmqLW0rC4UwloGoMs7tjvJlLkYiucmTkEJswltjHU+eOLIZNPNtgZBqSYHX0plWIYsQjfVHgmxkFxwC1kTsL6mP7BBuQXJoOa8+O3qwSS+UwMLYClB1bwZeMXugKp884/ZiifqoKBO6jmpAsA/o0RtdkZRiwHdd0ay+cexCf4pYpSJbGErWXX9LIfObEoTVL0HhxA5LOxdywPguYTzxw1cyxGhPwBjTSsStoFfQ37t3XypQmVNNCAQ02fJ5tRhutTL2EQWztk0QeSGMOSlVCT86gnbKj3CK1J2U1dvX4j8UwzgIjB/Gx0coCI49VwpIC60g6YS5i5oRJu4V1AoU4GYXqQ59g86C9jZkAjJsh+N1aOz22ZGEKcSjFemcFlx2HLzbMRQsZDQ8cbHSL2xmV+FMTjliAhfXi9uREbW+Yo44oDNYwb6fopugGpJai5haIQqhKbQtL5tixxq0XQnJosFJxKN8vzMw4dObUx0JicTvbQTTZ9TGl8bp5x6AME61Ts0b6mDLn1lJD3UoDWOsRqCKU1yQgJy/z6lU8EpjP4njeV0PKSUudgg7TmNf0LZnFaNz/KqGyzTyTqZz6S5xGAqA6j2uqE4ZkEUBaHoVVHzZ3GdDZETkjN/MjUTkr9ukTGiRXgciWSfGUSnMCXYdC45yAL8OjlY1QYwJdh8rNvKYEPY88llhQdzMWc9T6ChBJUInxAtOA2HNSD5BjpDpWeoF63mB+rSI9tB4qwCydK4/TV25o9Aksi1KeQAwu08AIv4aUKcX8WEvpur7BlHCwAaWF+6JeRUAsf/Qp158sSFaUJgFxsAmzwGRZGPGnJdKVGlfKguS08cRDCZU9FolNkiW0OKHuoGdc66mVKMI9i6GaGx14vYKSPKIFQso9dBTSuoag+WRmgREdQnvgVetX+JmQ5gkW5HUD8Qdzy4/ui7816dWCOYuWK/MtrAoczQvrVUyiCGWTgCxDqH5oFJ/wIdhcWYJAcGaUf+bctYx1z+IfVF4c0nz0vNGyzZbGLrbJNj2V3bdq2e6vBTjcnPbb6bzNLm+T+Uu2nHbabvqMDXZtnwwOT8bHRKC1fnX/W5bCu3XYttx3Z3HrSfadK+vM0LsfphlrX6GgDb2dXzJQeq/F5iUD+5t3bY/Hv4U/vaG/bnW0e7TVvydbf0peRlfsJ8zWe31FhDYtP3iNGN6aUe/au7455VS38S907vdS9Gv7rfure/fqw+t77LtbL/PYraXKZJpp+749wvDmiAdum3Jhr236+o/0ZvZy+VCDdI93XdStqPfK1O3fgbTC/l2p+1WqKWr4vx2VZ1k8acW3T6+TJf97VN5XB/p7VO5XqYZ3XF3zRRgnq+tieYaM0R3eFdX4nqhd3rlU2LpPwSvLoc9c6J1ejtXixVifszIrJNe+21CNO73DbPMIyD7G5c3xZVq3adYv1r7xl2tdG7f1ucxrfDvKZ84qtTVcf+CxauaDhFTqYcdDkR3Xq+0B7VH7tV+AOdrTTppFrR4kzep28yRpa92tHsRAhuNu78ps857M+1lDPMCU2vqhEFO17vmS053Swq0S/Q/SBz5Le20d9fsLfUL7HcUWm5TZPmPbcprPwVQL23w6KUOIzU6xDVs+PtPWkO1TM5/BCz/K/1/8d26rh0/EBx8eqQ9c9C7f996GburR3vsF83lPfQGi55OI9/KzdTz7gkT+AQnC14HT47FzUTu2uOVLVosLVrV1XZysq9wT1vagK3IexmzOgosDEsA60Q9TfvBEt7jyBQvFIj9f0cvtfg6182NWLeoV8j2xwY9+xuJfkkC9oqSvPjnQu8h+V+5lhBcGLdk9BZcv5OuZPzAB0mRFWJIZ/O03Lb5b8c0/NryhR/teOP/WzC6Bm0o7t9XHTM5t9ZGV/wFMW/MmfGUAAA==

Main issues were:

* Pino needed an override for the named exports in https://github.com/jspm/overrides/commit/fc4bdf8f37f1a00e469bdcb1ebf021922edac615
* `Buffer` and `global` needed to be set from their imports

With that it seems like it might be working now. Let me know if you need any further help.

**Comment by sgraphics** [comment]
This is great, I now have the entire web3auth stack operational except for one library `@web3auth/coinbase-adapter`. Apparently it is doing `import i from "@coinbase/wallet-sdk"` but *"i is not a constructor"*. I think it should instead do `import { CoinbaseWalletSDK as i } from "@coinbase/wallet-sdk"`

**Comment by guybedford** [comment]
`web3auth/coinbase-adapter` seems to be working for me in this case:

https://jspm.org/sandbox#H4sIAAAAAAAAA91c3XObSBJ/z1/Bal92qxawZNn5ODulJJvaulSc5M6bh3tKDTCSxgaGYwbLylb+9+uZAQRoaJDtLbvuIZERv/51z1dPdzPo7KeIh3KbUWctk/j1s7Pqg5Lo9TPHOUuoJE64Jrmg8nxSyKX7YqJvSCZj+vprqj+jM99c1yIpSej55IbRTcZzOXFCnkqaAsWGRXJ9HtEbFlJXX/zmsJRJRmJXhCSm51NQcOYbC84CHm0160+uCx+O8+Hyy4XzB01pTiTPnX8mit+5IJm++z5i0vn674+voD0yE698f1VBvSuRJR7j/s9fZ5/W//nj7fXvF0f59vL7h8uv03X4bv3lzz8/fP747vjD0Xv/8/cXtx8v2e3n6dfpxeXlhl9eTrfi07++H/1+8e7NR/HfbCZu3rwBna6rzHPORJizTDqqL88nTFuVkAya8hfcLr8Qk1fOX9rOyWJDg2NSyLUfcpYGRFCXRCSTNAfMpDae1FanWfKqX2jx0jvyZn7EhPRjFnhUJD5LI3oL8pPfSpWKCiRz6qc8ogATflAsl22VWh8Mj4/Age+HIp2IkGe00SqL3fVNuP1zULA48pVxEQ2B9AsJr6lUNvY3mqYrllK4cjM1C/PFiTfzjv0eqiDnGwDtmt1WS9MHU9uiGlC7inlAYuGpjhyrNowZLJjFqXfqTf19qh5NMiep0HPNz3gcs3Tl3q7zh1DcwzxsB0xawXUvPawVO96WDTBRYerDmkhJ7AuZU5IIf5nzBNcMuIgEMXWNyOIYFM/8XjLXOuJWuPl8MO3m065fFJnqG5+Jt3ql4koLyeLFkTedeSd+V/KthX4RkIDGfl6A008oeOg4o7mA9beEMfuSgyvI5RZzXy35xXNvduKd1jRmKTepxijnwRUN5WWmOnB2L90tprbqytv6GxLHVLoiusZUWeCLOfjnufHPHb+sFFC5pjktkivh53GGcbeR4JRqt29x+R1qNd4jufXUeOlNvSOUPOUwZ/2wyG+o8EkAU5OE0k94VMQE3ciagoupN4dGKBVdCkSboGE2Ozm9nt5BTS1r418TsQb+b0TA/JfD7Aav2Y80eymJcIf5NpP8QGojhLCuExLewVwlhrBmwXW0RFeWhdcIIawQK9Ekmp4e3cHgWhbhF2sCA3wguRHCWY/vYLASw1lPpof2sBFCWNUKxpy/jVTLtDkFLB7qK2+Gce1QwDT1Xuqdq8dnlFiWHaNtbsBK6zBOEweAbMgh0k4hcnBpwuRAOI2IwQ48LXfgHp2QUhQiJioqVoG4SnByiItgO8FU9ktBqDOttoieEL6jNuckComQLuRnaUpR346ILabg5itHP0ozWC0kSeXIltbwxXR+oCYaDvvKfbTeFg/pyuXyitwQk8KNU9WUWJhWmSC10pcQlvapU/RuGXuMU9eUgODlsE5UCXlEJDlMZVcK5udhamGXhSXsZkXgiiIYp7Qtszh0YgoqBOOpm5CUrPC13ysEK/9ApZLk1xsCZh8yV7tSi0OXhtxQKlMSxi4a5PdI6K6d+/pqCc6graWuM6j/RhUk1H8QMM5HNKGWGdpVWsARFY49cpfeJAeVVbpC45SSADKnhitHVHWh5WSzJXOD8acBLGY6SjfOxxJ5gpdisU4tVWkqckmeky02YewCer48tzReddnpHJ+DNQZYTiCd72MpcmwPqzG606wsbJUWSTCU9zZhOsmZ+buvkjZhdvwSZYL7OlSAiCwPbSalA7ao+7q2NNXBRtDeNAI9LzB5DVCTYKqjzZO2eM5zkkaYvEHosO3IZv9egbBLoAF6czi2yIeQArsBQ22oMb2TrEb46q+3vDiIr5Zpc8biFiOB2yCvxkUvf3XtJW0GHnOsa/R98Osze8+ou8oV3ODLvIWDgbZPfYNSVfdBKgXS4z3v5YEsnKWrQSYDA66XdpsGt8O6xFy2a1doNg7RlvRGlGYJzVdYQ2sM9P5xPYJXokOkik2ujnGy4eqVDd7bjSW4xDGKuYA9bDnt9llpHEO4ybAsv4LAgjyBqa/zl/KrNlUaukMpYo1phkTQizbL0sjly7J6iVI2cDqvs/Vetwp8n4Ixxm4q+/d5CGBhF257QLE5tQ8uQ14rL83BWaMDVmGA5Rhn8ekNwTbbLpWC9zDB/oEuxi6Vxvdx0eUhTHTZwyO2qSSYe+9SGYEeNhUIHcCl4D1MRc4OIAJ0m6cs0JYpwyon2Xrrr6Nrik4ymxQ4XOVjdAFQyY/Qcw3pNcEK30OKDMEITffQMUQ96PMG+PdLZPQG3E5ZNcKqgy2crlBYXbxCoQZqAHhksyrVRYtgCfsyJSGWtVWQBYRs1tBkiSaUg5v2smNRkYZSJdgDYWALp3fWmcW2FZUuS1XgIdCNsIXTO6ptp1nxDDNJ3dYe2TZUayJqtw1u3NSCcAfdJ6J12FpbCqBRVI3RLLbxVAixTQKOTv0GagyTKkEnh/FpiT0+yU0cKclqFGcDX/ablXeNJ14lQs8zEydVMk0SvklxDgDoZWAdvISEbpQHWCBdY8pppg2pvmuxMUrp85M5wlUiesNHloJvY6h3qSC6TWrBmMtvtgIFEy7JV0Uy4LCaMN3bVtOEqTMwgTmuBkr7LlunA0ble6qAgTNVKN1dtqQTMPXhIbdyTjjnPt4Mqy0UA3hKBvgAoEOBnoY2CjQ4TwNohsC2tivcWL6Kzh6vMjHMYxjUVDuxMFwJ2AuErI5FwIpnS4zPiu+dcQo9zKcYjnr8/9VGuubsEUZSg1pPCey5gwmQfNRvGYzOyOZ+J6ON+SqGkACL6yuITtrN863qqxZVwlKWkBgyPha6g6VIC7p322xhTZQ1mIn2yjS85n5kZk50uAxjrjF6opxa7K0R6tjTdslirHu7dJWIjRGi7hGWKVTvJDYYD3qcrdLx9pUCMCOnsPJ6bIzZDeMFbOEUG/kWrnxQW58YsZdEeRpiK0bdLonUny3RjIPhndK0rmdhHdkv1Ou81CGgEGu2ASymsPHXLTbfefroCrXQ+WvOr1FD26Qabqj1n3ZmHlJxv3C95FAxZFToTautokiwE0nqtvZGtj2qc6zt4ANw9be2+EOQJdwYqk83UGWZfd9MmLr1hu3GFEJLLAqxoHUMYesAiEzxMNQAYGhgLVpNY0mmemXDvn9HI5o2EDatHoOqIw/DpbUuFNzFi4ENbCcyWFrrQnWdfI6z6039m9lOUe4WsCymqD2ifaNFLiEiLITkiSnBIOwdpE7FqxJz4/v2k6RdxAT5y/CstcH1cyZboDR0rm/QAyiCPUYIW8AhhURis64NLNMx22LdrFm4Hhmw7mHN/mdr+iYnWYZyaUBpmLlQBFr+h6E58DzkpHGgfbBaM9z3uxLOKJssJxqbBj3AKbjyxBp+Eu4up8ta5bMDGrt/wDKJjFPtafadjlcq4t3TpvuYVx2ofKr2tc5PPlUjdzPwCVt4/MTtK0+IPlULa2fw6AbuHzZ9DKd6p4PA7aF+VHdtOwzW7Me7ZwNz76QsVvAiF80AY4xhrYNSTYMGAqfm+zFViDRGX/egUlPlYOQ3HDEE9as9o4xpHFF6XEP0Sae56s4nYYlJBh/VkM5hjZYto86Nlb25Ozg2SmvnWMfjdgHyvPX/NrBt1XAftfvtZZe/zaTxj7kfOnGy7yjNhg6X0kqE2hKm6pnOgdvQfiXqUYceKTH8zXY9U/9+PDvzzfNv9f78M/OGv/P+0rnQVU7ncs0S4Zj35p2EZMKp6tSifOe+euWeiG0aOiIPz5FzNaZ26grFqsoJ9Xm2zj1lpRPmXAiesxVLzyck5ek24YWYvO5a3Hrn37DoH0dwKrvfQa98KrvDvFfrqJeH0Xfx/6EJNiyN+MYzb3s75+V1615JeG7RUt4zcPX6DY+pF/PVL2RDmCyt+wX7EYJff1XCuwaf+eaXGM588wsR/wMcTIaVOUIAAA==

Let me know how I can hit that `import i` issue you've having if you;re still finding that.

**Comment by sgraphics** [comment]
Thanks for checking so quickly and yea you are right it does not immediately show. Only when actually using new await CoinbaseAdapter().init() does it use the invalid constructor. Is this in scope?

```
  <script type="module">
    import CoreNodelibsBuffer from "@jspm/core/nodelibs/buffer";
    window.global = window;
    window.Buffer = CoreNodelibsBuffer.Buffer;
  </script>
  
  <script type="module">
    import { CoinbaseAdapter } from "@web3auth/coinbase-adapter";
    const adapter = new CoinbaseAdapter({ clientId : "BPi5PB_UiIZ-cPz1GtV5i1I2iOSOHuimiXBI0e-Oe_u6X3oVAbCiAZOTEBtTXw4tsluTITPqA8zMsfxIKMjiqNQ" }); //taken from https://web3auth.io/docs/sdk/pnp/web/adapters/coinbase#helper-sdks-menu example
    await adapter.init(); //Error here!
  </script>

```

**Comment by guybedford** [comment]
Okay, so the above is actually an interop problem, which strictly speaking is a bug in this file:

https://unpkg.com/@web3auth/coinbase-adapter@9.0.2/dist/lib.cjs/coinbaseAdapter.js

In the above it does this:

```js
var CoinbaseWalletSDK = require('@coinbase/wallet-sdk');

// later on

new CoinbaseWalletSDK(...)
```

when the file at `@coinbase/wallet-sdk` is https://unpkg.com/@coinbase/wallet-sdk@4.1.0/dist/index.js and looks like:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoinbaseWalletSDK = void 0;
// Copyright (c) 2018-2024 Coinbase, Inc. <https://www.coinbase.com/>
const CoinbaseWalletSDK_1 = require("./CoinbaseWalletSDK");
exports.default = CoinbaseWalletSDK_1.CoinbaseWalletSDK;
var CoinbaseWalletSDK_2 = require("./CoinbaseWalletSDK");
Object.defineProperty(exports, "CoinbaseWalletSDK", { enumerable: true, get: function () { return CoinbaseWalletSDK_2.CoinbaseWalletSDK; } });
```

which therefore has the shape `module.exports === { default: CoinbaseWalletSDK, CoinbaseWalletSDK }`.

So the fix would be for the consumer to change their code to instead do:

```js
var { CoinbaseWalletSDK } = require('@coinbase/wallet-sdk');
```

or if they are concerned about interop issues to something like:

```js
var CoinbaseWalletSDK = require('@coinbase/wallet-sdk');
if (CoinbaseWalletSDK.CoinbaseWalletSDK)
  CoinbaseWalletSDK = CoinbaseWalletSDK.CoinbaseWalletSDK;
```

I would therefore advise posting an issue to the original repo about this further. If there is no desire to change on their side then we can potentially look into solving this through JSPM-side overrides, but usually we try to avoid that whenever possible.

Let me know if you need any further help at all.

**Comment by guybedford** [comment]
And if they are transpiling ES modules, their transpilation isn't applying the `__esModule` interop pattern correctly where it is supposed to output: `var CoinbaseWalletSDK = require('@coinbase/wallet-sdk').__esModule ? require('@coinbase/wallet-sdk').default : require('@coinbase/wallet-sdk');` kind of thing.

**Comment by sgraphics** [comment]
Bug fixed in https://github.com/Web3Auth/web3auth-web/issues/1967

**Comment by sgraphics** [comment]
Thanks for information, all good now.
