### ISSUE TITLE
[CDN]: `tailwindcss-stimulus-components@6.0.2` timing out on build

### ISSUE THREAD

**Issue by KonnorRogers** [jspm/project#345]
https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hKEnMzCnPzEtJLi7WLS7JzC3NKS3WTc7PLcjPS80rKXYw0zPQMwIAzrlD+DQA

<img width="1728" alt="Screenshot 2024-09-13 at 11 12 36 AM" src="https://github.com/user-attachments/assets/907e3362-7fe8-4196-b28d-e98e7e9216b5">

<img width="1708" alt="Screenshot 2024-09-13 at 11 13 37 AM" src="https://github.com/user-attachments/assets/9376fef8-40d1-4834-a2ed-e03ea87c67d9">

tailwindcss-stimulus-components fails to build. I even made a few requests to the build queue API. It seems to be timing out? I think?

**Comment by guybedford** [comment]
This should be working now, thanks for reporting.

**Comment by guybedford** [comment]
(And I'm going to reprioritise resolving the root cause here as well)

**Comment by excid3** [comment]
https://api.jspm.io/generate?install=tailwindcss-stimulus-components 

Seems to still generate 5.1.1?

```json
{
  "staticDeps": [
    "https://ga.jspm.io/npm:@hotwired/stimulus@3.2.2/dist/stimulus.umd.js",
    "https://ga.jspm.io/npm:tailwindcss-stimulus-components@5.1.1/dist/tailwindcss-stimulus-components.cjs"
  ],
  "dynamicDeps": [],
  "map": {
    "imports": {
      "tailwindcss-stimulus-components": "https://ga.jspm.io/npm:tailwindcss-stimulus-components@5.1.1/dist/tailwindcss-stimulus-components.cjs"
    },
  "scopes": {
    "https://ga.jspm.io/": {
        "@hotwired/stimulus": "https://ga.jspm.io/npm:@hotwired/stimulus@3.2.2/dist/stimulus.umd.js"
      }
    }
  }
}
```

Anything I'm doing wrong in the tailwindcss-stimulus-components package on my end that I can fix?

**Comment by guybedford** [comment]
Thanks for sharing, this was a bug in the latest generator caching update which I've resolved in https://github.com/jspm/generator/pull/382.

The new API deployment is going out now and looks like it's working now.

Please do share if you see any further issues.

**Comment by excid3** [comment]
Awesome, thanks for all your work @guybedford 👍

**Comment by guybedford** [comment]
Happy to help!
