### ISSUE TITLE
CDN build error for @shopify/hydrogen-react@2024.7.6

### ISSUE THREAD

**Issue by bastienrobert** [jspm/project#346]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
This should be working now, although note that they assume the existence of a `process` global, here's an example:

https://jspm.org/sandbox#H4sIAAAAAAAAA41U23LaMBB9z1ds3If0gi2ctCklNkMaaJqLSSZAO+1LR5FFLLAljSQgJpN/r3whE5im7QNopF2dPTp7vMFuLIjJJYXEZGlnJ1gvFMedHYAgowYDSbDS1ITO3EzcllMGDDMp7Yx5ucYBqvZPVzjOaOgsGF1KoYwDRHBDuYVYstgkYUwXjFC33DSAcWYYTl1NcEpD3xYIUMUguBVxXqLuuq5dAM6H1xGcUk4VNkLBWVbgQ4RlGe3HzMD45rJt32OkbiN0t071plpmHhPo1Xh/kPw4/TzrRU2VD1fnw7GfkJPpVX6CzkYXi/HqMIkuiLwetQ5Gl2M5GJ18uI96Z8vI9Ff+Kuodf/n57hNqLY6PbU3XLehBoIli0kChZeiwklWGZanVQ0mtPtROuz6wR12dCMkmOUryWAlL1VUUE2NTnCf++Ik4l1n7hRvd/eb+e++jd4hipg26VWKpqXKlEjFiPKb3XjbVTln2sVHR0URIusHmDyWfhW3Cv8hVVPyWd+D5dVlbtbEFgKb63lVz65yM/i/YsytbkEuhZkZIRISYsb/h1YndppXpoE7f1saqs7P+L34BqtpadLE2IfSHEIl4nlIYJizTULUVbLM1SJHmE5amurbF2hVY55yAViR8iR3VblaiurpA7fqe3/SaVTe3YoUAQJTQWih2x3joYC54nom5djrbjOudNQKhWkMID0D5wnYVBle9/q/+4Fsb9gqbzIlhgu/BIzwePQfZNHbFo3Q1rF/+1j4PvtZ2vCm6BhMlspfdfVRxA0AIvitmqBWPcaiw7aSI7TSiijbAft8WGoOmEttvmILVlsKSmcQeOlZOB7Axit3ObUxwMAldo1SsvbKMnT1apNRLxd3rDZ5vjjZ6HKBq2tjhU07B30I84o4dBQAA
