### ISSUE TITLE
On "editing" config.js files

### ISSUE THREAD

**Issue by adriatic** [jspm/project#36]
This issue extracts the item 3 in https://github.com/aurelia-ui-toolkits/screenshots/issues/14 - problem you proposed to address separately. 

> 1. Edit config.js files by removing **all data that are created by running the `jspm install` command**. As the initial approximation of such edit we can start by removing the whole `map` section, ensuring that the subsequent invocation of `jspm install` (with the newly edited `package.json`) will result with the "good" `config.json` - with no remnants of a year old map settings.
>    <p align=center>
>    <img src="https://cloud.githubusercontent.com/assets/2712405/13448934/cec10cf2-dff4-11e5-9b3f-4a0e9b3bae5a.png"></img>
>    <br><br>
>    </p>

Rather than editing this file (it should really be a read-only file in my opinion, as the complete definition of application needs should be stored in `package.json`), I would like to get your advice how to get the same task done via jspm - something along your initial comment

> This something that can be handled by a variation of jspm clean, so that feature may be best handled by calling into jspm, and tracking an issue in jspm to provide the ability to filter out unused maps when using jspm clean.

**Comment by guybedford** [comment]
From the previous brief discussion, I was suggesting `jspm clean` can be extended to handle the automatic removal of map configurations that are not related to dependencies installed in the package.json, providing a "cleaned" configuration file. The reason for map configuration is to be a version lock that provides the guarantee that the application will install and run predictably. That's enough of a critical priority for a package manager that giving users an option to remove is not something I'd want to encourage.

Let me know if that makes sense? What is the reason you're looking to clean up the map configuration here? Perhaps separating user configuration into a separate configuration file to the version lock file, and then simply choosing not to have `config.js` in version control would be a compromise on what you're after here?

**Comment by adriatic** [comment]
Here is the scoop: I observed that most problems in Aurelia community related to use jspm/systemjs in building Aurelia apps is related to "stale" `config.js`. 

Example: 
1 Start with the building the aurelia app for the first time - where the app is completely defined with `package.json` file. At that time the `config.js` file is generated for the first time (by `jspm`, I presume, to communicate the systemjs loader what this app needs).

2 As the app continues to evolve, the developer keeps editing the `package.json` file and running the sequence
```
jspm install
gulp watch
```

3 As it is very likely that the developer will add more modules to the `package.json` file (modules that were not present in the initial version of `package.json` and continue running the same loop shown above, the content of the `config.js` might not be consistent with `package,json` content, as the developer could have removed some of the modules in `package.json` that were present in the original version of `package.json`

So, I might be just insufficiently informed about how jspm should be used - as I do not believe that you did not consider this above use case (which I encounter very often in the Aurelia chat room discussion. If on the other hand, my workflow is correctly using jspm, I wanted to add a tool that would ensure how the package.json and config.js are consistent.

I am quite curious about your comments to this :-)

**Comment by guybedford** [comment]
This would be entirely in line with the `jspm clean` workflow feature, which is to "resync" the map configuration with the package.json entirely, and remove anything that is not in sync. But map directly relating to what is in the package.json would be left in-tact.

**Comment by guybedford** [comment]
Created https://github.com/jspm/jspm-cli/issues/1822. Let me know how that sounds.

**Comment by adriatic** [comment]
Perfect then - are you saying that `jspm clean` already does what I am describing here - or that it had to be added to jspm?

**Comment by guybedford** [comment]
The feature to prune map configurations is not currently there, so I'm tracking that in the issue above.

**Comment by adriatic** [comment]
Hello Guy

Thanks for giving me the "smoke" signal that you are still alive and around - as these issues were initiated some 720 days ago 😄 

I am still equally interested in pruning the map configuration despite the fact that I forgot that I need it (got into the habit of manually deleting anything in the map object before running jspm.
