### ISSUE TITLE
Are sources of the converter available?

### ISSUE THREAD

**Issue by sgtpep** [jspm/project#39]

**Comment by guybedford** [comment]
I was initially going to open source the converter along with the CDN relaunch, but as there was very little interest I have delayed this.

I'm going to make the conversion available for other tools definitely, and am aiming an open source release of it before the end of the year, it's just not a high priority right now.

**Comment by sgtpep** [comment]
> as there was very little interest
Everyone was busy configuring webpack (kidding).

Thanks you. I'm eager to see it one day. Especially if it will also be available as a cli tool that is able to download npm packages in a format of es6 modules locally.

**Comment by guybedford** [comment]
Yup, the jspm 2 CLI will enable exactly that sort of thing.
