### ISSUE TITLE
npm type-check module not loading from cdn

### ISSUE THREAD

**Issue by hansrwindhoff** [jspm/project#40]
import typeCheck from 'https://dev.jspm.io/npm:type-check@0.3.2/lib/index';
   

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by guybedford** [comment]
Thanks, I've fixed this up.

**Comment by hansrwindhoff** [comment]
Works for me, thanks for all your work!
