### ISSUE TITLE
CDN - importing //dev.jspm.io/firebase fails

### ISSUE THREAD

**Issue by adelespinasse** [jspm/project#41]
I've tried various different imports like:
```
import firebase from 'https://dev.jspm.io/firebase;
import firebase from 'https://dev.jspm.io/firebase@5';
import firebase from 'https://dev.jspm.io/firebase@4';
import '//dev.jspm.io/firebase@5/database';
```
The first load succeeds, but triggers dependencies on other Firebase modules, one of which fails with a 404 eventually. If I'm importing `https://dev.jspm.io/firebase@5`, the URL that fails to load is `https://dev.jspm.io/npm:@firebase/app@0.0.0?dew`.

**Comment by adelespinasse** [comment]
Hmm, also getting a 500 error when I try to import `react-router-dom`. That's a pretty common one, so it makes me wonder if I'm just doing something wrong.

I'm successfully importing `react@16`, `react-dom@16` and `react-hyperscript@3`.

This is in Chrome 68.

**Comment by guybedford** [comment]
Thanks for posting these cases, I can see the replications, looking into them now further and will report back shortly.

**Comment by guybedford** [comment]
Ok I have fixed the react-router-dom issue, tracking down the firebase issue now.

**Comment by guybedford** [comment]
The firebase issue was harder than expected, but it's working now (turned out to be a `'0' || x` fallthrough bug in the version resolution, thanks JavaScript!).

Thanks again for posting, really helps to know when things aren't working.
