### ISSUE TITLE
react-sortable-tree

### ISSUE THREAD

**Issue by eljenso** [jspm/project#42]
Package [react-sortable-tree](https://github.com/frontend-collective/react-sortable-tree) does not work correctly.

Sample code:
```js
import React from "https://dev.jspm.io/react";
import ReactDOM from "https://dev.jspm.io/react-dom";

import SortableTree from "https://dev.jspm.io/react-sortable-tree";

export default class Tree extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      treeData: [{ title: "Chicken", children: [{ title: "Egg" }] }],
    };
  }

  render() {
    return React.createElement(
      "div",
      { style: { height: 400 } },
      React.createElement(SortableTree, {
        treeData: this.state.treeData,
        onChange: (treeData) => this.setState({ treeData }),
      }),
    );
  }
}

ReactDOM.render(
  React.createElement(Tree, null),
  document.getElementById("reactRoot"),
);
```

Console output:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Tree`.
    in Tree
```

Maybe has something to do with `react-sortable-tree` importing cjs by default (see under "Getting started" in Readme)?

**Comment by guybedford** [comment]
Try replacing `React.createElement(SortableTree` with `React.createElement(SortableTree.default`.

Note that this same problem will apply to the above code executing under `--experimental-modules` in NodeJS.

**Comment by eljenso** [comment]
Replacing `SortableTree` with `SortableTree.default` gives me other errors:

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at ScrollingComponent.componentDidMount (index.dew.js:235)
[...]
Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at ScrollingComponent.componentWillUnmount
[...]
The above error occurred in the <Scrolling(List)> component:
    in Scrolling(List) (created by AutoSizer)
[...]
```

**Comment by guybedford** [comment]
I'm not exactly sure what the issue here is, but one cause might be that there are two versions of React running here - 0.15 and 0.16 because react-dnd-scrollzone is resolving to react@0.15 in https://dev.jspm.io/npm:react-dnd-scrollzone@4.0.0/lib/index.dew.js.

The reason for this is that it uses react as a dependency without listing it in the dependencies, so the devDependencies range for react is being used from https://github.com/azuqua/react-dnd-scrollzone/blob/master/package.json#L62. Which exactly gives 0.15 as the react version.

We could possibly disable the devDependencies version range support in jspm, which would allow the latest version of react to be used instead. Will leave this open to track that.

**Comment by eljenso** [comment]
There is an open PR to fix this: azuqua/react-dnd-scrollzone#38, hopefully it will be fixed soon.

Btw, is the code behind dev.jspm.io open source? Would love to look into it.

**Comment by guybedford** [comment]
Nice, seems like that will do it.

I would like to fix it on the jspm side too though.

The main parts of the code are available through the jspm CLI. This is still in private beta though. You can sign up here if you are interested to try it - https://docs.google.com/forms/d/e/1FAIpQLSenR5AjHN2_Ks1pWxaw7YPak4quhHLIrM9Bx3XON4WvaMD9RA/viewform

**Comment by eljenso** [comment]
Yes, you should definitely also fix this on `jspm` since this will not be the only package with such a problem.

**Comment by guybedford** [comment]
@eljenso did you have any other feedback on the CDN? How did you find the speed / reliability?
