### ISSUE TITLE
Support URL resolution

### ISSUE THREAD

**Issue by guybedford** [jspm/project#43]
URLs should be supported natively - eg `import 'https://site.com/url.js`, whereas currently they are rewritten to empty.

**Comment by mantou132** [comment]
Any progress?
I want to publish my project to npm and load it directly from https://dev.jspm.io

**Comment by guybedford** [comment]
Sure, I can aim to look into this next week.

**Comment by guybedford** [comment]
URL imports are now fully supported on the new https://jspm.dev release.
