### ISSUE TITLE
Load from GitHub

### ISSUE THREAD

**Issue by filips123** [jspm/project#48]
Packages from GitHub aren't supported by jspm.io CDN. If any package requires them, its imports will fail.

Can you add support for them?

---

Examples of packages from GitHub:

* https://dev.jspm.io/github:hugomrdias/concat-stream@feat/smaller?dew
* https://dev.jspm.io/github:hugomrdias/ndjson@feat/readable-stream3?dew

Which lead to failing import of my package:

* https://dev.jspm.io/ethavatar

**Comment by guybedford** [comment]
jspm used to support loading packages from GitHub, and this feature could certainly be added back, sure. It would need to be based on enough user interest in such a feature though (for example, we also need to integrate support for eg GitHub Package Registry too!).

**Comment by guybedford** [comment]
Private registry support is something we are looking to offer integrations for as a way to fund the project. https://jspm.org/private-registries In due course this stuff will be made open source but for now I need to focus on paying my own salary.
