### ISSUE TITLE
Question: availability for production use.

### ISSUE THREAD

**Issue by fusionstrings** [jspm/project#49]
Homepage clearly states **Not for Production** but the reason mentioned behind it is

> These workflows are intended for development only as serving 100's or even 1000's of modules is not suitable for production.

Is there any other drawback while using https://unsafe-production.jspm.io for production than huge number of requests?
Primarily around availability and cache / wrong path resolution aspects. 
I am interested in using it for production because then I can serve systemjs, es build and importmap without handling multiple builds. Although above issues are still the concerns.

**Comment by guybedford** [comment]
The CDN server itself is very much optimized and available for production, the concern is exactly just that most published packages aren't optimized. The hope is to eventually get to a place where they are though indeed.

**Comment by fusionstrings** [comment]
Thanks for clarifying. I will take it as **yes** for production use from CDN (availability mainly) perspective. Dependency optimization and tree is responsibility of end users.

**Comment by guybedford** [comment]
Exactly.
