### ISSUE TITLE
Wrong dependency required by react-dom

### ISSUE THREAD

**Issue by itaybiri** [jspm/project#51]
The following url which loads react-dom 16.8.6 requires react 16 (without a minor version) which causes an incompatibility error because react latest version is now 16.9.0.

https://dev.jspm.io/npm:react-dom@16.8.6

**Comment by guybedford** [comment]
The URL for React 16 in jspm will always track the latest React version, since the expires for these URLs are less than for the exact version URLs.

If the version of React was published right at the time you were testing there may have been a short delay of a day before this update reflected.
