### ISSUE TITLE
Import specifier replaced with @empty.dew.js

### ISSUE THREAD

**Issue by azazdeaz** [jspm/project#52]
Hi, thank you for this great project! I run into an issue that i couldn't figure out:

When i load a file with jspm.io which requires:
> `var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault")`

the import specifier will be replaced with @empty.dew.js:
> `import { dew as _emptyDewDew } from "/npm:@jspm/core@1/nodelibs/@empty.dew.js";`
> `...`
> `var _interopRequireDefault = _emptyDewDew();`

Example:
[/npm:@monaco-editor/react@3.0.1/lib/index.dew.js](https://dev.jspm.io/npm:@monaco-editor/react@3.0.1/lib/index.dew.js)
<details>
  <summary>source on npm</summary>
<p>

```js

// /node_modules/@monaco-editor/react/lib/index.js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "DiffEditor", {
  enumerable: true,
  get: function get() {
    return _DiffEditor["default"];
  }
});
Object.defineProperty(exports, "ControlledEditor", {
  enumerable: true,
  get: function get() {
    return _ControlledEditor["default"];
  }
});
Object.defineProperty(exports, "monaco", {
  enumerable: true,
  get: function get() {
    return _utils.monaco;
  }
});
exports["default"] = void 0;

var _Editor = _interopRequireDefault(require("./Editor"));

var _DiffEditor = _interopRequireDefault(require("./DiffEditor"));

var _ControlledEditor = _interopRequireDefault(require("./ControlledEditor"));

var _utils = require("./utils");

var _default = _Editor["default"];
exports["default"] = _default;
```
</p>
</details>

In my understanding, this should only happen if a file has no exports, but it seems like this one has:
[/npm:@babel/runtime@7.8.3/helpers/interopRequireDefault.dew.js](https://dev.jspm.io/npm:@babel/runtime@7.8.3/helpers/interopRequireDefault.dew.js)

**Comment by guybedford** [comment]
This is fixed on the new jspm.dev release.
