### ISSUE TITLE
Bug: JSPM does not transform `export * as name` syntax

### ISSUE THREAD

**Issue by KSXGitHub** [jspm/project#54]
I tried to load https://dev.jspm.io/@tsfun/all. It returns an error.

This is the content of `@tsfun/all/index.mjs`:

```javascript
export * as Function from "@tsfun/function/index.mjs";
export * as Pipe from "@tsfun/pipe/index.mjs";
export * as Option from "@tsfun/option/index.mjs";
export * as Result from "@tsfun/result/index.mjs";
export * as Object from "@tsfun/object/index.mjs";
export * as Array from "@tsfun/array/index.mjs";
export * as Tap from "@tsfun/tap/index.mjs";
export * as Misc from "@tsfun/misc/index.mjs";
```

It seems that jspm did not convert re-export module names to jspm URLs.

**Comment by guybedford** [comment]
Thanks for posting about this issue, I will include the fix in the next CDN deployment soon, and update here when I do, it should be within the next week or so.

**Comment by guybedford** [comment]
This has been updated and is working now. Let me know if you're still having problems though.
