### ISSUE TITLE
Support conversion for p5js

### ISSUE THREAD

**Issue by mushtaq** [jspm/project#56]
I am trying to use p5 as an ES Module with deno, like so:

`deno run https://dev.jspm.io/p5@1.0.0`

I get the following error:

```txt
error: Uncaught ReferenceError: require is not defined
        for (var u = require, i = 0; i < t.length; i++) o(t[i]);
                                                         ^
    at r (https://dev.jspm.io/npm:p5@1.0.0/lib/p5.dew.js:57:58)
    at https://dev.jspm.io/npm:p5@1.0.0/lib/p5.dew.js:64:45
    at https://dev.jspm.io/npm:p5@1.0.0/lib/p5.dew.js:15:7
    at dew (https://dev.jspm.io/npm:p5@1.0.0/lib/p5.dew.js:31:3)
    at https://dev.jspm.io/p5@1.0.0:2:16
```

Is it possible to get around this? Thanks!

**Comment by guybedford** [comment]
Hi @mushtaq it doesn't currently work on this version of jspm unfortunately.

I did just test this out on the next version of jspm though and it is working there. You can load this from `https://jspm.dev/p5@1.0.0`.

Note that this new CDN is in development mode and will change and break still until its public release. Please do not share this link or any public information about it as this work has not yet been announced.

I hope that helps you with your problem at least.

**Comment by mushtaq** [comment]
Ah, got it, thanks!
