### ISSUE TITLE
How to install private npm modules from jspm.io?

### ISSUE THREAD

**Issue by mcuking** [jspm/project#57]
Hello, thanks for the service which help me fetch npm module in browser via jspm.io.

But there are some npm module in our private npm registry, and is there a method to fetch these npm modules via the jspm.io ?

The code below is how I use jspm.io to fetch modules in my project:

const module = await import('https://dev.jspm.io/' + moduleName);

**Comment by guybedford** [comment]
As discussed on Gitter, the goal is to expand on the private registry offering in future here - https://jspm.org/private-registries.
