### ISSUE TITLE
Support dot file dependency as self resolve

### ISSUE THREAD

**Issue by guybedford** [jspm/project#59]
This pattern is being shared recently:

```js
{
  "depenencies": {
    "~": "file:."
  }
}
```

as a way to permit internal self resolution like `require('~/self')`.

Currently jspm won't support this.... it should!

**Comment by Warren0506** [comment]
I need to access my documents

**Comment by guybedford** [comment]
Can you share the exact package / example?

Files starting with dot are supported as is self resolve provided the
exports field includes them if set.
