### ISSUE TITLE
esbuild worker global bug

### ISSUE THREAD

**Issue by guybedford** [jspm/project#60]
When running esbuild from https://jspm.dev/npm:esbuild-wasm@0.5.17!cjs using eg https://jspm.org/sandbox#H4sIAAAAAAAAA4VQy27bMBC86yumvkg2UioP9OLYvuXWU518AE2uLaYSKXBpOUKQfy8pOm6CHHIgsJzZeZD1osACz9x32Eqrd+4l3hP02BgGZwj0QuoYiPGwRef0sY3jYOQyLaaz+qGdCmNPaELXbiaIlTd9QELXsyyaTQwghAjJnrQJzkM5TRGaVHWWZYud0+NZstJmgNHrmXI2SGPJzzarOoLvvJJ2kJxXpjHxecpm9cUtnYdnUrFcQ5c37kaw6fp2xJGNPWBqePKy78mnbnVRRNr5AOLd0bQae+86lE0IPS/rOv2h0DTUZ/rnSXJX3hdFJXm0CtUc6w1eC8T3Wg5g8oNRhDXkSZqLq+AgfdhmskrrQHJ6+vN7+U3Y+0VMyVdZ6vxf8kvsZcsUkbd5bJQruJZE6w5VGby0vHe+KyP5mcvVzlXFZbEqb7FY4K68witi3wOFWI749vrmVxkzvvj8z4B2llLQ27yaF0LJoJqKvP/4OUkVIecTMa3e/wM7Fu4+qAIAAA==, there is a bug with the global reference in the worker code.

**Comment by evanw** [comment]
Sorry about that. I didn't realize that using Function.prototype.toString() could cause issues like this. It's pretty easy to avoid that on my end so I changed my code to avoid doing this and published a new release. Version 0.5.20 of esbuild should not have this problem.

**Comment by guybedford** [comment]
Nice, thanks for spotting this and adding a fix, all seems to work now! That makes sense if it was a toString() call, I suppose that is the nature of it, unless there was something actually wrong in the transform itself.

The only issue now is that the Wasm file no longer reflected in the "exports" field so it's not being included anymore. I think we probably want to just always expose Wasm for packages as this is a very common need and it shouldn't be necessary to list it in the "exports". Will follow up in https://github.com/jspm/project/issues/64.

**Comment by guybedford** [comment]
ESBuild is finally working via eg https://jspm.org/sandbox#H4sIAAAAAAAAA21STY/TMBA9N79iiJCSLsVZVoJD+iGEWAmk7oXu3te13a2r2I5sp21U9b8zttOABAcnzpuZ9+ZNprrL4A4OrlWwoZpvzRm/A/S8lw5cgkCcBeu8cPC4AWV41+D1KGkdEsNZvOOG+b4VsPeqWUXIMStbDwFd5qkojxEAQogP9IJLbywwwwVCsapKZYlia3g/lCy4PILky5wZ7anUwuarRYXgLc6oPlKXUuI1xNMtkVUjWziPB8Gwub0YPW57cFK1TQ+dk/oNYocnS9tW2NBblWUYNtaDcNtONhx21igo9t63rq6qMEPCxbEawh9P1Kmv9+QLeSjmWVZS12sG5RSWK7hkgK618+CEPUomYAn0ROXITZyn1m9SsAzpAIHv5de6/o+kblX9r+ytExKgAjmu0zk+/2ibzkbp12wyEefojYsd7RqPGqJpDBTwAf/5t5ef6+/zbPKKPm7FF+zHahyUm+H6hLOJdE+0hetoZ7BHvKXa7YxVZRKdQfKELt+ER0vCPdx/+lzMIpq2BVFmlDL64AY81Sra1uBtJ/4GdzIWhBcZ89EMbko9aMHNCeblw2jyIoaug67Uctcn8nFcuNmdEtqTsD9Ealy9H89P6zC2RWvF6v3l4K6LKlxxPtdpOSWMerYvw5wMtiOsNZZspeY3aIrEvwFP9bOTeQMAAA==

This would be good to include in the standard sandbox examples...
