### ISSUE TITLE
passport-azure-ad error

### ISSUE THREAD

**Issue by velascopja** [jspm/project#65]
Hi,

I'm trying to figure out how I can use passport and passport-azure-ad with Deno through jspm and, while importing passport seems to work right

```javascript
import * as pkg from 'https://jspm.dev/passport@0.4.1';
console.log('Content:', pkg);
```

outputs

```javascript
Content: Module {
  Authenticator: [Function: Authenticator],
  Passport: [Function: Authenticator],
  Strategy: [Function: Strategy],
  __dew: [Function: dew$3],
  default: Authenticator {
    _key: "passport",
    _strategies: {
      session: SessionStrategy { name: "session", _deserializeUser: [Function: bound ] }
    },
    _serializers: [],
    _deserializers: [],
    _infoTransformers: [],
    _framework: { initialize: [Function: initialize], authenticate: [Function: authenticate] },
    _userProperty: "user",
    _sm: SessionManager { _key: "passport", _serializeUser: [Function: bound ] },
    Authenticator: [Function: Authenticator],
    Passport: [Function: Authenticator],
    Strategy: [Function: Strategy],
    strategies: { SessionStrategy: [Function: SessionStrategy] }
  },
  strategies: { SessionStrategy: [Function: SessionStrategy] },
  Symbol(Symbol.toStringTag): "Module"
}
Process exited with code 0
```

Importing passport-azure-ad in the same way (I don't know if this is the right way to do it)

```javascript
import * as pkg from 'https://jspm.dev/passport-azure-ad@4.2.1';
console.log('Content:', pkg);
```

outputs an error

```javascript
error: Uncaught TypeError: unknown stream type "undefined"
      throw new TypeError("unknown stream type \"" + s.type + "\"");
            ^
    at Logger.addStream (https://jspm.dev/npm:bunyan@1.8.14!cjs:686:13)
    at https://jspm.dev/npm:bunyan@1.8.14!cjs:519:12
    at Array.forEach (<anonymous>)
    at new Logger (https://jspm.dev/npm:bunyan@1.8.14!cjs:518:21)
    at Function.createLogger (https://jspm.dev/npm:bunyan@1.8.14!cjs:1718:10)
    at new getLogger (https://jspm.dev/npm:passport-azure-ad@4.2.1/lib/logging!cjs:9:22)
    at https://jspm.dev/npm:passport-azure-ad@4.2.1!cjs:559:13
Process exited with code 1
```

Any hint on what I'm doing wrong?

Any help would be very much appreciate.

Best regards.

**Comment by guybedford** [comment]
I had a quick look at this and while I can fix this bug with a workaround in for example:

https://jspm.org/sandbox#H4sIAAAAAAAAA5WOwU7DMBBE7/2KvcWRqE0rTkRFOfAJ/IBrLyTIzlq7G4pA/femrUFCiAO3nZ2ZpxlzIVYoTAFF4JkpQzOoFrl37lVKthHfXH++XCDGfusmipjGvbhaarrVeKWIMvr8P8i1szAqzYpGmhV2MOGhEu3jXBK+m/ZHCpn/StVB5veI4kXO1tp/zIxrH/s7u7WbprU64GQyxTkh7B7gcwUQaBJKaBO9VGdhH1sbvIbBfMcE9WnMuKw2pv16AujAdADsFnG8gdtLtTsBIGsBNXABAAA=

unfortunately there is another issue after this once this is solved which is that the cache manager functions are not supported.

I've created the following two issues:

* https://github.com/jspm/jspm-core/issues/10 for the bug you've listed above
* https://github.com/jspm/project/issues/66 for the next bug that comes up with the workaround

Will see if I can try dig into the second one further soon.

**Comment by velascopja** [comment]
Thank you very much Guy!
