### ISSUE TITLE
d3-graphviz not working

### ISSUE THREAD

**Issue by letmaik** [jspm/project#75]
```js
import { graphviz } from 'https://jspm.dev/d3-graphviz@3.0.4';

const dot = '..';
graphviz("#graph").renderDot(dot);
```

The library tries to lazy load some dependency and fails because it loads it from the wrong url:
`http://localhost:8000/graphvizlib.wasm`

Adding `<script src="https://unpkg.com/@hpcc-js/wasm/dist/index.min.js"></script>` as described in the [README](https://github.com/magjac/d3-graphviz) didn't help either, it still tries to load the module.

**Comment by guybedford** [comment]
@letmaik I just tried the following:

```js
import('https://jspm.dev/d3-graphviz@3.0.4').then(x => x.graphviz('#graph').renderDot('..'))
```

but it seems to be the following error:

```js
Uncaught (in promise) TypeError: Cannot read property '__graphviz__' of null
    at Selection.selection_graphviz [as graphviz] (d3-graphviz.js:2200)
    at Module.graphviz (d3-graphviz.js:2156)
    at <anonymous>:1:58
```

which in turn seems to be because selection_graphviz is returning null.

Are you sure this isn't just a usage issue? Or do you have an example that directly shows the wasm error?

**Comment by guybedford** [comment]
Ah I needed a `<div id="graph'>` I see it now.

**Comment by guybedford** [comment]
Here's how you can do it, as per https://github.com/hpcc-systems/hpcc-js-wasm#__hpcc_wasmFolder:

```js
window.__hpcc_wasmFolder = 'https://unpkg.com/@hpcc-js/wasm@0.3.14/dist/'
document.body.appendChild(Object.assign(document.createElement('div'), { id: 'graph' }))
import('https://jspm.dev/d3-graphviz@3.0.4').then(x => x.graphviz('#graph').renderDot('..'))
```

This is where libraries should be using `import.meta.url` in modules to reference the Wasm asset, and `__dirname` or `__filename` for relative references in CommonJS modules. Most don't though yet, so this is the pain point of the day. It could be added in a PR to them though if you felt like it.

**Comment by letmaik** [comment]
Thanks a lot, that work-around is good enough for me at the moment! :)

**Comment by guybedford** [comment]
Great, will close this, but happy to follow up with PR etc instructions for how to do the modular asset location to upstream too.
