### ISSUE TITLE
JSPM_GITHUB_AUTH_TOKEN

### ISSUE THREAD

**Issue by lucasgfavaro** [jspm/project#77]
Hello there, I am using the JSPM_GITHUB_AUTH_TOKEN with a Github PAT. And I am receiving a warning from Github that I should be sending the access_token as a header parameter and not as a query param. It happens when I execute jspm install. 

![GithubAlert](https://user-images.githubusercontent.com/9703223/92978152-58635300-f465-11ea-8fc1-486bfd8525d2.png)

I really don't know how to change it. 

Sorry I am not a front-end expert. Any help would be appreciate. 

Thank you

**Comment by guybedford** [comment]
Hi @lucasgfavaro. Apologies but the version of jspm you are using is many years old and unsupported at this point. It sounds to me like the GitHub authentication used by jspm is now out of date for the current GitHub APIs.

**Comment by lucasgfavaro** [comment]
Thanks @guybedford for the quick reply, just one more question, basically what should we do? Upgrade jspm or move to something else? I am really lost here. 

Thank you

**Comment by guybedford** [comment]
@lucasgfavaro yes you are on completely unsupported software at this point as after years of development on the old CLI I was not able to get financial support, contributors or development assistance from users so it was deprecated and is being replaced entirely.

If you need to just fix the current issue implementing the new authentication scheme in jspm 16/17 core may be a possibility but that work would either need to be done yourself or by someone else.

**Comment by lucasgfavaro** [comment]
I understand @guybedford . Thank you for your time.

**Comment by guybedford** [comment]
No problem, and thanks for understanding. And if someone wants to pick up and maintain those CLI versions I'd be happy to arrange for that.

**Comment by lucasgfavaro** [comment]
Hi Guy, hope you are doing well, long time since we last talk. As you may be aware github is deprecating API authentication through query parameters on May. We already developed the necessary changes to support oauth through request headers but we have a doubt on how to contribute it to the jspm github repo. We are working on branch 0.13. We are already in sync with the last commit 0.13.22. Should we ask you for a PR on that branch? @smgonzalez is working with me with the coding.

Thanks in advance

**Comment by guybedford** [comment]
@lucasgfavaro sure I can gladly review and release a PR against the 0.13 branch. Also if you are interested in co-maintaining let me know as well.

**Comment by lucasgfavaro** [comment]
Great @guybedford! I will let @smgonzalez know just to proceed with the PR. 

Thanks for the prompt response! and the offering :)

**Comment by smgonzalez** [comment]
Hi, @guybedford! How are you? 
I have created the pull request [#133](https://github.com/jspm/github/pull/133) fixing this issue. Please let us know anything you might need.

Thanks for the help!

**Comment by guybedford** [comment]
Hi @smgonzalez - thank you for the PR! I will trust your work here, and if changes are necessary we can do any follow-up PRs. Released the change in 0.13.23. Really nice to see this support landing.

**Comment by smgonzalez** [comment]
Hi @guybedford, hope you are doing well?
Thank you for merging the PR! I have seen that you made further changes, but i see that there is a typo [here](https://github.com/jspm/github/commit/74571655e53b22e16090dbe3f1eb33d3a3a8bc34#diff-35d8b42b726adaa751252eb3ad98a7708f7be5ecf10ea6e637a42988b54d5a76R241)

Let me know if you need something!

**Comment by guybedford** [comment]
Thanks, published an update with the fix. Let me know if you have any other
issues.
