### ISSUE TITLE
Feature request: modulepreload

### ISSUE THREAD

**Issue by gingur** [jspm/project#79]
I like how the module exposes the deep imports needed upfront, like https://jspm.dev/react@16 showing object-assign@major will be needed and importing it immediately. I was wondering if there is a way to get this in a JSON format somehow so these deep imports could potentially be injected into the HTML as a `<link rel="modulepreload">`?

**Comment by guybedford** [comment]
@gingur yes this is very much needed and the CLI tool being released soon comes with this feature to generate these preloads for you. In fact, I'm supposed to be working on just that right now but am having a slow day apparently :)

**Comment by gingur** [comment]
Awesome, feel free to close this then or use to track the update?

**Comment by guybedford** [comment]
It's in so sure will close.
