### ISSUE TITLE
'worker_threads' not found

### ISSUE THREAD

**Issue by brkeejp** [jspm/project#81]
While using Discord.js module with Deno, I got error.
Looks like worker_threads not found on server or something like that.

I know this not npm but just plain missing not fit. Reporting in case.
Link:
https://jspm.dev/npm:@jspm/core@2/nodelibs/worker_threads

**Comment by guybedford** [comment]
It is missing in jspm core yes, and there is a tracking issue for its implementation here - https://github.com/jspm/jspm-core/issues/8.

I was hoping this might be something a new contributor could assist with if interested. Otherwise as per usual I will get to it eventually.
