### ISSUE TITLE
Thoughts on handling duplicate transitive dependencies?

### ISSUE THREAD

**Issue by lewisl9029** [jspm/project#84]
Hi, been following the project for a while, and although it's sad to see the jspm cli sunsetted, it's also really exciting to see all the amazing progress on the jspm CDN!

One thing I was curious about, given that the CDN inlines transitive dependencies, is how the CDN handles shared transitive dependencies, some of which might not play nicely with multiple copies living on the same page (React is the elephant in the room that immediately came to mind).

I went looking for examples, and surely enough, the [Material UI sandbox](https://jspm.org/sandbox#H4sIAAAAAAAAA41UTW+cMBC98ytcLuxKC6x63C6oTdJDD2mjdG9VDw6eLG5sjOxhFVTlv3eMadmuQMkJPO/N13uG/TthKuxbYDVqVUb7ByN65rBXUGhuj7LZbcuIsb2QJyZFEVemQS4bsHG5zylIKbnPoaerrGyR+WpFLHVrLGrexmX0mwqMARfvmD9SwAKvkI5xjdi6XZ7/cq3OBJzygGzOaKkwepk6oCNdcwQruUo7mc9mnBE+brP323wucxDA5bedPNSg4c6akxS08ysFF/NmWnxq2yv+esWRNlPght7vZPX0hrHOqFTnJXoh04Jbl7ZpIzoF5Fmwi917fdmjNZolg9bJh/+gm2+356h3YmJcyjAy3yDYVCPsP5MZgIk47ThDnkBKiOgOu6EyK9hqzYqS/SBZhn2yivZA+KxomAZXoQnp+cg7hZvx6j5Bv2MJSlTwQCMEb4YjhQ/+OcYkdbpW3LmvXMO9PNZIBN1J+uZc6sG04Sd55CjpFZ5b3ohUGwuJd2m9WRhqWmZ+MEF4G5YNY9SywQM8++bXigCGhn0HBeQsH3QL/aKfpM1fVzMLDRmxWpjh0rBpkqZTKrRdEDRQ1kQZNiQtOg9lR8CRddV/Eavk358mWUdrmmy6sn8AA08+mrUEAAA=) exhibits the exact issue that I was afraid of: 

```
The above error occurred in the 
 component:

div
DatePicker@https://jspm.dev/npm:material-ui@0.20.2/DatePicker/DatePicker!cjs:133:34
App
MuiThemeProvider@https://jspm.dev/npm:material-ui@0.20.2/styles/MuiThemeProvider!cjs:81:34

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

Element ref was specified as a string (input) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://reactjs.org/link/refs-must-have-owner for more information. sandbox::
```

(https://jspm.dev/react and Material UI's transitive dependency on react living in the same tree sounds like the culprit here)

Curious if folks have any workarounds in mind? I was thinking it might be possible to make use of import maps to potentially rewire the transitive dependencies to point to the same copy in userland, depending on how the CDN actually performs the inlining (is it literally bundled inline? or is there an import statement in there somewhere that's amenable to rewiring?). But I wanted to start a discussion on how we might be able to offer a more seamless solution from the CDN side that "just works"?

**Comment by guybedford** [comment]
Thanks for the kind words, yes I'm sure I've seen your username before. Very good points and this actually just came up recently in the chat - it seems like the React update has been causing this for a few users.

You can see this dependency in the https://jspm.dev/npm:material-ui@0.20.2/DatePicker/DatePicker!cjs file which contains:

```js
'/npm:react@16!cjs';
```

In Chrome, you can configure an import map with the following here to fix it:

```html
<script type="importmap">
{
  "imports": {
    "/npm:react@16!cjs": "/npm:react@17!cjs"
  }
}
</script>
```

It requires using the Experimental Web Platform Features flag. Or if you're using es-module-shims, this issue is tracking support for these URL -> URL maps - https://github.com/guybedford/es-module-shims/issues/97.

**Comment by guybedford** [comment]
Feel free to join the jspm beta on Discord if you want to discuss this problem further, it would be great to have your input and show you the new work there.
