### ISSUE TITLE
Fully qualified url for map-base option

### ISSUE THREAD

**Issue by joeldenning** [jspm/project#90]
Is it possible to specify a fully qualified URL for `--map-base` cli option? I'd like to do so so that I can run a jspm project on a separate server from the server hosting the HTML file.

Currently, I get the following error:

```sh
~/c/j/p/app1 (main|✔) $ jspm map -o lib/app1.importmap --map-base http://localhost:9001/
err (jspm) Unable to reference mapping @empty at ../../jspm_packages/npm/@jspm/core@1.1.1/nodelibs/@empty.js. The base for the import map must a higher path than its mappings.
```

**Comment by guybedford** [comment]
Thanks for posting - I've transferred this issue to the beta repo to make sure it is captured for the release.
