### ISSUE TITLE
react-hot-toast goober default export

### ISSUE THREAD

**Issue by joelmoss** [jspm/project#96]
react-hot-toast has a dependency on goober, and when importing react-hot-toast:

```js
import toast from 'react-hot-toast'
```

I get an error: `Uncaught SyntaxError: The requested module '/npm:goober@2!cjs' does not provide an export named 'default'`

Goober has no default export, and from what I can see, react-hot-toast does not try to import a default export from goober.

Any ideas? thx.

**Comment by guybedford** [comment]
Thanks for posting, I've posted a PR to the original repo at https://github.com/cristianbote/goober/pull/262.

**Comment by guybedford** [comment]
The original package issue was since merged and the package is working now.
