### ISSUE TITLE
Ordered Upload Batching

### ISSUE THREAD

**Issue by lewisl9029** [jspm/project#98]
Hi there, as described in title, the following module for some reason has a content-type of `application/octet-stream` instead of the appropriate `application/javascript`:

https://jspm.dev/npm:@babel/parser@7!cjs

![image](https://user-images.githubusercontent.com/6934200/112706675-0b742680-8e63-11eb-8f19-1373b6c5e925.png)

As you can see from the screenshot above, every other module in the dependency tree has the appropriate content-type, and this causes the import of `@babel/core` to fail.

**Comment by guybedford** [comment]
@lewisl9029 thanks for posting. I just checked https://jspm.dev/npm:@babel/parser@7!cjs and I'm definitely seeing a application/javascript content type there. Perhaps clear your cache and try again? Perhaps this may have been due to a buggy patch release for Babel, I'm not sure. Let me know.

**Comment by lewisl9029** [comment]
Hmm, I'm getting `application/javascript` too now. Luckily I still have the same devtools session open from yesterday when I was experiencing the same issue. The issue was actually somewhat intermittent, as you can tell from this screenshot:

![image](https://user-images.githubusercontent.com/6934200/112927142-5ee7ae00-90c9-11eb-8fb7-1208a4b2ae76.png)

Note the small number of `application/javascript`'s mixed in with the rest. This makes me still not convinced that the issue is gone for good yet.

Maybe we can get an idea of what happened by comparing the full set of headers. Here's what they looked like:

```
General:
Request URL: https://jspm.dev/npm:@babel/parser@7!cjs
Request Method: GET
Status Code: 200 
Remote Address: 34.120.137.141:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Content-Length, Content-Type, Date, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-Trace
age: 195
alt-svc: clear
cache-control: public, max-age=200
content-encoding: br
content-language: en
content-length: 62
content-type: application/octet-stream
date: Mon, 29 Mar 2021 03:50:24 GMT
etag: "9451dc3091991ee491a572a0d3adc0b9"
expires: Mon, 29 Mar 2021 03:53:44 GMT
last-modified: Sat, 27 Mar 2021 01:17:22 GMT
server: UploadServer
x-goog-generation: 1616802571494616
x-goog-hash: crc32c=20ONiA==
x-goog-hash: md5=lFHcMJGZHuSRpXKg063AuQ==
x-goog-metageneration: 1
x-goog-storage-class: STANDARD
x-goog-stored-content-encoding: br
x-goog-stored-content-length: 62
x-guploader-uploadid: ABg5-Uz3ytIsFNieRdmiTE2XRGK1kpzYaIdXp064835_C-3Z8JlSkAX5fzWxCMnolZm5wbN36BSuelaKaC8IvBwbuaE

Request Headers:
:authority: jspm.dev
:method: GET
:path: /npm:@babel/parser@7!cjs
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
origin: https://automate.lewisl.dev
pragma: no-cache
referer: https://jspm.dev/npm:@babel/core@7.13.10
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: script
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```

Here's one for the `application/javascript` response from today:

```
General:
Request URL: https://jspm.dev/npm:@babel/parser@7!cjs
Request Method: GET
Status Code: 200 
Remote Address: 34.120.137.141:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Content-Type
age: 0
alt-svc: clear
cache-control: public, max-age=200
content-encoding: br
content-language: en
content-length: 62
content-type: application/javascript
date: Tue, 30 Mar 2021 02:36:01 GMT
etag: "9451dc3091991ee491a572a0d3adc0b9"
expires: Tue, 30 Mar 2021 02:39:21 GMT
last-modified: Sat, 27 Mar 2021 01:17:22 GMT
server: UploadServer
x-goog-generation: 1616807842569515
x-goog-hash: crc32c=20ONiA==
x-goog-hash: md5=lFHcMJGZHuSRpXKg063AuQ==
x-goog-metageneration: 2
x-goog-storage-class: STANDARD
x-goog-stored-content-encoding: br
x-goog-stored-content-length: 62
x-guploader-uploadid: ABg5-UyV-DfNLPrpu3fSKKyAALZo5UQWBdfXSYSxITBDsAkS33AzgML6LCGShdDKqHvF85saDtItQa5IL305s56XFp0

Request Headers:
:authority: jspm.dev
:method: GET
:path: /npm:@babel/parser@7!cjs
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
origin: https://automate.lewisl.dev
pragma: no-cache
referer: https://jspm.dev/npm:@babel/core@7.13.10
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: script
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```

Swapping between the two, I found the following notable differences (outside of the content-type obviously):

On the one with application/octet-stream:
```
access-control-expose-headers: Content-Length, Content-Type, Date, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-Trace
x-goog-generation: 1616802571494616
x-goog-metageneration: 1
x-guploader-uploadid: ABg5-Uz3ytIsFNieRdmiTE2XRGK1kpzYaIdXp064835_C-3Z8JlSkAX5fzWxCMnolZm5wbN36BSuelaKaC8IvBwbuaE
```

On the one with application/javascript:
```
access-control-expose-headers: Content-Type
x-goog-generation: 1616807842569515
x-goog-metageneration: 2
x-guploader-uploadid: ABg5-UyV-DfNLPrpu3fSKKyAALZo5UQWBdfXSYSxITBDsAkS33AzgML6LCGShdDKqHvF85saDtItQa5IL305s56XFp0
```

The x-goog-generation and x-goog-metageneration ones look especially suspicious. I'm not familiar enough with Google cloud storage to know what they mean though.

It's also strange that they'd have different access-control-expose-headers, maybe that could also be a clue for how it got there?

**Comment by guybedford** [comment]
@lewisl9029 I've been trying to think about what this might be and my best guess is the following scenario:

* A new version of Babel/parser comes out -> JSPM processes it and hosts it
* There are two "groups" of hosting that apply:
   1. The version redirects like `https://jspm.dev/@babel/parser` pointing to `export * from '/npm:@babel/parser@x.y.z/index.js'`.
   2. The actual exact version code like `https://jspm.dev/npm:@babel/parser@x.y.z/index.js`
* If the version redirect at `https://jspm.dev/@babel/parser` is updated **before** the file at `https://jspm.dev/npm:@babel/parser@x.y.z/index.js` is fully uploaded and finalized with its metadata, then there is a risk of getting partial metadata.

To ensure the update is fully transactional, the version update group must always happen after the exact versions are complete.

At the moment we handle this via a priority system in the upload batching, but it is not absolutely full-proof it is more like a probabilistic uploader.

To fully transactionalize, the upload groups should be numbered and the version groups only uploaded at all after their corresponding exact version groups have finished.

I'm going to leave this issue open to track this further and aim to dive into it next week.

If not the above, the only other thing it could be is some type of upload failure / google cloud metadata propagation delay. But let's fix what we can first.

**Comment by guybedford** [comment]
Moving this over to the original tracking issue at https://github.com/jspm/project/issues/78.
