### ISSUE TITLE
Error loading @material-ui/core with JSPM

### ISSUE THREAD

**Issue by albertocorrales** [jspm/project#99]
I need to use material-ui as in browser module with Single SPA, so I'm using JSPM in order to get SystemJS modules.

However, if I import package @material-ui/core version 4.11.3, it throws the following error when I run it on sandbox:

```
Uncaught (in promise) TypeError: u is not a function
    at _interopRequireWildcard (interopRequireWildcard.js? [sm]:21)
    at Object.execute (elementTypeAcceptingRef.js? [sm]:13)
    at i (s.min.js:1)
    at e (s.min.js:1)
    at s.min.js:1
    at Array.forEach (<anonymous>)
    at e (s.min.js:1)
    at s.min.js:1
    at Array.forEach (<anonymous>)
    at e (s.min.js:1)
```

it seems related to babel runtime dependency

Link to [sandbox](https://jspm.org/sandbox#H4sIAAAAAAAAA7VZUVPbOBB+769Qcy8wg+0YWtrhEiYt5XplCO2Rcr17VGwlFsiST5ITwk3/+61sx8TBdhTCPSSZ2Lvf9628Wq2s3utQBHqREBTpmJ2+6i1/CA5PXyHUi4nGKIiwVET3O6meOO872Q1NNSOnNzz7DXte/r904Tgm/c6MknkipO6gQHBNOEDMaaijfkhmNCBO9ucAUU41xcxRAWak7wNBz8sV9MYiXGSorx0HjRZKk/hidIJGaWJwFWICh5RPUSzClBGFEiInQsaYa7YAXIQZQ2Mp5opIhcY4uENaoC/nvo/2QpIQnjkLjhgdSywXSOXA+8hxMloVSJpopGTQ70RaJ+rE86bYVZkS91YlsUuFx5P4JL90qwbH7nv3yAup0p5yY8rBqnPa83IkA7oM54YHIo5hVMrA0Ec8JiCYMDFHEAfCHIJwigDQ+QgNsziRh77DQxvl4jx0MfoLwZCiuZB3E/B1l/INzTNicMZGx6DrHrl+EUnlTjWkgqzggx8Egr4N0WfCicQawvgSm0FFQ5xkd89DqtHN9eUJKuUsTUs5vwwP/5z+/fnj3adhVy5GDxejGz8KhtHV5fmdXtw9DLujoyv/3Pt62U384dX5w9XVHw8fp2dX8e/+7cX8AxBVH6HJ8n6njINmkmKcZOn8b6ark19UnZPiAlwaxFgTabIzpV4gJIGbG0bxicvgjev7JifIzKU8JPdm/DKCnwc5sQpEQiq8zRQrVkZf9kA8mcJMjAlMGwZTQHlYQcLo7xFVX/LJRR9IaCG9gjZ45/qQAd12VBPMwUZBAQPnM5iOZxEJ7nZWUoWzlCAJPJgz47k7/yOWHXlIJpSTbxKes9SLnfmrcHYSyD2U4HD32AscO9Ip0aBSCzP9vk525q7C2UmgPILpqHcPfAm0He2lEMqmathxZ2i2AqAMieSa/JNSST6RCU6ZfgEhNajPEfSDsjDAcveqVA9rJ0mMb0mgf1AdiVQX04mS3VOlAXcnUS+TSG3gdvISoRQdM3ImuNIyDWDZviY6lXxnbY3IdsIUg6Yy/C4+SIl3L7EVNDsB+oWo9XakZrjSGMPAvRT9GqKlEKjJYvcSn8OsU672VEovmNUcfepU24o18mSQ2/Jk97fiSTVl24aT+eQsh40sAVP3m3GN1cB3/WWvb/6vAynlzGDRF9ICrrQdHLpd930BWl51g9v1OhiK2Cl7zDC0bNFWvAZvXeDyALn0b6GQJBYz20awnmUFYo0oEhCuwwV3oEUMtKM01jSwIGpwHBzBLuwwH8QGk5oRjRZJRDjki5PlvWP24xYSarwgM7ruGy9Pr6dEFLZS5Q51M0PFPEu6Yqtcl763Ns8HjAZ+1z2GB5MBmbkA12qkwlUnYekUBAQQGINvm/W01q1CWWvRLiDM+yYnhX3UVhJWHZtErNq0y5gyMcZsKwG5SxN1fredlBPAt2j7nrjUPeeqRTtxAt2OcpR5IbUN+aNbU9SPFu0CZAqTaoZZSpxJygNNhUXP1O7fNiY15u368gIN4cDu8t5mOjf7Ng3VmlmNnrxBdaCy0qnF8FTMzYIIy1hdMUlEAjXcXNwIWZqaAnXs+g7TKg8kjUPvEWgVHTLAMZ2LDXxpO/Dfuu9a1u+sym8GzMwG/jso1BuwHFjNLPGMqR0mtYh5aWmHqCXmipp8daZSpIkt/rofpAMkRLZgNxGqICLmlapFspemA4igLYjS0ANBAeXTZ2IX3mvomvKFM8eSWwGvWmdL+dFjqVi9t5yIBc/PJeHzenmrd5QvtF8gKl7ZM2ypv73pqobxnGw/zsTWvPm1l/i0XPy/sl4tv82n7tziNyGRhuUWsuak+pL9NPPNTzPc/GX6Xs0b9H1XQ5u5F6P+qTkYUoIRl4npXry//2sD56XAoTkNwUkCWtGEMoLmkmpNzAkJAjxUvNvvFGdBKDsH0kikOkk12ptRjK4FY2lyMUJecdKyeo6yX3dosnZqkEN38rOUXMv6QUjPy8+sel5+lvYf3K850mMbAAA=)

**Comment by guybedford** [comment]
@albertocorrales thanks for posting this issue, I'm looking into the problem, and managed to get it to work with a slight change to the import map generation, then removing one of the scopes here:

https://jspm.org/sandbox#H4sIAAAAAAAAA7VZXVPbOBR9769Qsy8wW9sEysewCROa0k6zsO0QWHb7pthKIpAlVZITsjv973tlOyYOdqIQ9gEY5HvPOVe6uvpqvY1EaGaSoLGJ2dmb1vwPwdHZG4RaMTEYhWOsNDHtRmKG3kkj/WCoYeTsmuDQoL7ByhDVCrLGwo/jmLQbE0qmUijTQKHghnDAmdLIjNsRmdCQeOk/7xDl1FDMPB1iRtpNYGkFmYzWQESzFPWt56H+TBsS9/qnqJ9Ii6sREziifIRiESWMaCSJGgoVY27YDHARZgwNlJhqojQa4PABGYG+XDSbaCcikvDUWXDE6EBhNUM6A95FnpfS6lBRaZBWYbsxNkbq0yAYYV+nSvx7LWOfioDL+DRrutedI//EPwgiqk2g/ZhysGqctYIMyYLOw7nloYhj6JUiMPQBDwgIJkxMEcSBMIcgvDwAdNFHV2mcKEA3MHL9TFyAev2/EHQpmgr1MARffy7f0rwgBm9gdXT2/AO/mUdS+lIOKSfL+eAPAkHfrtBnwonCBsL4EttORVdYpl8vImrQ7fXlKSrkzE0LOb9c7f85+vvzh4ePF/KPm+7hdbd72Lvsyt7lXW86u9i7uJVx7+vgB4uHqvfr7Z38SL8fjcX3o8fR+Xn3dyUuz8+BrDyMNt3bjSIWmsqKsUzz+t9UWyNr1I3TvAGaOjGGHLcZmtAgFIrAxzU9+cyl895vNm1ekIlPeUQebR+mBD/fZcQ6FJKUeOspFqysvnRQApVwQ2MCU4fBNNAB1pA05mZM9ZdsgtF/SOQgvYTWOfabkAV7q1FtMO/WCgoZOHdhSnbHJHzYWkkZzlGCIjAwXeu5Pf8Tlht5RIaUk28KxlmZ2db8ZTg3CeQRynC0few5jhvpiBhQaYSdfl+HW3OX4dwkUD6G6Wi2D3wOtBntpRDapWq4cadorgKgDAl5TX4kVJGPZIgTZl5BSAXqSwTdURaFWG1flaph3SSJwT0JzR01Y5GYfDpRsn2q1OBuJep1EmkVuJs8KbSmA0a6gmujkhCW7mtiEsW31laL7CZMM9hYRjfiXCm8fYktobkJMK9EbTYjtd2VxBg67rXolxAdhUBNFtuX+AxmmXJxT6XNjDnN0edOlVuxWp4UclOe9PtGPImhbNNwUp+MZb+WJWT6cT2uteo0/eZ8v2//XwbS2pvAoi+UA1xh29n39/yTHLRo9cP75ToYidgr9phR5LhFW/DqHPrAFQBy4b+CQpFYTFw3gtUsCxBLRGMB4XpccE/ZU7KnDTY0dCCqcewcwElsP+vEGpOKHh3P5JhwyBcvzXvPnskdJFR4QWbs+e+DLL2eE1E4ShWn1PUMJfM06fLjclX63ruMDxh1mnv+EQxMCmTnArRVSIVWT7JkBAJCCIzBb5f1tNKtRFlpsVpAlO2bvATOURtJWHSsE7Fos1rGiIkBZhsJyFzqqLOvq0k5AXyHbd8zl6pxLlusJpaw29GetpdSm5A/udVF/WSxWoBKYFJNMEuIN0x4aKhw2DOt9l/VJxXmq/VlBRrCgdPlo8t0rvet66olswo92QbVg8pKRw7dUzK3CyIsY1XFRAoJNdw2roUsTG2BOvKbHjM6CySJo+AJaBEdMsCzOxcX+MK20zz0j1es32mVXw+YmnWax1Co12B5sJo54llTN0zqEPPc0g3RKMw1tfnqjZRIpCv+sh+kAyREumDXEepwTOy1qkOyF6YdiGBVEIVhAIJCykcvxM69l9AN5TNvihV3Al60Tpfyg6dSsfhtPhFznp9zwq02LeWrypdky1F6OKi4OXWX+Hy6/b+y3sx/25+qu/9PQiEDyxX0+mn5kvos9c1eBPzsMnqn4gZ61zewTduJUfvMPq5owYjPxGgn3t39rYbzUuDIvihgKUErGlJG0FRRY4h9ZUCAh/K78Ub+noLStxSDRGJkYtDOhGJ0LRhLZK+Pgvy1YvEtYrfq4WHp1j2DbmTvEZmW5ceEVpC9+7SC7FHqP4JrOyasGgAA

I will aim to post a comprehensive fix to the import map generator as soon as I can.

**Comment by albertocorrales** [comment]
Thanks for posting that solution @guybedford . I've tested it to render a button and it worked. However, I see some issues when I try to use some elements, like makeStyles. 

For that case I'm seeing error: 

`Uncaught SyntaxError: The requested module '@material-ui/core' does not provide an export named 'makeStyles' sandbox:102:18`

Here I have an example to reproduce it. Do you know how I can solve that?

https://jspm.org/sandbox#H4sIAAAAAAAAA71ZbVPjOBL+fPkV2mxtVajCdkyAYTIJFZjJbMERZo/A7b3UfVBsEQtsyyfJCWGK/34t+SU2iY0hVfeBULa6n6e71Wq3pMEvLnPkKiLIk4F/2hpk/wh2T1sIDQIiMXI8zAWRw3Ys742Tth6QVPrk9C7U/92BlTznKiEOyLC9oGQZMS7byGGhJCFALKkrvaFLFtQhhn7YRzSkkmLfEA72ydAGgoGVWDCYMXd12vrLwKULRN1hmzMm26cDC5412S+GgaYrIUlwOe2jaRwpOoF8hl0azlHA3NgnAkWE3zMe4FD6K6BD2PfRjLOlIFygGXYekWToYmzbqOOSiIRamYXIpzOO+QqJBHgPGYamFQ6nkUSCO8O2J2Uk+pY1x6bQlpgPIgpMyqwwCvrJqwcxOjZPzB7YLaQlzICGIKUcSZAUaObOXeiwIIBg5Y6hczwjYDDx2RKBHwiH4ISROoDGUzTRfiIL3cJcThPjLHQ5/QeCSKMl44/3oGtm5iuaD/hgzJQdo67ZM+3Uk9JI2aWULOWDfwgM+mOCfich4ViCGxeBCiqa4EiPjl0q0d3NVR/l5mSiuTm/Tg7+Pv/n7+fBt5MuX02fL6d3tudMvOur8aNcPT5PutPetT22flx1I3tyPX6+vv7b87+o99fbu2XcvetdPvfultfXE3g/fp5fPJyRs/Oj6Hv3883yDIwoT69aGMM21VYGOIK8/Amj6QvR7qOf2u72KMCScJXBMbUcxgkMFUNajOWG7OjQtG2VGWRh0tAlTyqK+wkwJ9iRNWB6fGQfm/ah2a1GMFwWvIWiZGqRNgy3hFzB2ioCa1RQtiqFAetFAbaFwyJSiOEW2/JBxa4TzOIxFJyAQHXwYUkLCwtYAPLWo+IiqSH0mbh10S/BjD6ZNqRytx5uHYNqOxwfVL9CVfnqEefx4waUcRoxw+xJ8lXp7UC7BmnC6ZJ7GpI/OMwgl6uP05ZxmjCTJ/iKuDt4mgI04ZoTCaZJpqrAj/uPU5ZxmjDT0IPFI3dwM0N4D9sVY6K2cjWj1DDNeKFEsOiG/DemnHwj9zj264rdm/xb4N5vx5/Udx3Mdygi2/GaWMJmD8SRf1LpsVimy4KSHdKgAnAHW3ZMkjrUJlZFTAg688lXFgrJYwdagxsiYx5+3KRKyCb2CB/aWPeWnXGOdyiEJZgmvHJXRvkeLhWaOMAQpJ1ZX0E14oe6yXaov4l+manYnmy2MXUtWyJd07RtwOsWuTG8ln4HfCyp39h4LZyAH1SAO754qoFTwyPbtLMNgHou6wthLOATy3gdSi40OjC75kmKlb81nYdykYLm1MibNNd9q90piI+OTKCwADBXrETmJGCLN3up7eAF3RK+x8A1I2ShkbTZQmJJnTr8Co1RD7ZdB0mkKkQ2wuatIo+EkACGTltD7crrmLeIw2R3zUMrSZTX+FQY631oDXBJTqdPuhPezL+H2tjD6Mjumsdqj6L0VQ7Duw3D4J0R+fEcWB1wwoff2s/WVvkS01aJOl436UCMGHYSzZiLGlXcRZk69rnPZthvxpvIVjEmo3VcIYGaVdcwbchum8OyRB1fBH2DMIQ6V2rEuZav8nEtUcfLY1gTC+zHxLiPQ0dSVtd21CvWRWCLeJ1ZSckEH2A39VS7DKuVqgLzSmzDjKSfM6Do0XldMEpy6gME34/NtR+xCKqqelWNlMuoMnJs2oYvRWJ2HLjWGmENCnNrqB6gFjUXGtlH5qfKr+NaznLUDl21sLcfwi6rl0ganvp8gsJcZec7j33ehqJ1HmYiTYAkx6GgKqeNOWdx9CbsawXIHsgf/c3dziMgtOo0tG4l5DIjsLfa5FzMAiscGs7fC5mqlUAlDVfGEvOwHq8opj/CvXWxKI5la1LDv+xXnqa93VoUz9veNevHuuMux7CJOZsr4/9uwubZZ9GE96aS/fm1DTunUg5ZSKXEMXWU2nppla8QstP9K4ZddU2Aowg00D31CVpyKiVRVwdIegRMSnYm6SUJ0hckEsHGPIol6iwoRjfM9+Pocoqs9AqieMGwt+02ITkyz68FEuh2csmQ2LJ5Q5DfRBQhUs3TVis5bkc3aqbQPWdBViG/lIa+/ZgUR3XxyyV+ovNYShbuowA/kqnew6GXVH7z+P5Lq+Wo4wAUi0x4WNDsqARRN1FZqqgbJFWcQhcm1achwRyKFXYpCWXn8Mgl83306/fx8fnJOep1f1MP30/GRz30ufvbXpojM8ZdwvuoW3y8AYxY9FEve/k09bDLlkDTRb3oCR3B3wH88fkMdw6OjvaR3VU/Pfgxexm2w3wG0O2lRyVJ33mEzj3w4PAkeY5gewT5lSB3oyctBqvnZS+PxlkUQRw6e2h4qh1P3uozax2hPFod0IEI6WMU9G8Nr+fITA6axz5R91uddG2kU5M+ZYsPoQWGSQnBxLa6PcQQVjdfT2ufIk4DzFeFESiT6oABWBZYfTf6SPKYFDSVwdfQxPcz2001mZnAS2EvTJ1HBFsm/WJPvf/Pl9YLxCPLOJNDg0S48mSbgxCwfRTGvq91XebE6rU5JzKVOF9duJ3kUnOvpYO2Xs4DK7n8HFjJpez/AGkTyi+sHQAA

**Comment by guybedford** [comment]
@albertocorrales this is a problem with Material UI itself - it is exporting a commonjs module (there is no "exports" field pointing to an ESM module), and CommonJS modules have unreliable support for named exports.

Instead you should import the default export:

```js
import MaterialUI from '@material-ui/core';
const { Button, makeStyles } = MaterialUI;
```

This is basically **the** common compatibility issue with ES modules.

Example working here - 

https://jspm.org/sandbox#H4sIAAAAAAAAA71ZbU/jOBD+fP0V3q5OAokkLaUsy7aowHZXcLS7x8ut7k73wU1MY0jsnO20lBX//cZ5a0KbEKh0EqWKPfM84/F4Mp723jncVouAIFf53lGjl34R7Bw1EOr5RGFku1hIovrNUN0aB81oQlHlkaMbFn07PSt+zlQY9km/OaNkHnChmsjmTBEGEHPqKLfvkBm1iRE97CDKqKLYM6SNPdJvA0HPii3oTbizOGr80nPoDFGn3xScq+ZRz4LniEzaggYKYblgNpLC7jddpQJ5aFlTbN7JwDcpt1jgHxJp+NwJPWJIl/py0DLb8Ac4UlnP5kyfMtDVNDG8ZtJk7wwDvhA6v/o+Ql8JIwIrLtCZr9eIRjiIZocOVejm8uIQZaakoplF70e7f0z//Hrifz5oicXV4/nVTdu1R+74YnivFvePo9ZVZ9weWt8uWkF7NB4+jse/P/5F3d+ub+Zh66Zz/ti5mY/HIxgfPk7P7o7J8Uk3+NL6eDk/BiMMI+8cvb/9Jo2s9HEA7v0Js8mAbB6in5HdzYGPFRF6I0Jq2VwQmCpz54rsYM9st82OBTtrUuaQB+3BnRhYEGyrCrBoftDeN9t7ZqscwXC4/xKKllmPFAE9abymtHlAcgtfA5hNar9M8IR4lggh2H0CkekFREgLS0mEunapPIvjlz4Sp8plBZjBB7PdgRishlu6oNwO2wPVU+x5py6x799uQBGnFjO4XJFTrbcB7RKkDqdDbikj3wXsoFCLt9MWceowkwfIYM4GK00A6nBNiQLTFNdH99vt2ymLOHWYKXPhXKsNlpkivIbtgnNZmW7qUUYw9Xghe/HgkvwbUkE+k1scelUZ6kX+NXCvt+MH9Rwbiw2SyHq8OpbwyR2x1Q+qXB6q5FhQskEYlABuYMuGQVKFWseqgEtJJx455UwqEdrwPr8kKhTs7SaVQtaxR3pQQjnX/FgIvEEiLMDU4VWbMqrXcGnXhD4GJ23M+gyqFj/kTb5B/o31i0z5ykmqhVd9yFalKyqtFfiFVKSqZloj/Qr4UFGvtvGRcAy+WwJue/KhAk5PD9pmOy3b9XNRX0pjBq9YLqpQMqHBrtkyDxKsbNS074pJCipKIyvSHOelcicnPuiaQGEBYKZYiiyIz2cv1lLrwXO6BXyXw9IMxpkR18ZSYUXtKvwSjUHH7Ohd054qEVlxm7sIXMIgAIwobA19I6xiXiMOm90y96w4UJ7jU2lQZkwEn0PdXAFckIvCpxMvZDX+7ip9D7MDuDPu64uF1tcxDGMrhsGYEXjhFFhtWIQH/ytfW2vlC0xrJap4nbgCMUK4SdRjzmuUcedlqtinHp9grx5vLFvGGM9WcTECOauqYFqRXbeHRYkqvgDqBmlI3dOoxbmUL1vjUqKKV+juxAx7ITFuQ2YryqvKjmrFKg+sEa8yK06ZsAa4TT1UHsNypTLHPBNbMSOu5wxIenRa5YyCnH4Bwftj9ewHPICsqofKkTIZnUb2zbbhKRmbHfqOtURYgsLeGroGqETNhAbtrvmh9O24lLNsfUPXJez1m7CL6gWSmq2aD5CYy+x8Za/mZShatcJUpA6QEphJqmPamAoeBi/CPleA6IH4id6563kkuFY3EqtOQiYzAHvLTc7ELLDCpmz6WshErQCqKFsYcyxYNV5eLHoJd5bJIj+Xnsllb219N+3l0iLfb3vVru9HFXdZq6/cnNWT8b+bsNqwzJvw2lBqf3xuw8ahlEHmQileWEN/nhrFBnnSIkcXHDsIM4SDADTQLfUImguqFGGIMqRcAibFNxMU993RLRdwV0BwMQ9ChbZmFKNL7nlhcH6FLHSi71jwrdPVVUS4nba4NV+xzx0j36Ut/Wb8q0BsS66lv7ZHnqgcNRpxcxxd6i1Ct4L7aWr8VJj6/G2Un42yXiYxSm4/N2eJzGqD/VPD1ld/9BOdhEpxtoN8fE+uonseekL9HManRiIbylSgn5Pe0oGjfx1JQ2iC7XudtJgDm+1RRrCAJIYdSpja2us6ZLqD3n8Z7p8cnKBO61f98OVg2O2gj61ft5PYmXDhEHGIWvnHS8AI5SHqpIMPVy52+BxoWqgTPKAufHbhI6YTvLXb7e6gdkv/68A/s5Ni29zjAN2cu1SRZMwldOrCCvYO4ucArk0QdzFyK3iIxOBUPW1n3jgOAvDD1jbqH0ULj0ejXnbkocxbW6ADHoraK+jvCD7aQjNuQA894mvPJGcm2Y7kKT2UCM0w7AYDE5v6Fy0MbnWyc7ZcUyCoj8UiNwPpUzcegGWG9fvkECkRkpymNngMxf1harupNzMVeMrdkal9j+AqFQ1s6/F/PjWewB9pQJoCCici9ErWLRActoNY6HmRrsPtUA+bU6ISiZPFmbMV/9C23YictjzmPSv+Qa5nxT8U/gcPxNxJQBwAAA==

**Comment by guybedford** [comment]
Actually, this named export should be detected! And it's a bug that it's not. Looking into a fix...

**Comment by guybedford** [comment]
Root cause fixed in https://github.com/guybedford/cjs-module-lexer/pull/51.

**Comment by guybedford** [comment]
The named exports issue is now fixed (and actually will be upstreamed into Node.js core itself).

If you clear your cache, the example should be working at https://jspm.org/sandbox#H4sIAAAAAAAAA71ZbVPbOBD+fPkVajqdgRlsJwQopQkToGmnHKE9Atd7mfug2EossC2fJCeEDv/9Vpbt2CQ2hszcTF7G0u7z7K5WsrTqvnGYLRchQa70veNGN/0j2DluINT1icTIdjEXRPaakZwYh824Q1LpkeObIP53upZ+zlQC7JNec0bJPGRcNpHNAkkCgJhTR7o9h8yoTYz4YQfRgEqKPUPY2CO9NhB0LW1Bd8ycxXHjl65DZ4g6vSZnTDaPuxY8x2TC5jSUCItFYCPB7V7TlTIUR5Y1xeatCH2TMisI/SMiDJ85kUcM4VJf9FtmGz6AI6T1pM/0aQC6ikbDKyZF9sYw0E1gM98HV9BoISTxz0foFI+Jh+DL5mjCOMIBeGSMOZsLwtFghIYxOLLQNUR6pC220PnoDwRxQHPG7yagayLDOE5pUseeuiRi0oJnuulWGGNlBzjWSf0q9hRdSsgSPvhDYND3IfpCAsKxBDe++mro0BCHce/AoRLdXF0cocycVDQz5+1w9/fpn19O/U+HLb4YPZyPbtquPXQvLwZ3cnH3MGyNOpftgfXtohW2h5eDh8vL3x7+ou6v1zfzqHXTOX/o3MwvL4fQPniYfr09ISen++Hn1oer+QkYkcQnCY1K216Txlb6OISs+Qm9SYNoHqGfsd3Nvo8l4Sq/ImrZjBPoKsuSFdn+ntlumx0LBsqkgUPuVRR3NDAn2JYVYHF/v31gtvfMVjmC4TD/ORQlsx4pBnpUeE1hs5DkHF8DmHWquMRZYfEI5rBPYMJ5IeHCwgKyVl67VHzV05I+EKcqZAWY/nuzDfnXqoZbhqDcDtsD1TPseWcuse9eb0ARpxYzhFySM6W3Ae0SpA6nQyY0IN85jCCXi9fTFnHqMJN7WJidDTxNAOpwTYkE0yRTU/fb5PWURZw6zDRwYV7LDdxMEV7CdsGYqFxu6lHGMPV4YfVi4RX5N6KcfCITHHlVK9Sz/GvgXm7HD+o5NuYbLCLr8epYwsa3xJY/qHRZJJNpQckGaVACuIEtGyZJFWodq0ImBB175IwFQvLIhvf5FZERD15vUilkHXuEBztD55qdcI43WAgLMHV45aaM8iVcKjSRjyFIG7M+garFD+sm22D91fpFpvzOSciFVz3JVqUrdlor8PG+tjZ8LP0C+EhSr7bxsbAG3y0Btz1xXwGnuvtts53u2tVzUV8IYwavWMarUDKh/q7ZMg8TrKzVtG+LixTsKI1sk+Y4z213cuL9fRMoLADMFEuROfHZ7Nm91HrwnG4B32XgmhGwwNB7YyGxpHYVfolGvwNnpV0dqRKRlbC5i9AlASSAEaetoQ66VcxrxGGwW+aepRPlKT4VxvLwWAFckIvTp6MdWc2/28rYQ28fjsIH6mCh9FUOQ9uKYdBmhF40BVYbnPDgt/K1tVa+wLRWoorX0TsQI4KTRD3mvEYZd16min3qsTH26vFq2TJG3VvFFRBYs6o2TCuy68awKFHFF8K+QRhClWpqcS7ly3xcSlTxclV0mWEvIsYkCmxJWdW2o1qxKgJrxKvM0ksm+ACnqfvKaViuVBaYJ2IrZuj9nAGLHp1WBaMgp15A8P5YnfshC2FVVU3lSJmMWkYOzLbhSaHNjnzHWiIsQWFsDbUHqETNhPrtffN96dtxKWfZ6oSutrDXr8IuqhdIapZq3sPCXGbnC2s1z0PRKg9TkTpAkuNAUJXTxpSzKHwW9qkCZA/kT/zOXc8jILSqhFk1EzKZPthbbnImZoEVNg2mL4VM1AqgkgYLY455UI2XF4tfwp3lYpHvS+fksra2vpr2/NYiX2970agfxDvuslJfuTmrM+N/N2G1YJk34aWp1P7w1IaNUymDzKWSdqyhvo+NYt0/LclfMOyo2j4OQ9BAE+oRNOdUSqLq/Ui6BEzSJxOkrxPUbQCcFRAczMNIoq0ZxeiKeV4Uno+Qldwb5G8FttddAeg6d1bL19BNfTOgbVkt62fXB3mIRPO40dA1cnSlRgpNOPPTFfJjoevTt2G+N178Momf6DSSkgU7yMd3ZBSf4dBjIr9ac//YaNiqHIAikQr3cppbKkHU5U6aKmNs36nFKXBgUD0aEMxhscIOJYHc2tt3yHQHvf08ODg9PEWd1jv18PlwsN9BH1rvtpMcGTPuEH6EWvnHK8CIxBHqpI33Ixc7bA40LdQJ79E+fHfhy6djvLW7v7+D2i3104Efs5Ni28xjAN2cu1SSpM0ldOqCB3uH+jmE4xHkl0ZuhfexGMyex+0sGidhCHHY2ka949hx3RrXrOMIZdHaAh2IUFxGQX/H8PEYmbrQPPCIupTaSuZGMjTJUzr5EJphGJQATGyqCzkMYXWy+bT0KeTUx3yR64FlUhUYgGWG1XvjCEkekZymMvgSNvFHqe2mGsxU4DF3Fqb2HYIjU9ywrdr/+dh4hHikGWdy2CARrjxZ5yAEbAcFkefFug6zI9VsTolMJE4XX50tfU+43YiDtpzOXUvfJ3Ytfc/5H9MmLOH/HAAA

This issue is still tracking the import map generation issue, so will leave it open for a little longer still.

**Comment by guybedford** [comment]
@albertocorrales I've updated the generator to fix the original generation bug as well, so the direct generator map should now be working correctly!

Let me know if we are good to close this now, I believe so :) Was some nice bugs to catch.

**Comment by albertocorrales** [comment]
Hey @guybedford, I've just tested it and it works beautifully. 

Thank you so much for your quick response and resolution. Closing this issue.
